// frontend/react_js/components/community/BoardComment.js
import { useState, useEffect } from 'react'
import { useAuth } from '@/contexts/AuthContext'
import { useAlert } from '@/contexts/AlertContext'
import { api } from '@/lib/axios'
import styles from './BoardComment.module.css'

export default function BoardComment({ comments = [], boardSq, boardType, onRefresh }) {
  const { user } = useAuth()
  const { showAlert } = useAlert()
  const [newComment, setNewComment] = useState('')
  const [editSq, setEditSq] = useState(null)
  const [editDescription, setEditDescription] = useState('')
  
  // 대댓글 관련 상태
  const [showReplyForm, setShowReplyForm] = useState(null)
  const [replyDescription, setReplyDescription] = useState('')
  const [editReplySq, setEditReplySq] = useState(null)
  const [editReplyDescription, setEditReplyDescription] = useState('')
  const [commentReplies, setCommentReplies] = useState({})
  
  const viewerSq = user?.userSq || null
  
  // 대댓글 목록 구성
  useEffect(() => {
    console.log('댓글 데이터:', comments)
    const replies = {}
    comments.forEach(comment => {
      // Vue에서는 comment.replies 사용, 둘 다 지원
      const replyList = comment.replyComments || comment.replies || []
      console.log(`댓글 ${comment.sq}의 대댓글:`, replyList)
      if (Array.isArray(replyList)) {
        replies[comment.sq] = replyList
      }
    })
    setCommentReplies(replies)
    console.log('최종 대댓글 목록:', replies)
  }, [comments])
  
  // 날짜 포맷
  const formatTime = (createdAt) => {
    if (!createdAt) return ''
    const date = new Date(createdAt)
    const year = date.getFullYear()
    let month = date.getMonth() + 1
    let day = date.getDate()
    let hour = date.getHours()
    let minute = date.getMinutes()
    
    if (month < 10) month = '0' + month
    if (day < 10) day = '0' + day
    if (hour < 10) hour = '0' + hour
    if (minute < 10) minute = '0' + minute
    
    return `${year}-${month}-${day} ${hour}:${minute}`
  }
  
  // 댓글 등록
  const handleSubmit = async (e) => {
    e.preventDefault()
    if (!viewerSq) {
      showAlert('로그인 후 이용해주세요.', 'danger')
      return
    }
    if (!newComment.trim()) {
      showAlert('댓글을 입력해주세요.', 'danger')
      return
    }
    
    try {
      const response = await api.$post(`/${boardType}/${boardSq}/comment`, {
        description: newComment
      })
      if (response.status === 'OK') {
        showAlert('댓글이 등록되었습니다.', 'success')
        setNewComment('')
        onRefresh()
      } else {
        showAlert('댓글 등록에 실패했습니다.', 'danger')
      }
    } catch (error) {
      showAlert('댓글 등록에 실패했습니다.', 'danger')
    }
  }
  
  // 댓글 수정 모드
  const clickEdit = (commentSq, description) => {
    setEditSq(commentSq)
    setEditDescription(description)
  }
  
  // 댓글 수정 제출
  const editRegisterConfirm = async (e, commentSq) => {
    e.preventDefault()
    try {
      const response = await api.$put(`/comment/${commentSq}`, {
        description: editDescription
      })
      if (response.status === 'OK') {
        showAlert('댓글이 수정되었습니다.', 'success')
        setEditSq(null)
        setEditDescription('')
        onRefresh()
      } else {
        showAlert('댓글 수정에 실패했습니다.', 'danger')
      }
    } catch (error) {
      showAlert('댓글 수정에 실패했습니다.', 'danger')
    }
  }
  
  // 댓글 삭제
  const openDeleteConfirm = async (commentSq) => {
    if (!confirm('댓글을 삭제하시겠습니까?')) return
    
    try {
      const response = await api.$patch(`/comment/${commentSq}`)
      if (response.status === 'OK') {
        showAlert('댓글이 삭제되었습니다.', 'success')
        onRefresh()
      } else {
        showAlert('댓글 삭제에 실패했습니다.', 'danger')
      }
    } catch (error) {
      showAlert('댓글 삭제에 실패했습니다.', 'danger')
    }
  }
  
  // 댓글 추천
  const rcmndComment = async (commentSq) => {
    if (!viewerSq) {
      showAlert('로그인 후 이용해주세요.', 'danger')
      return
    }
    try {
      const response = await api.$post(`/comment/${commentSq}/recommend`)
      if (response.status === 'OK') {
        showAlert(response.message, 'success')
        onRefresh()
      } else {
        showAlert('추천 반영에 실패했습니다.', 'danger')
      }
    } catch (error) {
      showAlert('추천 반영에 실패했습니다.', 'danger')
    }
  }
  
  // 댓글 신고
  const clickReportApplication = (commentSq) => {
    if (!viewerSq) {
      showAlert('로그인 후 이용해주세요.', 'danger')
      return
    }
    showAlert('신고 기능은 준비 중입니다.', 'info')
  }
  
  // 대댓글 작성
  const createReply = async (e, commentSq) => {
    e.preventDefault()
    if (!viewerSq) {
      showAlert('로그인 후 이용해주세요.', 'danger')
      return
    }
    if (!replyDescription.trim()) {
      showAlert('내용을 입력해주세요.', 'danger')
      return
    }
    
    try {
      const response = await api.$post('/reply', {
        commentSq: commentSq,
        boardSq: boardSq,
        description: replyDescription
      })
      
      if (response.status === 'CREATED') {
        showAlert(response.message, 'success')
        setReplyDescription('')
        setShowReplyForm(null)
        onRefresh()
      }
    } catch (error) {
      showAlert('대댓글 등록에 실패하였습니다.', 'danger')
    }
  }
  
  // 대댓글 수정 모드
  const clickEditReply = (replyCommentSq, description) => {
    setEditReplySq(replyCommentSq)
    setEditReplyDescription(description)
  }
  
  // 대댓글 수정 제출
  const editReplyConfirm = async (e, replyCommentSq) => {
    e.preventDefault()
    if (!editReplyDescription.trim()) {
      showAlert('내용을 입력해주세요.', 'danger')
      return
    }
    
    try {
      // Vue와 동일하게 query parameter로 전달
      const params = new URLSearchParams()
      params.append('description', editReplyDescription)
      const response = await api.$put(`/reply/${replyCommentSq}?${params.toString()}`)
      
      if (response.status === 'OK') {
        showAlert(response.message || '대댓글이 수정되었습니다.', 'success')
        setEditReplySq(null)
        setEditReplyDescription('')
        onRefresh()
      }
    } catch (error) {
      showAlert('대댓글 수정에 실패했습니다.', 'danger')
    }
  }
  
  // 대댓글 삭제
  const deleteReply = async (replyCommentSq) => {
    if (!confirm('대댓글을 삭제하시겠습니까?')) return
    
    try {
      const response = await api.$patch(`/reply/${replyCommentSq}`)
      if (response.status === 'OK') {
        showAlert('대댓글이 삭제되었습니다.', 'success')
        onRefresh()
      }
    } catch (error) {
      showAlert('대댓글 삭제에 실패했습니다.', 'danger')
    }
  }
  
  // 대댓글 추천
  const rcmndReply = async (replyCommentSq) => {
    if (!viewerSq) {
      showAlert('로그인 후 이용해주세요.', 'danger')
      return
    }
    
    try {
      const response = await api.$post(`/reply/${replyCommentSq}/recommend`)
      if (response.status === 'OK') {
        showAlert(response.message, 'success')
        onRefresh()
      }
    } catch (error) {
      showAlert('대댓글 추천에 실패하였습니다.', 'danger')
    }
  }
  
  // 대댓글 신고
  const clickReportReply = (replyCommentSq) => {
    if (!viewerSq) {
      showAlert('로그인 후 이용해주세요.', 'danger')
      return
    }
    showAlert('신고 기능은 준비 중입니다.', 'info')
  }
  
  return (
    <div>
      <div className="post-comments mt-5 post-comments">
        <h4 className={`mb-3 ${styles.fontSize15}`}>댓글 ({comments.length})</h4>
        <ul className="comments">
          {comments.map((comment) => (
            <li key={comment.sq}>
              <div className="comment">
                <div className={`img-thumbnail img-thumbnail-no-borders d-none d-sm-block ${styles.thumbWrapper}`}>
                  {comment.userProfileImgUrl ? (
                    <img
                      className="avatar object-fit-cover"
                      alt=""
                      src={comment.userProfileImgUrl}
                    />
                  ) : (
                    <div className={`rounded-circle ${styles.commentProfile}`}>
                      <i className="fas fa-user text-muted"></i>
                    </div>
                  )}
                </div>
                <div className={`comment-block ${styles.fontSize12}`}>
                  <div className="comment-arrow"></div>
                  {/* 이름 + 버튼 */}
                  {editSq !== comment.sq && (
                    <div className="d-flex justify-content-between align-items-center mb-2">
                      <span className={`comment-by text-primary ${styles.fontSize13}`}>
                        <strong>{comment.userNm}</strong>
                      </span>
                      {/* 작성자 본인 */}
                      {comment.userSq === viewerSq ? (
                        <span className="comment-icons d-flex">
                          <button
                            className={`text-danger me-2 ${styles.fontSize10}`}
                            onClick={() => clickEdit(comment.sq, comment.description)}
                            style={{ background: 'none', border: 'none', cursor: 'pointer' }}
                          >
                            <span className="ms-2 text-primary">수정</span>
                          </button>
                          <button
                            className={`text-danger ${styles.fontSize10}`}
                            onClick={() => openDeleteConfirm(comment.sq)}
                            style={{ background: 'none', border: 'none', cursor: 'pointer' }}
                          >
                            <span className="ms-2 text-primary">삭제</span>
                          </button>
                        </span>
                      ) : (
                        /* 다른 사람 */
                        <span className="comment-icons d-flex">
                          <button
                            className={`text-danger me-2 ${styles.fontSize10}`}
                            onClick={() => rcmndComment(comment.sq)}
                            style={{ background: 'none', border: 'none', cursor: 'pointer' }}
                          >
                            <span className="ms-2 text-primary">
                              추천 {comment.recommendCnt || 0}
                            </span>
                          </button>
                          <button
                            className={`text-danger ${styles.fontSize10}`}
                            onClick={() => clickReportApplication(comment.sq)}
                            style={{ background: 'none', border: 'none', cursor: 'pointer' }}
                          >
                            <span className="ms-2 text-primary">신고</span>
                          </button>
                        </span>
                      )}
                    </div>
                  )}
                  
                  {/* 내용 */}
                  {editSq !== comment.sq ? (
                    <p className={styles.fontSize12}>{comment.description}</p>
                  ) : (
                    <form onSubmit={(e) => editRegisterConfirm(e, comment.sq)}>
                      <div className="input-group">
                        <input
                          value={editDescription}
                          onChange={(e) => setEditDescription(e.target.value)}
                          type="text"
                          maxLength="5000"
                          className="form-control"
                          placeholder="댓글을 입력해주세요"
                          required
                        />
                        <button type="submit" className="btn btn-primary">
                          댓글 수정
                        </button>
                      </div>
                    </form>
                  )}
                  
                  {/* 날짜 */}
                  {editSq !== comment.sq && (
                    <span className={`date float-end ${styles.fontSize11}`}>
                      {formatTime(comment.createdAt)}
                    </span>
                  )}
                  
                  {/* 대댓글 달기 버튼 */}
                  {editSq !== comment.sq && (
                    <div className="mt-2 mb-2" style={{ clear: 'both' }}>
                      {showReplyForm !== comment.sq ? (
                        <button
                          onClick={() => setShowReplyForm(comment.sq)}
                          className={`btn btn-link btn-sm p-0 text-primary ${styles.fontSize11}`}
                          style={{ textDecoration: 'none', background: 'none', border: 'none', cursor: 'pointer' }}
                        >
                          대댓글 달기
                        </button>
                      ) : null}
                    </div>
                  )}
                  
                  {/* 대댓글 목록 */}
                  {commentReplies[comment.sq] && commentReplies[comment.sq].length > 0 && (
                    <ul className="comments replies">
                      {commentReplies[comment.sq].map((reply) => {
                        const replyCreatedAt =
                          reply.replyCommentCreatedAtDtm ||
                          reply.replyCommentCreatedAt ||
                          reply.createdAt ||
                          null

                        return (
                        <li key={reply.replyCommentSq}>
                          <div className="comment">
                            <div className={`img-thumbnail img-thumbnail-no-borders d-none d-sm-block ${styles.thumbWrapper}`}>
                              <div className={`rounded-circle ${styles.commentProfile}`}>
                                <i className="fas fa-user text-muted"></i>
                              </div>
                            </div>
                            <div className={`comment-block ${styles.fontSize12}`}>
                              <div className="comment-arrow"></div>
                              {editReplySq !== reply.replyCommentSq && (
                                <div className="d-flex justify-content-between align-items-center mb-2">
                                  <span className={`comment-by text-primary ${styles.fontSize13}`}>
                                    <i className="fas fa-level-up-alt fa-rotate-90 me-2" style={{ fontSize: '0.8rem', opacity: 0.6 }}></i>
                                    <strong>{reply.userNm}</strong>
                                  </span>
                                  {reply.userSq === viewerSq ? (
                                    <span className="comment-icons d-flex">
                                      <button
                                        onClick={() => clickEditReply(reply.replyCommentSq, reply.replyCommentDescriptionTxt)}
                                        className={`text-danger me-2 ${styles.fontSize10}`}
                                        style={{ background: 'none', border: 'none', cursor: 'pointer' }}
                                      >
                                        <span className="ms-2 text-primary">수정</span>
                                      </button>
                                      <button
                                        onClick={() => deleteReply(reply.replyCommentSq)}
                                        className={`text-danger ${styles.fontSize10}`}
                                        style={{ background: 'none', border: 'none', cursor: 'pointer' }}
                                      >
                                        <span className="ms-2 text-primary">삭제</span>
                                      </button>
                                    </span>
                                  ) : (
                                    <span className="comment-icons d-flex">
                                      <button
                                        onClick={() => rcmndReply(reply.replyCommentSq)}
                                        className={`text-danger me-2 ${styles.fontSize10}`}
                                        style={{ background: 'none', border: 'none', cursor: 'pointer' }}
                                      >
                                        <span className="ms-2 text-primary">
                                          추천 {reply.replyCommentRecommendCnt || 0}
                                        </span>
                                      </button>
                                      <button
                                        onClick={() => clickReportReply(reply.replyCommentSq)}
                                        className={`text-danger ${styles.fontSize10}`}
                                        style={{ background: 'none', border: 'none', cursor: 'pointer' }}
                                      >
                                        <span className="ms-2 text-primary">신고</span>
                                      </button>
                                    </span>
                                  )}
                                </div>
                              )}
                              {editReplySq !== reply.replyCommentSq ? (
                                <p className={styles.fontSize12}>{reply.replyCommentDescriptionTxt}</p>
                              ) : (
                                <form onSubmit={(e) => editReplyConfirm(e, reply.replyCommentSq)}>
                                  <div className="input-group">
                                    <input
                                      value={editReplyDescription}
                                      onChange={(e) => setEditReplyDescription(e.target.value)}
                                      type="text"
                                      maxLength="5000"
                                      className="form-control"
                                      placeholder="대댓글을 입력해주세요"
                                      required
                                    />
                                    <button type="submit" className="btn btn-primary">
                                      대댓글 수정
                                    </button>
                                  </div>
                                </form>
                              )}
                              {editReplySq !== reply.replyCommentSq && (
                                <span className={`date ${styles.replyDate} ${styles.fontSize11}`}>
                                  {formatTime(replyCreatedAt)}
                                </span>
                              )}
                            </div>
                          </div>
                        </li>
                        )})}
                    </ul>
                  )}
                  
                  {/* 대댓글 작성 폼 */}
                  {showReplyForm === comment.sq && (
                    <div className="mt-3">
                      <form onSubmit={(e) => createReply(e, comment.sq)}>
                        <div className="input-group">
                          <input
                            value={replyDescription}
                            onChange={(e) => setReplyDescription(e.target.value)}
                            type="text"
                            maxLength="5000"
                            className="form-control"
                            placeholder="대댓글을 입력해주세요"
                          />
                          <button type="submit" className="btn btn-primary">
                            대댓글 작성
                          </button>
                          <button
                            type="button"
                            className="btn btn-secondary"
                            onClick={() => setShowReplyForm(null)}
                          >
                            취소
                          </button>
                        </div>
                      </form>
                    </div>
                  )}
                </div>
              </div>
            </li>
          ))}
        </ul>
      </div>
      
      {/* 댓글 작성 폼 */}
      <div className="post-comments mt-4">
        <h4 className={`mb-3 ${styles.fontSize15}`}>댓글 작성</h4>
        <form onSubmit={handleSubmit}>
          <div className="input-group">
            <input
              value={newComment}
              onChange={(e) => setNewComment(e.target.value)}
              type="text"
              maxLength="5000"
              className="form-control"
              placeholder="댓글을 입력해주세요"
            />
            <button type="submit" className="btn btn-primary">
              댓글 작성
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}

// frontend/vue_js/src/fo/components/community/BoardComment.vue
<template>
  <div>
    <div class="post-comments mt-5 post-comments">
      <h4 class="mb-3 font-size-15">댓글 ({{ props.comments.length }})</h4>
      <ul class="comments">
        <li v-for="comment in props.comments" :key="comment">
          <div class="comment">
            <div
              class="img-thumbnail img-thumbnail-no-borders d-none d-sm-block"
            >
              <img
                v-if="comment.userProfileImgUrl != null"
                class="avatar object-fit-cover"
                alt=""
                :src="`${comment.userProfileImgUrl}`"
              />
              <div v-else class="rounded-circle comment-profile">
                <i class="fas fa-user text-muted"></i>
              </div>
            </div>
            <div class="comment-block font-size-12">
              <div class="comment-arrow"></div>
              <!-- 이름 + 신고/하트 -->
              <div
                class="d-flex justify-content-between align-items-center mb-2"
                v-show="editSq != comment.sq"
              >
                <span class="comment-by text-primary font-size-13">
                  <strong>{{ comment.userNm }}</strong>
                </span>
                <!-- 작성자 본인일 경우 -->
                <span
                  v-if="comment.userSq == viewerSq"
                  class="comment-icons d-flex"
                >
                  <button
                    href="#"
                    class="text-danger me-2 font-size-10"
                    @click="clickEdit(comment.sq, comment.description)"
                  >
                    <span class="ms-2 text-primary">수정</span>
                  </button>
                  <button
                    href="#"
                    class="text-danger font-size-10"
                    @click="openDeleteConfirm(comment.sq)"
                  >
                    <span class="ms-2 text-primary">삭제</span>
                  </button>
                </span>
                <!-- 작성자 아닌 경우 -->
                <span v-else class="comment-icons d-flex">
                  <button
                    class="text-danger me-2 font-size-10"
                    @click="rcmndComment(comment.sq)"
                  >
                    <span class="ms-2 text-primary"
                      >추천 {{ comment.recommendCnt }}</span
                    >
                  </button>
                  <button
                    class="text-danger font-size-10"
                    @click="clickReportApplication(comment.sq)"
                  >
                    <span class="ms-2 text-primary">신고</span>
                  </button>
                </span>
              </div>
              <!-- 내용 -->
              <p class="font-size-12" v-show="editSq != comment.sq">
                {{ comment.description }}
              </p>
              <form @submit.prevent="editRegisterConfirm(comment.sq)">
                <div class="input-group" v-if="editSq == comment.sq">
                  <input
                    v-model="editdescription"
                    type="text"
                    maxlength="5000"
                    class="form-control"
                    name="message"
                    placeholder="댓글을 입력해주세요"
                    required
                  />
                  <button
                    type="submit"
                    class="btn btn-primary"
                    data-loading-text="로딩 중..."
                  >
                    댓글 작성
                  </button>
                </div>
              </form>
              
              <!-- 날짜 -->
              <span
                class="date float-end font-size-11"
                v-show="editSq != comment.sq"
              >
                {{ formatTime(comment.createdAt) }}
              </span>
              
              <!-- 대댓글 달기 버튼 -->
              <div v-show="editSq != comment.sq" class="mt-2 mb-2" style="clear: both;">
                <button 
                  v-if="showReplyForm !== comment.sq" 
                  @click="showReplyForm = comment.sq" 
                  class="btn btn-link btn-sm p-0 text-primary font-size-11"
                  style="text-decoration: none;">
                  대댓글 달기
                </button>
              </div>
              
              <!-- 대댓글 목록 -->
              <ul v-if="commentReplies[comment.sq] && commentReplies[comment.sq].length > 0" class="comments replies">
                <li v-for="reply in commentReplies[comment.sq]" :key="reply.replyCommentSq">
                  <div class="comment">
                    <div class="img-thumbnail img-thumbnail-no-borders d-none d-sm-block">
                      <div class="rounded-circle comment-profile">
                        <i class="fas fa-user text-muted"></i>
                      </div>
                    </div>
                    <div class="comment-block font-size-12">
                      <div class="comment-arrow"></div>
                      <div class="d-flex justify-content-between align-items-center mb-2" v-show="editReplySq != reply.replyCommentSq">
                        <span class="comment-by text-primary font-size-13">
                          <i class="fas fa-level-up-alt fa-rotate-90 me-2" style="font-size: 0.8rem; opacity: 0.6;"></i>
                          <strong>{{ reply.userNm }}</strong>
                        </span>
                        <!-- 본인 대댓글일 경우 -->
                        <span v-if="reply.userSq == viewerSq" class="comment-icons d-flex">
                          <button @click="clickEditReply(reply.replyCommentSq, reply.replyCommentDescriptionTxt)" class="text-danger me-2 font-size-10">
                            <span class="ms-2 text-primary">수정</span>
                          </button>
                          <button @click="openDeleteReplyConfirm(reply.replyCommentSq)" class="text-danger font-size-10">
                            <span class="ms-2 text-primary">삭제</span>
                          </button>
                        </span>
                        <!-- 다른 사람 대댓글일 경우 -->
                        <span v-else class="comment-icons d-flex">
                          <button @click="rcmndReply(reply.replyCommentSq)" class="text-danger me-2 font-size-10">
                            <span class="ms-2 text-primary">추천 {{ reply.replyCommentRecommendCnt || 0 }}</span>
                          </button>
                          <button @click="clickReportReply(reply.replyCommentSq)" class="text-danger font-size-10">
                            <span class="ms-2 text-primary">신고</span>
                          </button>
                        </span>
                      </div>
                      <p class="font-size-12" v-show="editReplySq != reply.replyCommentSq">{{ reply.replyCommentDescriptionTxt }}</p>
                      
                      <!-- 대댓글 수정 폼 -->
                      <form @submit.prevent="updateReply(reply.replyCommentSq)" v-if="editReplySq == reply.replyCommentSq">
                        <div class="input-group">
                          <input
                            v-model="editReplyDescription"
                            type="text"
                            maxlength="5000"
                            class="form-control"
                            placeholder="대댓글을 입력해주세요"
                            required
                          />
                          <button type="submit" class="btn btn-primary btn-sm">수정</button>
                          <button type="button" @click="editReplySq = null" class="btn btn-secondary btn-sm">취소</button>
                        </div>
                      </form>
                      
                      <span class="date float-end font-size-11" v-show="editReplySq != reply.replyCommentSq">{{ formatTime(reply.replyCommentCreatedAtDtm) }}</span>
                    </div>
                  </div>
                </li>
              </ul>
              
              <!-- 대댓글 작성 폼 -->
              <div v-if="showReplyForm === comment.sq" class="reply-form mt-3 ms-5">
                <form @submit.prevent="createReply(comment.sq)">
                  <div class="input-group">
                    <input 
                      v-model="replyDescription" 
                      type="text" 
                      maxlength="5000"
                      class="form-control" 
                      placeholder="대댓글을 입력해주세요" 
                      required 
                    />
                    <button type="submit" class="btn btn-primary btn-sm">작성</button>
                    <button type="button" @click="showReplyForm = null" class="btn btn-secondary btn-sm">취소</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </li>
      </ul>
    </div>
    <div class="post-block mt-5 post-leave-comment">
      <form
        class="contact-form p-4 rounded bg-color-grey"
        @submit.prevent="openRegisterConfirm"
      >
        <div class="p-2">
          <div class="row">
            <label class="form-label font-weight-bold text-dark text-5 mb-3"
              >댓글 남기기</label
            >
            <div class="input-group">
              <input
                v-model="description"
                type="text"
                maxlength="5000"
                class="form-control"
                name="message"
                placeholder="댓글을 입력해주세요"
                required
              />
              <button
                type="submit"
                class="btn btn-primary"
                data-loading-text="로딩 중..."
              >
                댓글 작성
              </button>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</template>
<script setup>
import { useAlertStore } from '@/fo/stores/alertStore'
import { useModalStore } from '@/fo/stores/modalStore'
import { defineProps, onMounted, ref, watch } from 'vue'
import CommonConfirmModal from '../common/CommonConfirmModal.vue'
import { api } from '@/axios'
import { useRoute } from 'vue-router'
import ReportModal from './ReportModal.vue'
import { useBoardStore } from '@/fo/stores/boardStore'

const alertStore = useAlertStore()
const modalStore = useModalStore()
const boardStore = useBoardStore()

const route = useRoute()
const boardSq = route.params.board_sq
const editSq = ref(null)
const viewerSq = ref(boardStore.viewerSq)

const formatTime = (createdAt) => {
  const date = new Date(createdAt)
  let year = date.getFullYear()
  let month = date.getMonth() + 1
  let day = date.getDate()
  let hour = date.getHours()
  let minute = date.getMinutes()
  let timePeriod = 'am'
  if (hour > 12) {
    hour += -12
    timePeriod = 'pm'
  }
  if (minute < 10) minute = '0' + minute

  return `${year}년 ${month}월 ${day}일 ${hour}:${minute} ${timePeriod}`
}

const props = defineProps({
  comments: {
    type: Array,
    default: () => [],
  },
  isAnswer: {
    type: Boolean,
    default: false,
  },
  answerSq: {
    type: Number,
    default: 0,
  },
  getBoard: {
    type: Function,
    default: () => {},
  },
})

const description = ref('')
const editdescription = ref('')
const replyDescription = ref('')
const showReplyForm = ref(null)
const commentReplies = ref({})
const editReplySq = ref(null)
const editReplyDescription = ref('')

// 추천
const rcmndComment = async (sq) => {
  if (viewerSq.value == null) {
    alertStore.show('로그인 후 이용해주세요.', 'danger')
    return
  }
  const res = await api.$post(`/comment/${sq}/recommend`)

  if (res.status == 'OK') {
    alertStore.show(res.message, 'success')
    props.getBoard()
  } else {
    alertStore.show('추천 반영에 실패하였습니다.', 'danger')
  }
}

// 삭제 컨펌 모달
const openDeleteConfirm = (sq) => {
  modalStore.openModal(CommonConfirmModal, {
    title: '댓글 삭제',
    message: '정말 삭제하시겠습니까?',
    onConfirm: async () => {
      try {
        const res = await api.$patch(`/comment/${sq}`)

        if (res.status == 'OK') {
          alertStore.show(res.message, 'success')
          editSq.value = null
          editdescription.value = ''
          props.getBoard()
        } else {
          alertStore.show('댓글 삭제에 실패하였습니다.', 'danger')
        }
      } catch (error) {
        alertStore.show('댓글 삭제에 실패하였습니다.', 'danger')
      }
      modalStore.closeModal()
    },
  })
}

// 수정
const clickEdit = (idx, description) => {
  editSq.value = idx
  editdescription.value = description
}
const editRegisterConfirm = (sq) => {
  if (editdescription.value == null || editdescription.value.trim() == '') {
    alertStore.show('내용을 입력해주세요.', 'danger')
    return
  }
  modalStore.openModal(CommonConfirmModal, {
    title: '댓글 수정',
    message: '댓글을 수정하시겠습니까?',
    onConfirm: async () => {
      try {
        const res = await api.$put(`/comment/${sq}`, {
          description: editdescription.value,
        })

        if (res.status == 'OK') {
          alertStore.show(res.message, 'success')
          editSq.value = null
          editdescription.value = ''
          props.getBoard()
        } else {
          alertStore.show('댓글 수정에 실패하였습니다.', 'danger')
        }
      } catch (error) {
        alertStore.show('댓글 수정에 실패하였습니다.', 'danger')
      }
      modalStore.closeModal()
    },
  })
}

// 댓글 등록 컨펌 모달
const openRegisterConfirm = () => {
  if (viewerSq.value == null) {
    alertStore.show('로그인 후 이용해주세요.', 'danger')
    return
  }
  if (description.value == null || description.value.trim() == '') {
    alertStore.show('내용을 입력해주세요.', 'danger')
    return
  }
  modalStore.openModal(CommonConfirmModal, {
    title: '댓글 등록',
    message: '댓글을 등록하시겠습니까?',
    onConfirm: async () => {
      try {
        const res = await api.$post(`/comment`, {
          userSq: 4,
          boardSq: props.isAnswer ? null : boardSq,
          answerSq: props.isAnswer ? props.answerSq : null,
          description: description.value,
        })

        if (res.status == 'CREATED') {
          alertStore.show(res.message, 'success')
          props.getBoard()
        } else {
          alertStore.show('댓글 등록에 실패하였습니다.', 'danger')
        }
      } catch (error) {
        alertStore.show('댓글 등록에 실패하였습니다.', 'danger')
      }
      modalStore.closeModal()
    },
  })
}

// 신고 모달
const clickReportApplication = (sq) => {
  if (viewerSq.value == null) {
    alertStore.show('로그인 후 이용해주세요.', 'danger')
    return
  }
  modalStore.openModal(ReportModal, { reportTypeCd: 2003, sq })
}

watch(
  () => boardStore.viewerSq,
  (newVal) => {
    viewerSq.value = newVal
  },
)

// 대댓글 작성
const createReply = async (commentSq) => {
  if (viewerSq.value == null) {
    alertStore.show('로그인 후 이용해주세요.', 'danger')
    return
  }
  if (replyDescription.value.trim() === '') {
    alertStore.show('내용을 입력해주세요.', 'danger')
    return
  }
  
  try {
    const res = await api.$post('/reply', {
      commentSq: commentSq,
      boardSq: boardSq,
      description: replyDescription.value
    })
    
    if (res.status === 'CREATED') {
      alertStore.show(res.message, 'success')
      replyDescription.value = ''
      showReplyForm.value = null
      props.getBoard()
    }
  } catch (error) {
    alertStore.show('대댓글 등록에 실패하였습니다.', 'danger')
  }
}

// 대댓글 추천
const rcmndReply = async (replyCommentSq) => {
  if (viewerSq.value == null) {
    alertStore.show('로그인 후 이용해주세요.', 'danger')
    return
  }
  
  try {
    const res = await api.$post(`/reply/${replyCommentSq}/recommend`)
    if (res.status === 'OK') {
      alertStore.show(res.message, 'success')
      props.getBoard()
    }
  } catch (error) {
    alertStore.show('대댓글 추천에 실패하였습니다.', 'danger')
  }
}

// 대댓글 신고
const clickReportReply = (replyCommentSq) => {
  if (viewerSq.value == null) {
    alertStore.show('로그인 후 이용해주세요.', 'danger')
    return
  }
  modalStore.openModal(ReportModal, { reportTypeCd: 2004, sq: replyCommentSq })
}

// 대댓글 수정
const clickEditReply = (replyCommentSq, description) => {
  editReplySq.value = replyCommentSq
  editReplyDescription.value = description
}

const updateReply = async (replyCommentSq) => {
  if (editReplyDescription.value.trim() === '') {
    alertStore.show('내용을 입력해주세요.', 'danger')
    return
  }
  
  modalStore.openModal(CommonConfirmModal, {
    title: '대댓글 수정',
    message: '대댓글을 수정하시겠습니까?',
    onConfirm: async () => {
      try {
        // URLSearchParams를 사용하여 쿼리 파라미터 전달
        const params = new URLSearchParams()
        params.append('description', editReplyDescription.value)
        const res = await api.$put(`/reply/${replyCommentSq}?${params.toString()}`)
        
        if (res.status === 'OK') {
          alertStore.show(res.message, 'success')
          editReplySq.value = null
          editReplyDescription.value = ''
          props.getBoard()
        }
      } catch (error) {
        alertStore.show('대댓글 수정에 실패하였습니다.', 'danger')
      }
      modalStore.closeModal()
    }
  })
}

// 대댓글 삭제
const openDeleteReplyConfirm = (replyCommentSq) => {
  modalStore.openModal(CommonConfirmModal, {
    title: '대댓글 삭제',
    message: '정말 삭제하시겠습니까?',
    onConfirm: async () => {
      try {
        const res = await api.$patch(`/reply/${replyCommentSq}`)
        if (res.status === 'OK') {
          alertStore.show(res.message, 'success')
          props.getBoard()
        }
      } catch (error) {
        alertStore.show('대댓글 삭제에 실패하였습니다.', 'danger')
      }
      modalStore.closeModal()
    }
  })
}

// 각 댓글의 대댓글 조회
const loadReplies = async () => {
  for (const comment of props.comments) {
    try {
      // 간단하게 DB에서 직접 조회하는 방식 대신, getBoard로 한 번에 가져오기
      const replies = comment.replies || []
      commentReplies.value[comment.sq] = replies
    } catch (error) {
      console.error('대댓글 조회 실패', error)
    }
  }
}

onMounted(() => {
  viewerSq.value = boardStore.viewerSq
  loadReplies()
})

watch(
  () => props.comments,
  () => {
    loadReplies()
  },
  { deep: true }
)
</script>
<style>
button {
  background: inherit;
  border: none;
  box-shadow: none;
  border-radius: 0;
  padding: 0;
  overflow: visible;
  cursor: pointer;
}
.font-size-10 {
  font-size: 1rem;
}
.font-size-11 {
  font-size: 1.1rem;
}
.font-size-12 {
  font-size: 1.2rem;
}
.font-size-13 {
  font-size: 1.3rem;
}
.font-size-15 {
  font-size: 1.5rem;
}
.rounded-circle.comment-profile {
  width: 48px;
  height: 48px;
}
.comment-profile .fas.fa-user.text-muted {
  font-size: 20px;
}
/* 대댓글 스타일 */
.comments.replies {
  margin-left: 60px;
}
.comments.replies .comment {
  background-color: #fafafa;
}
.btn-link:hover {
  text-decoration: underline !important;
}
.fa-rotate-90 {
  transform: rotate(90deg);
}
</style>
