// frontend/nextjs/components/community/BoardTable.tsx
'use client'
import Link from 'next/link'
import { Badge } from '@/components/ui/badge'
import type { BoardItem } from '@/types'

function fmtDate(iso: string) {
  const d = new Date(iso)
  const yy = String(d.getFullYear()).slice(-2)
  const mm = String(d.getMonth() + 1).padStart(2, '0')
  const dd = String(d.getDate()).padStart(2, '0')
  return `${yy}-${mm}-${dd}`
}

type BoardType = 'board' | 'qna' | 'notice'

const STATUS: Record<number, { label: string; cls: string }> = {
  1501: { label: '진행중', cls: 'bg-yellow-100 text-yellow-800' },
  1502: { label: '채택완료', cls: 'bg-green-100 text-green-800' },
  1503: { label: '자체해결', cls: 'bg-gray-100 text-gray-700' },
  1504: { label: '미해결', cls: 'bg-red-100 text-red-700' },
}

interface Props {
  boardList: BoardItem[]
  boardType: BoardType
}

export default function BoardTable({ boardList, boardType }: Props) {
  const isQna = boardType === 'qna'

  return (
    <div className="w-full overflow-x-auto rounded-lg border">
      <table className="w-full text-sm">
        <thead>
          <tr className="border-b bg-muted/50 text-left text-muted-foreground">
            <th className="w-14 px-3 py-2.5 text-center font-medium">순번</th>
            <th className="px-3 py-2.5 font-medium">제목</th>
            <th className="w-20 px-3 py-2.5 text-center font-medium">작성자</th>
            <th className="w-24 px-3 py-2.5 text-center font-medium">등록일</th>
            <th className="w-14 px-3 py-2.5 text-center font-medium">조회</th>
            <th className="hidden w-14 px-3 py-2.5 text-center font-medium md:table-cell">댓글</th>
            <th className="hidden w-14 px-3 py-2.5 text-center font-medium md:table-cell">추천</th>
            {isQna && <th className="w-20 px-3 py-2.5 text-center font-medium">상태</th>}
          </tr>
        </thead>
        <tbody>
          {boardList.length === 0 ? (
            <tr>
              <td colSpan={isQna ? 8 : 7} className="py-12 text-center text-muted-foreground">
                게시글이 없습니다.
              </td>
            </tr>
          ) : (
            boardList.map((b) => (
              <tr key={b.sq} className="border-b transition-colors hover:bg-muted/30">
                <td className="px-3 py-2.5 text-center text-muted-foreground">{b.sq}</td>
                <td className="px-3 py-2.5">
                  <Link
                    href={`/${boardType}/${b.sq}`}
                    className="font-medium hover:text-primary hover:underline"
                  >
                    {b.ttl}
                    {isQna && b.answerCnt && b.answerCnt > 0 && (
                      <span className="ml-2 text-xs text-muted-foreground">답변 {b.answerCnt}</span>
                    )}
                  </Link>
                  {b.normalTags && b.normalTags.length > 0 && (
                    <div className="mt-1 flex flex-wrap gap-1">
                      {b.normalTags.map((t) => (
                        <Link
                          key={t}
                          href={`/${boardType}?tag=${encodeURIComponent(t)}`}
                          className="text-xs text-muted-foreground hover:text-primary"
                        >
                          #{t}
                        </Link>
                      ))}
                    </div>
                  )}
                </td>
                <td className="px-3 py-2.5 text-center">{b.userNm}</td>
                <td className="px-3 py-2.5 text-center">{fmtDate(b.createdAt)}</td>
                <td className="px-3 py-2.5 text-center">{b.viewCnt}</td>
                <td className="hidden px-3 py-2.5 text-center md:table-cell">{b.commentCnt}</td>
                <td className="hidden px-3 py-2.5 text-center md:table-cell">{b.recommendCnt}</td>
                {isQna && (
                  <td className="px-3 py-2.5 text-center">
                    {b.boardAdoptStatusCd && STATUS[b.boardAdoptStatusCd] && (
                      <span className={`rounded-full px-2 py-0.5 text-xs font-medium ${STATUS[b.boardAdoptStatusCd].cls}`}>
                        {STATUS[b.boardAdoptStatusCd].label}
                      </span>
                    )}
                  </td>
                )}
              </tr>
            ))
          )}
        </tbody>
      </table>
    </div>
  )
}

// frontend/vue_js/src/fo/components/community/BoardTable.vue
<template>
  <div class="table-responsive">
    <table class="table table-hover table-bordered align-middle text-center">
      <thead class="table-light">
        <tr>
          <th class="th-ws">순번</th>
          <th class="th-ttl">제목</th>
          <th class="th-wm">작성자</th>
          <th class="th-wl">등록일</th>
          <th class="th-ws">조회</th>
          <th class="th-ws d-none d-md-table-cell">댓글</th>
          <th class="th-ws d-none d-md-table-cell">추천</th>
          <th v-if="isQna" class="th-wl">상태</th>
        </tr>
      </thead>
      <tbody v-if="boardList.length > 0">
        <tr v-for="board in boardList" :key="board.sq">
          <td>{{ board.sq }}</td>
          <td class="text-start px-3">
            <a :href="`/${isQna ? 'qna' : 'board'}/${board.sq}`"
              >{{ board.ttl
              }}<span
                class="text-grey ml-1 px-2"
                v-show="isQna && board.answerCnt > 0"
                ><i class="fas fa-comment-dots me-1"></i>답변
                {{ board.answerCnt }}</span
              ></a
            >
            <BoardTags
              :skillTags="board.skillTags"
              :normalTags="board.normalTags"
            />
          </td>
          <td>{{ board.userNm }}</td>
          <td>{{ formatTime(board.createdAt) }}</td>
          <td>{{ board.viewCnt }}</td>
          <td class="d-none d-md-table-cell">{{ board.commentCnt }}</td>
          <td class="d-none d-md-table-cell">{{ board.recommendCnt }}</td>
          <td v-if="isQna">
            <span
              v-if="board.boardAdoptStatusCd == 1501"
              class="badge bg-warning"
              >진행중</span
            >
            <span
              v-if="board.boardAdoptStatusCd == 1502"
              class="badge bg-success"
              >채택완료</span
            >
            <span
              v-if="board.boardAdoptStatusCd == 1503"
              class="badge bg-secondary"
              >자체해결</span
            >
            <span
              v-if="board.boardAdoptStatusCd == 1504"
              class="badge bg-danger"
              >미해결</span
            >
          </td>
        </tr>
      </tbody>
      <tbody v-else>
        <tr>
          <td class="text-start px-3 text-center" :colspan="isQna ? 8 : 7">
            게시글이 없습니다.
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
<script setup>
import { computed, defineProps } from 'vue'
import BoardTags from './BoardTags.vue'

const props = defineProps({
  boardList: { type: Array, default: () => [] },
  isQna: { type: Boolean, default: false },
})

const boardList = computed(() => props.boardList)
const isQna = computed(() => props.isQna)

const formatTime = (createdAt) => {
  const date = new Date(createdAt)
  let year = date.getFullYear().toString().slice(-2)
  let month = date.getMonth() + 1
  let day = date.getDate()
  if (month < 10) month = '0' + month
  if (day < 10) day = '0' + day

  return `${year}-${month}-${day}`
}
</script>
<style>
.tag {
  font-size: 12px;
}
.th-ttl {
  min-width: 300px;
}
.th-wl {
  width: 100px;
}
.th-wm {
  width: 90px;
}
.th-ws {
  width: 70px;
}
</style>
