// frontend/react_js/components/myPage/common/ResumeSelectModal.js
import {useEffect, useMemo, useState} from "react";
import { useModalStore } from "../../../store/modalStore";
import { useAlertStore } from "../../../store/alertStore";
import { api } from "../../../api";
import CommonPagination from "../../common/CommonPagination";
import ResumeDetailModal from "./ResumeDetailModal";

export default function ResumeSelectModal( {
    userSq,
    projectSq,
    role,
    onConfirm,
    onClaose,
}) {
    const closeModal = useModalStore((s) => s.closeModal);
    const openModal = useModalStore((s) => s.openModal);

    const [resume, setResume] = useState([]);
    const [selectedResume, setSlectedResume] = useState([]);

    const close = () => {
        //모달 닫기(부모에서 onCLose 주입됨)
        onClose?.();
        closeModal();
    };

    const formatTime = (createAt) => {
        const date = new Date(createdAt);
        const y = date.getFullYear();
        const m = String(date.getMonth() + 1).padStart(2, '0');
        const d = String(date.getDate()).padStart(2, '0');
        return `${y}.${m}.${d}`;
    };

    //목록 조회
    const getResumes = async () => {
        try{
            if(role === 'PERSONAL'){
                const res = await api.get("/mypage/resume/select-list");
                const list = Array.isArray(res.data.output) ? res.data.output : [];
                setResume(list);
            } else if(role === 'COMPANY'){
                const res = await api.get('/mypage/resume/list/${userSq}');
                const list = Array.isArray(res.date?.output) ? res.date?.output : [];
                setResume(list);
            }
        }catch(e){
            console.error('이력서 목록 조회 실패:', e);
        }
    };
    // 대표 뱃지 토글 + 선택 상태 업데이트 (단일 선택))
    const selectResume = (resume) => {
        //기존 대표 이력서 뱃지 제거
        const next = (resumes || []).map((r) => ({
            ...r,
            resumeIsReporesentativeYn: 'N',
        }));
        //선택된 이력서에 대표 뱃지 부여
        const idx = next.findIndex((r) => r.resumeSq === resume.resumeSq);
        if(idx >= 0) next[idx].resumeIsRepresentativeYn = 'Y';
        setResumes(next);
    };
    //상세 모달 열기
    const openResumeDetailModal = (resume) => {
        openModal(ResumeDetailModal, {
            title: "이력서 상세보기",
            size: "modal-lg",
            resumeSq: resume.resumeSq,
            onConfirm: () => selectResume(resume),
        });
    };

    const confirm = async () => {
        if (selectedResume.length === 0) {
            showAlert("이력서를 선택해주세요.", "danger");
            resume;
    }

    try{
        if(role === 'PERSONAL'){
            await api.post(`/projects/applications/${projectSq}`, {
                resumeSq: selectedResume.map((r) => r.resumeSq),
                projectApplicationTyp: role,
            });
            showAlert("프로젝트 지원에 성공하였습니다.");
            onConfirm?.();
            close();
        } else if( role === 'COMPANY'){
            await api.patch(`/mypage/resume/representative/${selectedResume[0].resumeSq}`, 
                {memberSq: userSq},
                {withCredentials: true});
            showAlert("대표 이력서 설정에 성공하였습니다.");
            onConfirm?.();
            close();
        }
    } catch(e){
        console.error("프로젝트 지원 실패:", e);
        showAlert("프로젝트 지원에 실패했습니다.", "danger");
    }
};

    //마운트/role/userSq 변경 시 목록 갱신
    useEffect(() => {
        getResumes();
    }, [role, userSq]);

      // 현재 선택된 resumeSq를 빠르게 판별하기 위한 Set
  const selectedSqSet = useMemo(
    () => new Set(selectedResume.map((r) => r.resumeSq)),
    [selectedResume]
  );

  return (
    <div className="modal-content">
      <div className="modal-header">
        <h4 className="modal-title">이력서 선택</h4>
        <button type="button" className="btn-close" aria-hidden="true" onClick={close} />
      </div>

      <div className="modal-body">
        <ul className="simple-post-list m-0">
          {resumes.map((resume) => (
            <li
              key={resume.resumeSq}
              className="d-flex align-items-center gap-2"
            >
              <div className="post-info align-items-center gap-2">
                <a
                  href="#"
                  onClick={(e) => {
                    e.preventDefault();
                    openResumeDetailModal(resume);
                  }}
                >
                  {resume.resumeTtl}
                </a>

                {resume.resumeIsRepresentativeYn === "Y" && (
                  <span
                    className="badge bg-primary ms-2 align-middle"
                    style={{ fontSize: "12px", padding: "3px 6px" }}
                  >
                    대표 이력서
                  </span>
                )}

                <div className="post-meta">
                  <span className="text-dark text-uppercase font-weight-semibold">
                    등록일자
                  </span>{" "}
                  | {formatTime(resume.resumeCreatedAtDtm)}
                </div>
              </div>

              <div className="ms-auto">
                {selectedSqSet.has(resume.resumeSq) ? (
                  <button className="btn btn-primary btn-sm" disabled>
                    선택됨
                  </button>
                ) : (
                  <button
                    className="btn btn-outline-primary btn-sm"
                    onClick={() => selectResume(resume)}
                  >
                    선택하기
                  </button>
                )}
              </div>
            </li>
          ))}
        </ul>

        <CommonPagination
          currentPage={currentPage}
          totalPages={totalPages}
          onPageChange={(p) => setCurrentPage(p)}
        />
      </div>

      <div className="modal-footer">
        <button onClick={confirm} className="btn btn-primary">
          선택 완료
        </button>
        <button onClick={close} className="btn btn-light">
          닫기
        </button>
      </div>
    </div>
  );
}

// frontend/vue_js/src/fo/components/mypage/common/ResumeSelectModal.vue
<template>
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title">이력서 선택</h4>
      <button
        type="button"
        class="btn-close"
        @click="close"
        aria-hidden="true"
      ></button>
    </div>

    <div class="modal-body">
      <ul class="simple-post-list m-0">
        <li
          class="d-flex align-items-center gap-2"
          v-for="resume in resumes"
          :key="resume.resumeSq"
        >
          <div class="post-info align-items-center gap-2">
            <a href="#" @click="openResumeDetailModal(resume)">
              {{ resume.resumeTtl }}
            </a>
            <span
              v-if="resume.resumeIsRepresentativeYn === 'Y'"
              class="badge bg-primary ms-2 align-middle"
              style="font-size: 12px; padding: 3px 6px"
            >
              대표 이력서
            </span>
            <div class="post-meta">
              <span class="text-dark text-uppercase font-weight-semibold"
                >등록일자</span
              >
              | {{ formatTime(resume.resumeCreatedAtDtm) }}
            </div>
          </div>

          <div class="ms-auto">
            <button
              v-if="selectedResume.some((r) => r.resumeSq === resume.resumeSq)"
              class="btn btn-primary btn-sm"
              disabled
            >
              선택됨
            </button>
            <button
              v-else
              class="btn btn-outline-primary btn-sm"
              @click="selectResume(resume)"
            >
              선택하기
            </button>
          </div>
        </li>
      </ul>

      <CommonPagination
        :currentPage="currentPage"
        :totalPages="totalPages"
        @update:currentPage="currentPage = $event"
      />
    </div>

    <div class="modal-footer">
      <button @click="confirm" class="btn btn-primary">선택 완료</button>
      <button @click="close" class="btn btn-light">닫기</button>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted, defineProps, reactive } from 'vue'
import { useModalStore } from '../../../stores/modalStore'
import { useAlertStore } from '../../../stores/alertStore'
import { api } from '@/axios.js'

import CommonPagination from '@/fo/components/common/CommonPagination.vue'

import ResumeDetailModal from '@/fo/components/project/ProjectResumeDetailModal.vue'

const props = defineProps({
  userSq: {
    type: Number,
    required: false, // 소속 인원 리스트에서 호출할 때만 전달.
  },
  projectSq: {
    type: Number,
    required: false, // 개인 지원 할 때만 필요.
  },
  role: {
    type: String,
    required: true,
  },
  onConfirm: {
    type: Function,
    required: false,
  },
})

const modalStore = useModalStore()
const alertStore = useAlertStore()

const currentPage = ref(1)
const totalPages = ref(1)
const resumes = ref([])
const selectedResume = reactive([])

const close = () => {
  modalStore.closeModal()
}

const getResumes = async () => {
  if (props.role === 'PERSONAL') {
    try {
      const res = await api.$get('/mypage/resume/select-list')
      console.log('이력서 목록 응답:', res)
      if (Array.isArray(res.output)) {
        console.log(res.output)
        resumes.value = res.output
      } else {
        console.error('이력서 목록이 배열이 아닙니다:', res)
      }
    } catch (error) {
      console.error('이력서 목록 조회 실패:', error)
    }
  } else if (props.role === 'COMPANY') {
    try {
      const res = await api.$get(`/mypage/resume/list/${props.userSq}`)
      if (Array.isArray(res.output)) {
        resumes.value = res.output
      } else {
        console.error('이력서 목록이 배열이 아닙니다:', res)
      }
    } catch (error) {
      console.error('이력서 목록 조회 실패:', error)
    }
  }
}

const selectResume = (resume) => {
  // 1. 기존 대표 이력서 뱃지 제거
  resumes.value = resumes.value.map((r) => ({
    ...r,
    resumeIsRepresentativeYn: 'N',
  }))

  // 2. 선택된 이력서에 대표 뱃지 부여
  const selected = resumes.value.find((r) => r.resumeSq === resume.resumeSq)
  if (selected) {
    selected.resumeIsRepresentativeYn = 'Y'
  }

  // 3. selectedResume 업데이트 (배열이므로 비우고 다시 push)
  selectedResume.splice(0, selectedResume.length, resume)
}

const openResumeDetailModal = (resume) => {
  modalStore.openModal(ResumeDetailModal, {
    title: '이력서 상세보기',
    size: 'modal-lg',
    resumeSq: resume.resumeSq,
    onConfirm: () => selectResume(resume),
  })
}

const formatTime = (createdAt) => {
  const date = new Date(createdAt)
  const year = date.getFullYear()
  const month = String(date.getMonth() + 1).padStart(2, '0')
  const day = String(date.getDate()).padStart(2, '0')
  return `${year}.${month}.${day}`
}

const confirm = async () => {
  if (selectedResume.length === 0) {
    alertStore.show('이력서를 선택해주세요.', 'danger')
    return
  }

  if (props.role === 'PERSONAL') {
    try {
      await api.$post(`/projects/applications/${props.projectSq}`, {
        resumeSq: selectedResume.map((r) => r.resumeSq),
        projectApplicationTyp: props.role,
      })

      alertStore.show('프로젝트 지원에 성공하였습니다.')

      // ✅ 콜백 실행
      if (props.onConfirm) {
        props.onConfirm()
      }

      modalStore.closeModal()
    } catch (error) {
      console.error(error)
      alertStore.show('프로젝트 지원에 실패했습니다.', 'danger')
    }
  } else if (props.role === 'COMPANY') {
    try {
      await api.$patch(
        `/mypage/resume/representative/${selectedResume[0].resumeSq}`,
        {
          memberSq: props.userSq,
        },
        {
          withCredentials: true,
        },
      )

      // ✅ 콜백 실행
      if (props.onConfirm) {
        props.onConfirm()
      }

      modalStore.closeModal()
    } catch (error) {
      console.error(error)
      alertStore.show('프로젝트 지원에 실패했습니다.', 'danger')
    }
  }
}

onMounted(() => {
  getResumes()
})
</script>
