// frontend/vue_js/src/fo/components/mypage/common/ResumeDetailModal.vue
<template>
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title">{{ resumeInfo.title }}</h4>
      <button
        type="button"
        class="btn-close"
        @click="closeModal"
        aria-hidden="true"
      >
        ×
      </button>
    </div>
    <div class="modal-body">
      <div
        class="tab-pane tab-pane-navigation active show"
        id="resumeDetail"
        role="tabpanel"
      >
        <div class="card bg-color-grey mb-4 p-4">
          <div class="row align-items-start">
            <!-- 이력서 제목 -->
            <div class="mb-4">
              <h5 class="mb-1 text-primary" style="font-weight: bold">
                이력서 제목
              </h5>
              <p class="mb-0 text-dark">{{ resumeInfo.resumeTtl }}</p>
            </div>

            <!-- 사진 -->
            <div class="col-lg-3 mb-4 d-flex justify-content-center">
              <div
                class="photo-box bg-white"
                style="
                  width: 100%;
                  max-width: 200px;
                  height: 200px;
                  border: 1px solid #ddd;
                  display: flex;
                  align-items: center;
                  justify-content: center;
                "
              >
                <img
                  :src="resumeInfo.resumePhotoUrl || null"
                  alt="사진"
                  class="img-fluid rounded"
                  style="max-height: 100%; object-fit: cover"
                />
              </div>
            </div>

            <!-- 기본 정보 -->
            <div class="col-lg-9">
              <p>
                <strong class="text-primary">이름 :</strong>
                <span class="text-dark"> {{ resumeInfo.resumeNm }}</span>
              </p>
              <p>
                <strong class="text-primary">생년월일 :</strong>
                <span class="text-dark"> {{ resumeInfo.resumeBirthDt }}</span>
              </p>
              <p>
                <strong class="text-primary">전화번호 :</strong>
                <span class="text-dark"> {{ resumeInfo.resumePhoneNum }}</span>
              </p>
              <p>
                <strong class="text-primary">이메일 :</strong>
                <span class="text-dark"> {{ resumeInfo.resumeEmail }}</span>
              </p>
              <p>
                <strong class="text-primary">주소 :</strong>
                <span class="text-dark">
                  {{ resumeInfo.address.addressFull }}</span
                >
              </p>
            </div>
          </div>

          <hr />

          <!-- 학력 -->
          <h5 class="text-primary">학력</h5>
          <ul class="list-unstyled">
            <li
              v-for="(education, index) in resumeInfo.educationList"
              :key="index"
            >
              {{ education.educationSchoolNm }}
              {{ education.educationMajorNm }}
              {{ education.educationStatusNm }} ({{
                education.educationAdmissionDt
              }}
              ~ {{ education.educationGraduationDt }})
            </li>
          </ul>

          <!-- 경력 -->
          <h5 class="text-primary">회사 이력</h5>
          <ul class="list-unstyled">
            <li v-for="(career, index) in resumeInfo.careerList" :key="index">
              {{ career.careerCompanyNm }} {{ career.careerDepartmentNm }} -
              {{ career.careerPositionNm }} ({{ career.careerStartDt }} ~
              {{ career.careerEndDt }})
            </li>
          </ul>

          <!-- 교육 이력 -->
          <h5 class="text-primary">교육 이력</h5>
          <ul class="list-unstyled">
            <li
              v-for="(training, index) in resumeInfo.trainingList"
              :key="index"
            >
              {{ training.trainingInstitutionNm }} -
              {{ training.trainingProgramNm }} ({{ training.trainingStartDt }} ~
              {{ training.trainingEndDt }})
            </li>
          </ul>

          <!-- 프로젝트 이력 -->
          <h5
            class="text-primary d-flex justify-content-between align-items-center mb-3"
          >
            프로젝트 이력
            <div class="d-flex gap-3">
              <a
                href="#"
                @click.prevent="toggleAllProjects"
                class="text-grey text-decoration-none small"
              >
                <i
                  :class="[
                    'fas',
                    allProjectsExpanded ? 'fa-chevron-up' : 'fa-chevron-down',
                    'me-2',
                  ]"
                ></i>
                {{ allProjectsExpanded ? '전체 닫기' : '전체 펼치기' }}
              </a>
            </div>
          </h5>

          <ul class="list-unstyled">
            <li
              v-for="(project, index) in resumeInfo.projectList"
              :key="index"
              class="d-flex flex-wrap align-items-center gap-2"
            >
              <div
                class="btn btn-rounded btn-3d btn-light mb-2 w-100 d-flex align-items-center justify-content-between position-relative px-3 py-2"
                style="text-align: left"
              >
                <div
                  class="d-flex align-items-center flex-grow-1"
                  @click="toggleProject(index)"
                >
                  <i
                    :class="[
                      'fas',
                      'fa-chevron-right',
                      'me-2',
                      'transition-transform',
                      { 'rotate-90': project.isExpanded },
                    ]"
                  ></i>
                  <span
                    >{{ project.projectHistoryClient }}
                    {{ project.projectHistoryTask }} ({{
                      project.projectHistoryStartDt
                    }}
                    ~ {{ project.projectHistoryEndDt }})</span
                  >
                </div>
              </div>

              <div v-show="project.isExpanded" class="collapse show mb-3 w-100">
                <div class="bg-light rounded p-3 border">
                  <div class="row mb-2">
                    <div class="col-sm-4">
                      <strong>고객사:</strong>
                      {{ project.projectHistoryClient }}
                    </div>
                    <div class="col-sm-4">
                      <strong>업무단:</strong>
                      {{ project.projectHistoryJobPositionTypeNm }}
                    </div>
                    <div class="col-sm-4">
                      <strong>역할:</strong> {{ project.projectHistoryTypeNm }}
                    </div>
                  </div>
                  <div class="row mb-2">
                    <div class="col-sm-4">
                      <strong style="margin-right: 8px">기종:</strong>
                      <button
                        v-for="device in getTagsByCategory(project, 'Device')"
                        :key="device"
                        class="btn btn-rounded btn-3d btn-light btn-sm me-2"
                      >
                        <img
                          v-if="generateIconUrl(device)"
                          :src="generateIconUrl(device)"
                          width="16"
                          height="16"
                        />
                        {{ device }}
                      </button>
                    </div>
                    <div class="col-sm-8">
                      <strong style="margin-right: 8px">OS:</strong>
                      <button
                        v-for="os in getTagsByCategory(project, 'OS')"
                        :key="os"
                        class="btn btn-rounded btn-3d btn-light btn-sm me-2"
                      >
                        <img
                          v-if="generateIconUrl(os)"
                          :src="generateIconUrl(os)"
                          width="16"
                          height="16"
                        />
                        {{ os }}
                      </button>
                    </div>
                  </div>
                  <div class="row mb-2">
                    <div class="col-sm-12">
                      <strong style="margin-right: 8px">DBMS:</strong>
                      <button
                        v-for="dbms in getTagsByCategory(project, 'DBMS')"
                        :key="dbms"
                        class="btn btn-rounded btn-3d btn-light btn-sm me-2"
                      >
                        <img
                          v-if="generateIconUrl(dbms)"
                          :src="generateIconUrl(dbms)"
                          width="16"
                          height="16"
                        />
                        {{ dbms }}
                      </button>
                    </div>
                  </div>
                  <div class="row mb-2">
                    <div class="col-sm-12">
                      <strong style="margin-right: 8px">언어:</strong>
                      <button
                        v-for="lang in getTagsByCategory(project, 'Language')"
                        :key="lang"
                        class="btn btn-rounded btn-3d btn-light btn-sm me-2"
                      >
                        <img
                          v-if="generateIconUrl(lang)"
                          :src="generateIconUrl(lang)"
                          width="16"
                          height="16"
                        />
                        {{ lang }}
                      </button>
                    </div>
                  </div>
                  <div class="row mb-2">
                    <div class="col-sm-12">
                      <strong style="margin-right: 8px">TOOL:</strong>
                      <button
                        v-for="tool in getTagsByCategory(project, 'Tool')"
                        :key="tool"
                        class="btn btn-rounded btn-3d btn-light btn-sm me-2"
                      >
                        <img
                          v-if="generateIconUrl(tool)"
                          :src="generateIconUrl(tool)"
                          width="16"
                          height="16"
                        />
                        {{ tool }}
                      </button>
                    </div>
                  </div>
                  <div class="row mb-2">
                    <div class="col-sm-12">
                      <strong style="margin-right: 8px">FW:</strong>
                      <button
                        v-for="framework in getTagsByCategory(
                          project,
                          'FrameWork',
                        )"
                        :key="framework"
                        class="btn btn-rounded btn-3d btn-light btn-sm me-2"
                      >
                        <img
                          v-if="generateIconUrl(framework)"
                          :src="generateIconUrl(framework)"
                          width="16"
                          height="16"
                        />
                        {{ framework }}
                      </button>
                    </div>
                  </div>
                  <!-- <div class="row mb-3">
                    <div class="col-sm-12">
                      <strong style="margin-right: 8px">기타:</strong>
                    </div>
                  </div> -->
                </div>
              </div>
            </li>
          </ul>

          <!-- 자격증 -->
          <h5 class="text-primary">자격증</h5>
          <ul class="list-unstyled">
            <li
              v-for="(certificate, index) in resumeInfo.certificationList"
              :key="index"
            >
              {{ certificate.certificationNm }}
            </li>
          </ul>

          <!-- 기술 -->
          <h5 class="text-primary">보유 기술</h5>
          <div class="d-flex gap-2 flex-wrap mb-3">
            <div
              v-for="(skill, index) in resumeInfo.skillTagList"
              :key="index"
              class="btn d-flex align-items-center gap-2 border-0"
            >
              <img
                v-if="generateIconUrl(skill)"
                :src="generateIconUrl(skill)"
                width="20"
              />
              {{ skill }}
            </div>
          </div>

          <!-- 자기소개 -->
          <h5 class="text-primary">자기소개</h5>
          <p class="border p-3 bg-white rounded text-dark">
            {{ resumeInfo.resumeGreetingTxt }}
          </p>

          <!-- 첨부파일 -->
          <h5 class="text-primary">첨부 파일</h5>
          <p v-for="(file, index) in resumeInfo.attachmentList" :key="index">
            <a :href="file.attachmentFileUrl" target="_blank">{{
              file.attachmentOriginFileNm
            }}</a>
          </p>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <!-- <button class="btn btn-primary" @click="handleSelect">선택하기</button> -->
      <button class="btn btn-outline-secondary" @click="closeModal">
        닫기
      </button>
    </div>
  </div>
</template>

<script setup>
import { ref, watchEffect, defineProps, computed } from 'vue'
import { useModalStore } from '@/fo/stores/modalStore'
import { api } from '@/axios'
import skillIconMap from '@/assets/skillIconMap.js'

const props = defineProps({
  resumeSq: {
    type: Number,
    required: true,
  },
  projectSq: {
    type: Number,
    required: true,
  },
  applicationSq: {
    type: Number,
    required: true,
  },
  isFromApplicationList: {
    type: Boolean,
    default: false,
  },
})

const modalStore = useModalStore()

const resumeInfo = ref({
  resumeTtl: '',
  resumePhotoUrl: '',
  resumeNm: '',
  resumeBirthDt: '',
  resumePhoneNum: '',
  resumeEmail: '',
  address: '',
  photo: '',
  educationList: [],
  careerList: [],
  trainingList: [],
  projectList: [],
  certificationList: [],
  skillTagList: [],
  resumeGreetingTxt: '',
  attachmentList: [],
})

function getTagsByCategory(project, category) {
  const found = project.groupedSkillTags.find((item) => item[category])
  return found ? found[category] : []
}

const toggleProject = (index) => {
  resumeInfo.value.projectList[index].isExpanded =
    !resumeInfo.value.projectList[index].isExpanded
}

const allProjectsExpanded = computed(
  () =>
    resumeInfo.value.projectList.length > 0 &&
    resumeInfo.value.projectList.every((project) => project.isExpanded),
)

const toggleAllProjects = () => {
  const nextExpanded = !allProjectsExpanded.value

  resumeInfo.value.projectList.forEach((project) => {
    project.isExpanded = nextExpanded
  })
}

const closeModal = () => {
  modalStore.closeModal()
}

// const handleSelect = () => {
//   console.log('이력서 선택')
//   closeModal()
// }

// 이력서 상세조회
watchEffect(async () => {
  if (!props.resumeSq) return

  try {
    const res = props.isFromApplicationList
      ? await api.$post('/mypage/resume-detail-view', {
          resumeSq: props.resumeSq,
          projectSq: props.projectSq,
          applicationSq: props.applicationSq,
        }) // 열람 처리 포함 API
      : await api.$get(`/mypage/resume-detail/${props.resumeSq}`) // 단순 조회 API

    res.output.projectList = res.output.projectList.map((project) => ({
      ...project,
      isExpanded: true,
    }))
    resumeInfo.value = res.output
  } catch (err) {
    console.error('이력서 조회 실패:', err)
  }
})

const generateIconUrl = (name) => {
  if (!name) return null
  const key = name.toLowerCase().replace(/[\s.]+/g, '')
  return skillIconMap[key] || skillIconMap.default
}
</script>

<style scoped>
.modal-content {
  border-radius: 8px;
}

.btn-rounded {
  border-radius: 20px;
}

.btn-3d {
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.gap-2 {
  gap: 0.5rem;
}

.rotate-90 {
  transform: rotate(90deg);
}

.transition-transform {
  transition: transform 0.3s ease;
}

.bg-color-grey {
  background-color: #f5f5f5;
}
</style>

// frontend/nextjs/components/mypage/personal/ResumeDetailModal.tsx
'use client'
import { useState, useEffect, useCallback, useRef } from 'react'
import { toast } from 'sonner'
import { ChevronRight, ChevronDown } from 'lucide-react'
import { getSkillIconUrl } from '@/lib/skillIconMap'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import api from '@/lib/api'

interface GroupedTag { [category: string]: string[] }
interface ProjectDetail {
  projectHistoryClient?: string
  projectHistoryTask?: string
  projectHistoryStartDt?: string
  projectHistoryEndDt?: string
  projectHistoryJobPositionTypeNm?: string
  projectHistoryTypeNm?: string
  groupedSkillTags?: GroupedTag[]
  isExpanded?: boolean
}
interface ResumeInfo {
  resumeTtl?: string
  resumePhotoUrl?: string
  resumeNm?: string
  resumeBirthDt?: string
  resumePhoneNum?: string
  resumeEmail?: string
  address?: { addressSq?: number; addressFull?: string; address?: string; detailAddress?: string } | string
  educationList?: Array<{ educationSchoolNm?: string; educationMajorNm?: string; educationStatusNm?: string; educationAdmissionDt?: string; educationGraduationDt?: string }>
  careerList?: Array<{ careerCompanyNm?: string; careerDepartmentNm?: string; careerPositionNm?: string; careerStartDt?: string; careerEndDt?: string }>
  trainingList?: Array<{ trainingProgramNm?: string; trainingInstitutionNm?: string; trainingStartDt?: string; trainingEndDt?: string }>
  projectList?: ProjectDetail[]
  certificationList?: Array<{ certificationNm?: string; certificationIssuerNm?: string }>
  skillTagList?: string[]
  resumeGreetingTxt?: string
  attachmentList?: Array<{ attachmentFileUrl?: string; attachmentOriginFileNm?: string }>
}

const CATS: Array<{ key: string; label: string }> = [
  { key: 'Device', label: '기종' }, { key: 'OS', label: 'OS' }, { key: 'DBMS', label: 'DBMS' },
  { key: 'Language', label: '언어' }, { key: 'Tool', label: 'TOOL' }, { key: 'FrameWork', label: 'FW' },
]

interface Props {
  resumeSq: number | null
  // 지원 목록에서 열 때: projectSq·applicationSq를 주면 열람 처리 포함 POST API 사용
  projectSq?: number | null
  applicationSq?: number | null
  onClose: () => void
}

export default function ResumeDetailModal({ resumeSq, projectSq, applicationSq, onClose }: Props) {
  const [info, setInfo] = useState<ResumeInfo | null>(null)
  const [expanded, setExpanded] = useState<Set<number>>(new Set())

  // onClose는 부모에서 인라인 화살표로 넘어와 매 렌더 새 참조 → load 의존성에 넣으면 재조회 루프.
  // ref로 최신값만 참조해 에러 시 모달을 닫는다.
  const onCloseRef = useRef(onClose)
  onCloseRef.current = onClose

  const load = useCallback(async () => {
    if (resumeSq == null) return
    setInfo(null)
    try {
      const { data } = projectSq != null && applicationSq != null
        ? await api.post('/mypage/resume-detail-view', { resumeSq, projectSq, applicationSq })
        : await api.get(`/mypage/resume-detail/${resumeSq}`)
      const out: ResumeInfo = data.output ?? {}
      setInfo(out)
      setExpanded(new Set((out.projectList ?? []).map((_, i) => i))) // 기본 전체 펼침
    } catch (e) {
      // 삭제된 이력서 등: 백엔드가 "유효하지 않은 이력서입니다." 400 → 에러 토스트 + 모달 닫기
      const msg = (e as { response?: { data?: { message?: string } } }).response?.data?.message
      toast.error(msg || '이력서를 불러올 수 없습니다.')
      onCloseRef.current()
    }
  }, [resumeSq, projectSq, applicationSq])

  useEffect(() => { if (resumeSq != null) load() }, [resumeSq, load])

  const toggle = (i: number) => setExpanded((p) => { const n = new Set(p); n.has(i) ? n.delete(i) : n.add(i); return n })
  const tagsOf = (p: ProjectDetail, cat: string) => p.groupedSkillTags?.find((g) => g[cat])?.[cat] ?? []

  return (
    <Dialog open={resumeSq != null} onOpenChange={(o) => { if (!o) onClose() }}>
      <DialogContent className="flex max-h-[90vh] w-[95vw] flex-col gap-0 overflow-hidden p-0 sm:max-w-2xl">
        <DialogHeader className="shrink-0 border-b px-6 py-4"><DialogTitle>이력서 상세보기</DialogTitle></DialogHeader>
        <div className="overflow-y-auto px-6 py-4">
        {!info ? (
          <p className="py-10 text-center text-sm text-muted-foreground">불러오는 중...</p>
        ) : (
          <div className="space-y-5 text-sm">
            {/* 제목 + 사진 + 기본정보 */}
            <div className="flex items-start gap-4">
              <img src={info.resumePhotoUrl || '/img/logos/Company_logo.png'} alt="" className="h-24 w-24 shrink-0 rounded-md border bg-muted object-cover" />
              <div className="min-w-0 space-y-1">
                <p className="text-base font-semibold">{info.resumeTtl}</p>
                <p>{info.resumeNm} · {info.resumeBirthDt}</p>
                <p>{info.resumePhoneNum}</p>
                <p className="break-all">{info.resumeEmail}</p>
                <p className="text-muted-foreground">{addressText(info.address)}</p>
              </div>
            </div>

            <Sec title="학력" show={!!info.educationList?.length}>
              <ul className="space-y-1">
                {info.educationList?.map((e, i) => (
                  <li key={i}>{e.educationSchoolNm} {e.educationMajorNm} {e.educationStatusNm} ({e.educationAdmissionDt} ~ {e.educationGraduationDt})</li>
                ))}
              </ul>
            </Sec>

            <Sec title="회사 이력" show={!!info.careerList?.length}>
              <ul className="space-y-1">
                {info.careerList?.map((c, i) => (
                  <li key={i}>{c.careerCompanyNm} {c.careerDepartmentNm} - {c.careerPositionNm} ({c.careerStartDt} ~ {c.careerEndDt})</li>
                ))}
              </ul>
            </Sec>

            <Sec title="교육 이력" show={!!info.trainingList?.length}>
              <ul className="space-y-1">
                {info.trainingList?.map((t, i) => (
                  <li key={i}>{t.trainingProgramNm} / {t.trainingInstitutionNm} ({t.trainingStartDt} ~ {t.trainingEndDt})</li>
                ))}
              </ul>
            </Sec>

            <Sec title="프로젝트 이력" show={!!info.projectList?.length}>
              <div className="space-y-2">
                {info.projectList?.map((p, i) => (
                  <div key={i} className="rounded-md border">
                    <button type="button" onClick={() => toggle(i)} className="flex w-full items-center gap-2 px-3 py-2 text-left cursor-pointer">
                      {expanded.has(i) ? <ChevronDown className="h-4 w-4" /> : <ChevronRight className="h-4 w-4" />}
                      <span className="font-medium">{p.projectHistoryClient} {p.projectHistoryTask}</span>
                      <span className="text-muted-foreground">({p.projectHistoryStartDt} ~ {p.projectHistoryEndDt})</span>
                    </button>
                    {expanded.has(i) && (
                      <div className="space-y-2 border-t bg-muted/30 p-3">
                        <div className="grid grid-cols-1 gap-1 sm:grid-cols-3">
                          <div><strong>고객사:</strong> {p.projectHistoryClient}</div>
                          <div><strong>업무단:</strong> {p.projectHistoryJobPositionTypeNm}</div>
                          <div><strong>역할:</strong> {p.projectHistoryTypeNm}</div>
                        </div>
                        {CATS.map(({ key, label }) => {
                          const tags = tagsOf(p, key)
                          if (!tags.length) return null
                          return (
                            <div key={key} className="flex flex-wrap items-center gap-1">
                              <strong className="mr-1">{label}:</strong>
                              {tags.map((t) => (
                                <span key={t} className="inline-flex items-center gap-1 rounded-full border bg-background px-2 py-0.5 text-xs">
                                  <img src={getSkillIconUrl(t)} alt="" className="h-3.5 w-3.5" />{t}
                                </span>
                              ))}
                            </div>
                          )
                        })}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </Sec>

            <Sec title="자격증" show={!!info.certificationList?.length}>
              <ul className="space-y-1">
                {info.certificationList?.map((c, i) => (
                  <li key={i}>{c.certificationNm}{c.certificationIssuerNm ? ` (${c.certificationIssuerNm})` : ''}</li>
                ))}
              </ul>
            </Sec>

            <Sec title="보유 기술" show={!!info.skillTagList?.length}>
              <div className="flex flex-wrap gap-1.5">
                {info.skillTagList?.map((s, i) => (
                  <span key={i} className="inline-flex items-center gap-1 rounded-full border bg-background px-2 py-0.5 text-xs">
                    <img src={getSkillIconUrl(s)} alt="" className="h-3.5 w-3.5" />{s}
                  </span>
                ))}
              </div>
            </Sec>

            <Sec title="자기소개" show={!!info.resumeGreetingTxt}>
              <p className="whitespace-pre-wrap">{info.resumeGreetingTxt}</p>
            </Sec>

            <Sec title="첨부파일" show={!!info.attachmentList?.length}>
              <ul className="space-y-0.5">
                {info.attachmentList?.map((f, i) => (
                  <li key={i}><a href={f.attachmentFileUrl} target="_blank" rel="noreferrer" className="text-primary underline hover:no-underline">{f.attachmentOriginFileNm}</a></li>
                ))}
              </ul>
            </Sec>
          </div>
        )}
        </div>
      </DialogContent>
    </Dialog>
  )
}

function addressText(addr: ResumeInfo['address']): string {
  if (!addr) return ''
  if (typeof addr === 'string') return addr
  return [addr.addressFull ?? addr.address, addr.detailAddress].filter(Boolean).join(' ')
}

function Sec({ title, show, children }: { title: string; show: boolean; children: React.ReactNode }) {
  if (!show) return null
  return (
    <div className="space-y-1">
      <h4 className="font-semibold text-foreground">{title}</h4>
      {children}
    </div>
  )
}
