// frontend/vue_js/src/fo/components/community/BoardTable.vue
<template>
  <div class="table-responsive">
    <table class="table table-hover table-bordered align-middle text-center">
      <thead class="table-light">
        <tr>
          <th class="th-ws">순번</th>
          <th class="th-ttl">제목</th>
          <th class="th-wm">작성자</th>
          <th class="th-wl">등록일</th>
          <th class="th-ws">조회</th>
          <th class="th-ws d-none d-md-table-cell">댓글</th>
          <th class="th-ws d-none d-md-table-cell">추천</th>
          <th v-if="isQna" class="th-wl">상태</th>
        </tr>
      </thead>
      <tbody v-if="boardList.length > 0">
        <tr v-for="board in boardList" :key="board.sq">
          <td>{{ board.sq }}</td>
          <td class="text-start px-3">
            <a :href="`/${isQna ? 'qna' : 'board'}/${board.sq}`"
              >{{ board.ttl
              }}<span
                class="text-grey ml-1 px-2"
                v-show="isQna && board.answerCnt > 0"
                ><i class="fas fa-comment-dots me-1"></i>답변
                {{ board.answerCnt }}</span
              ></a
            >
            <BoardTags
              :skillTags="board.skillTags"
              :normalTags="board.normalTags"
            />
          </td>
          <td>{{ board.userNm }}</td>
          <td>{{ formatTime(board.createdAt) }}</td>
          <td>{{ board.viewCnt }}</td>
          <td class="d-none d-md-table-cell">{{ board.commentCnt }}</td>
          <td class="d-none d-md-table-cell">{{ board.recommendCnt }}</td>
          <td v-if="isQna">
            <span
              v-if="board.boardAdoptStatusCd == 1501"
              class="badge bg-warning"
              >진행중</span
            >
            <span
              v-if="board.boardAdoptStatusCd == 1502"
              class="badge bg-success"
              >채택완료</span
            >
            <span
              v-if="board.boardAdoptStatusCd == 1503"
              class="badge bg-secondary"
              >자체해결</span
            >
            <span
              v-if="board.boardAdoptStatusCd == 1504"
              class="badge bg-danger"
              >미해결</span
            >
          </td>
        </tr>
      </tbody>
      <tbody v-else>
        <tr>
          <td class="text-start px-3 text-center" :colspan="isQna ? 8 : 7">
            게시글이 없습니다.
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
<script setup>
import { computed, defineProps } from 'vue'
import BoardTags from './BoardTags.vue'

const props = defineProps({
  boardList: { type: Array, default: () => [] },
  isQna: { type: Boolean, default: false },
})

const boardList = computed(() => props.boardList)
const isQna = computed(() => props.isQna)

const formatTime = (createdAt) => {
  const date = new Date(createdAt)
  let year = date.getFullYear().toString().slice(-2)
  let month = date.getMonth() + 1
  let day = date.getDate()
  if (month < 10) month = '0' + month
  if (day < 10) day = '0' + day

  return `${year}-${month}-${day}`
}
</script>
<style>
.tag {
  font-size: 12px;
}
.th-ttl {
  min-width: 300px;
}
.th-wl {
  width: 100px;
}
.th-wm {
  width: 90px;
}
.th-ws {
  width: 70px;
}
</style>

// frontend/react_js/components/community/BoardTable.js
import { useRouter } from 'next/router'
import BoardTags from './BoardTags'
import styles from './BoardTable.module.css'

export default function BoardTable({ boardList, isQna }) {
  const router = useRouter()
  
  const formatTime = (createdAt) => {
    const date = new Date(createdAt)
    const year = date.getFullYear().toString().slice(-2)
    let month = date.getMonth() + 1
    let day = date.getDate()
    if (month < 10) month = '0' + month
    if (day < 10) day = '0' + day
    
    return `${year}-${month}-${day}`
  }
  
  const handleRowClick = (boardSq) => {
    const path = isQna ? `/qna/${boardSq}` : `/board/${boardSq}`
    router.push(path)
  }
  
  return (
    <div className="table-responsive">
      <table className="table table-hover table-bordered align-middle text-center">
        <thead className="table-light">
          <tr>
            <th className={styles.thWs}>순번</th>
            <th className={styles.thTtl}>제목</th>
            <th className={styles.thWm}>작성자</th>
            <th className={styles.thWl}>등록일</th>
            <th className={styles.thWs}>조회</th>
            <th className={`${styles.thWs} d-none d-md-table-cell`}>댓글</th>
            <th className={`${styles.thWs} d-none d-md-table-cell`}>추천</th>
            {isQna && <th className={styles.thWl}>상태</th>}
          </tr>
        </thead>
        <tbody>
          {boardList && boardList.length > 0 ? (
            boardList.map((board) => (
              <tr key={board.sq} style={{ cursor: 'pointer' }}>
                <td onClick={() => handleRowClick(board.sq)}>{board.sq}</td>
                <td className="text-start px-3" onClick={() => handleRowClick(board.sq)}>
                  <a
                    href={`/${isQna ? 'qna' : 'board'}/${board.sq}`}
                    onClick={(e) => {
                      e.preventDefault()
                      handleRowClick(board.sq)
                    }}
                  >
                    {board.ttl}
                    {isQna && board.answerCnt > 0 && (
                      <span className="text-grey ml-1 px-2">
                        <i className="fas fa-comment-dots me-1"></i>답변 {board.answerCnt}
                      </span>
                    )}
                  </a>
                  <BoardTags
                    skillTags={board.skillTags || []}
                    normalTags={board.normalTags || []}
                  />
                </td>
                <td onClick={() => handleRowClick(board.sq)}>{board.userNm}</td>
                <td onClick={() => handleRowClick(board.sq)}>{formatTime(board.createdAt)}</td>
                <td onClick={() => handleRowClick(board.sq)}>{board.viewCnt}</td>
                <td className="d-none d-md-table-cell" onClick={() => handleRowClick(board.sq)}>
                  {board.commentCnt}
                </td>
                <td className="d-none d-md-table-cell" onClick={() => handleRowClick(board.sq)}>
                  {board.recommendCnt}
                </td>
                {isQna && (
                  <td onClick={() => handleRowClick(board.sq)}>
                    {board.boardAdoptStatusCd === 1501 && (
                      <span className="badge bg-warning">진행중</span>
                    )}
                    {board.boardAdoptStatusCd === 1502 && (
                      <span className="badge bg-success">채택완료</span>
                    )}
                    {board.boardAdoptStatusCd === 1503 && (
                      <span className="badge bg-secondary">자체해결</span>
                    )}
                    {board.boardAdoptStatusCd === 1504 && (
                      <span className="badge bg-danger">미해결</span>
                    )}
                  </td>
                )}
              </tr>
            ))
          ) : (
            <tr>
              <td className="text-start px-3 text-center" colSpan={isQna ? 8 : 7}>
                게시글이 없습니다.
              </td>
            </tr>
          )}
        </tbody>
      </table>
    </div>
  )
}
