// frontend/vue_js/src/fo/components/common/CommonFooter.vue
<template>
  <footer id="footer" class="footer-top-border bg-color-grey">
    <div class="footer-copyright bg-color-grey">
      <div class="container py-2">
        <div class="row py-4">
          <div class="col-12 d-flex justify-content-between align-items-center">
            <p class="mb-0">
              <strong>이에스티 소프트</strong> 
            </p>
            <p class="mb-0 text-end">
              <router-link to="/privacy">개인정보 처리 방침</router-link> |
              <router-link to="/terms">이용약관</router-link>
              <span class="ms-2">- © Copyright 2024. All Rights Reserved.</span>
            </p>
          </div>
        </div>
      </div>
    </div>
  </footer>
</template>

<script setup></script>

<style scoped>

</style>

// frontend/react_js/components/common/CommonFooter.js
export default function CommonFooter() {
  return (
    <footer id="footer" className="footer-top-border bg-color-grey">
      <div className="footer-copyright bg-color-grey">
        <div className="container py-2">
          <div className="row py-4">
            <div className="col d-flex align-items-center justify-content-center">
              <p>
                <strong>PORTO TEMPLATE</strong> - © Copyright 2024. All Rights Reserved.
              </p>
            </div>
          </div>
        </div>
      </div>
    </footer>
  )
}
