// frontend/react_js/components/common/CommonHeader.js
import { useState, useEffect, useRef } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useAuth } from '@/contexts/AuthContext'
import { useAlert } from '@/contexts/AlertContext'
import { api } from '@/lib/axios'
import styles from './CommonHeader.module.css'

export default function CommonHeader() {
  const router = useRouter()
  const { user, isLoggedIn, clearUser } = useAuth()
  const { showAlert } = useAlert()

  const [isCommunityDropdownOpen, setIsCommunityDropdownOpen] = useState(false)
  
  const headerRef = useRef(null)
  const notificationDropdownRef = useRef(null)
  const userDropdownRef = useRef(null)

  // 현재 경로
  const currentPath = router.pathname

  // 각 메뉴의 활성 여부 판별
  const isAffiliationActive = currentPath.startsWith('/affiliation')
  const isProjectActive = currentPath.startsWith('/project')
  const isCommunityActive = ['/board', '/qna'].some((path) => currentPath.startsWith(path))

  // 모바일 메뉴 닫기
  const closeMenu = () => {
    const navCollapse = document.querySelector('.header-nav-main nav.collapse')
    if (navCollapse && navCollapse.classList.contains('show')) {
      const collapseInstance = window.bootstrap?.Collapse?.getInstance(navCollapse)
      if (collapseInstance) {
        collapseInstance.hide()
      }
    }
  }

  // 외부 클릭 시 메뉴 닫기
  const handleClickOutside = (event) => {
    if (headerRef.current && !headerRef.current.contains(event.target)) {
      closeMenu()
    }
  }

  // 커뮤니티 드롭다운 토글
  const toggleCommunityDropdown = () => {
    setIsCommunityDropdownOpen(!isCommunityDropdownOpen)
  }

  // 로그아웃
  const logout = async () => {
    await api.$post('/logout', {})

    // 1. 아이디 저장값만 따로 저장
    const savedPersonalId = localStorage.getItem('savedPersonalId')
    const savedCompanyId = localStorage.getItem('savedCompanyId')
    const savedLoginType = localStorage.getItem('savedLoginType')

    // 2. 로컬스토리지 전체 초기화
    localStorage.clear()

    // 3. 아이디 저장값 복원
    if (savedPersonalId) localStorage.setItem('savedPersonalId', savedPersonalId)
    if (savedCompanyId) localStorage.setItem('savedCompanyId', savedCompanyId)
    if (savedLoginType) localStorage.setItem('savedLoginType', savedLoginType)

    // 4. Context 상태 초기화
    clearUser()
    showAlert('로그아웃되었습니다.', 'success')
    
    // 5. 메인 페이지로 이동
    router.push('/')
  }

  // 이벤트 리스너 등록
  useEffect(() => {
    document.addEventListener('mousedown', handleClickOutside)
    
    return () => {
      document.removeEventListener('mousedown', handleClickOutside)
    }
  }, [])

  // 경로 변경 시 메뉴 닫기
  useEffect(() => {
    closeMenu()
    setIsCommunityDropdownOpen(false)
  }, [currentPath])

  return (
    <header
      id="header"
      ref={headerRef}
      className="header-effect-shrink header-spacing"
      data-plugin-options='{"stickyEnabled": true}'
    >
      {isLoggedIn ? (
        /* 로그인 상태 */
        <div className={`${styles.headerBody} border-0`}>
          <div className="header-container container">
            <div className="header-row justify-content-between">
              <div className="header-left d-flex align-items-center">
                <a
                  href="/"
                  className={`text-primary fs-3 text-decoration-none ${styles.home}`}
                  onClick={(e) => {
                    e.preventDefault()
                    closeMenu()
                    router.push('/')
                  }}
                >
                  Freelancer<br />
                  Service
                </a>
              </div>
              <div className="d-flex align-items-center">
                <div className="header-nav header-nav-line header-nav-top-line header-nav-top-line-with-border order-2 order-lg-1">
                  <div className="header-nav-main header-nav-main-square header-nav-main-effect-2 header-nav-main-sub-effect-1">
                    <nav className="collapse">
                      <ul className="nav nav-pills" id="mainNav">
                        <li className="dropdown">
                          <a
                            href="/affiliation"
                            className={`dropdown-item dropdown-toggle ${isAffiliationActive ? 'active current-page-active' : ''}`}
                            onClick={(e) => {
                              e.preventDefault()
                              router.push('/affiliation')
                            }}
                          >
                            소속
                            <i className="fas fa-chevron-down"></i>
                          </a>
                        </li>
                        <li className="dropdown">
                          <a
                            href="/project"
                            className={`dropdown-item dropdown-toggle ${isProjectActive ? 'active current-page-active' : ''}`}
                            onClick={(e) => {
                              e.preventDefault()
                              router.push('/project')
                            }}
                          >
                            프로젝트
                            <i className="fas fa-chevron-down"></i>
                          </a>
                        </li>
                        <li className={`dropdown ${isCommunityDropdownOpen ? 'open' : ''}`}>
                          <a
                            href="#"
                            className={`dropdown-item dropdown-toggle ${isCommunityActive ? 'active current-page-active' : ''}`}
                            onClick={(e) => {
                              e.preventDefault()
                              toggleCommunityDropdown()
                            }}
                            data-community-toggle
                          >
                            커뮤니티
                            <i className="fas fa-chevron-down"></i>
                          </a>
                          <ul className="dropdown-menu">
                            <li>
                              <a
                                href="/board"
                                className="dropdown-item"
                                onClick={(e) => {
                                  e.preventDefault()
                                  router.push('/board')
                                }}
                              >
                                일반 게시판
                              </a>
                            </li>
                            <li>
                              <a
                                href="/qna"
                                className="dropdown-item"
                                onClick={(e) => {
                                  e.preventDefault()
                                  router.push('/qna')
                                }}
                              >
                                Q&A 게시판
                              </a>
                            </li>
                          </ul>
                        </li>
                      </ul>
                    </nav>
                  </div>
                  <button
                    className="btn header-btn-collapse-nav"
                    data-bs-toggle="collapse"
                    data-bs-target=".header-nav-main nav"
                  >
                    <i className="fas fa-bars"></i>
                  </button>
                </div>
                <div className="header-nav-features header-nav-features-no-border header-nav-features-lg-show-border order-1 order-lg-2">
                  <div className="header-nav-feature d-inline-flex gap-2 align-items-center">
                    {/* 알림 드롭다운 */}
                    <div className="dropdown" ref={notificationDropdownRef}>
                      <a
                        href="#"
                        role="button"
                        className="btn btn-light d-flex justify-content-center align-items-center position-relative dropdown-toggle no-caret"
                        id="notificationDropdown"
                        data-bs-toggle="dropdown"
                        aria-expanded="false"
                        style={{ width: '36px', height: '36px', borderRadius: '50%' }}
                      >
                        <i className="bi bi-bell fs-5"></i>
                        <span
                          className="position-absolute border border-light rounded-circle"
                          style={{
                            top: '-1px',
                            right: '-1px',
                            width: '10px',
                            height: '10px',
                            backgroundColor: 'var(--bs-primary)',
                            opacity: '0.85'
                          }}
                        ></span>
                      </a>
                      <div
                        className="dropdown-menu dropdown-menu-end p-2 shadow"
                        aria-labelledby="notificationDropdown"
                        style={{ minWidth: '250px' }}
                      >
                        <div className="dropdown-item small text-muted">
                          🔧 준비 중입니다.
                        </div>
                      </div>
                    </div>

                    {/* 유저 드롭다운 */}
                    <div className="dropdown" ref={userDropdownRef}>
                      <a
                        href="#"
                        role="button"
                        className="btn btn-light d-flex align-items-center gap-2 px-3 py-1 dropdown-toggle"
                        style={{ height: '36px', borderRadius: '50px' }}
                        id="userDropdown"
                        data-bs-toggle="dropdown"
                        aria-expanded="false"
                      >
                        <i className="bi bi-person-circle fs-5"></i>
                        <span>{user.userNm}</span>
                      </a>
                      <ul
                        className="dropdown-menu dropdown-menu-end mt-2"
                        aria-labelledby="userDropdown"
                        style={{ minWidth: '150px' }}
                      >
                        <li>
                          <a 
                            href="/mypage" 
                            className="dropdown-item"
                            onClick={(e) => {
                              e.preventDefault()
                              router.push('/mypage')
                            }}
                          >
                            마이페이지
                          </a>
                        </li>
                        <li>
                          <hr className="dropdown-divider" />
                        </li>
                        <li>
                          <a href="#" className="dropdown-item" onClick={(e) => { e.preventDefault(); logout() }}>
                            로그아웃
                          </a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      ) : (
        /* 비로그인 상태 */
        <div className={`${styles.headerBody} border-0`}>
          <div className="header-container container">
            <div className="header-row justify-content-between">
              <div className="header-left d-flex align-items-center">
                <a
                  href="/"
                  className={`text-primary fs-3 text-decoration-none ${styles.home}`}
                  onClick={(e) => {
                    e.preventDefault()
                    closeMenu()
                    router.push('/')
                  }}
                >
                  Freelancer<br />
                  Service
                </a>
              </div>

              <div className="d-flex align-items-center">
                {/* 네비게이션 메뉴 */}
                <div className="header-nav header-nav-line header-nav-top-line header-nav-top-line-with-border order-2 order-lg-1">
                  <div className="header-nav-main header-nav-main-square header-nav-main-effect-2 header-nav-main-sub-effect-1">
                    <nav className="collapse">
                      <ul className="nav nav-pills" id="mainNav">
                        <li className="dropdown">
                          <a
                            href="/affiliation"
                            className={`dropdown-item dropdown-toggle ${isAffiliationActive ? 'active current-page-active' : ''}`}
                            onClick={(e) => {
                              e.preventDefault()
                              router.push('/affiliation')
                            }}
                          >
                            소속
                            <i className="fas fa-chevron-down"></i>
                          </a>
                        </li>
                        <li className="dropdown">
                          <a
                            href="/project"
                            className={`dropdown-item dropdown-toggle ${isProjectActive ? 'active current-page-active' : ''}`}
                            onClick={(e) => {
                              e.preventDefault()
                              router.push('/project')
                            }}
                          >
                            프로젝트
                            <i className="fas fa-chevron-down"></i>
                          </a>
                        </li>
                        <li className={`dropdown ${isCommunityDropdownOpen ? 'open' : ''}`}>
                          <a
                            href="#"
                            className={`dropdown-item dropdown-toggle ${isCommunityActive ? 'active current-page-active' : ''}`}
                            onClick={(e) => {
                              e.preventDefault()
                              toggleCommunityDropdown()
                            }}
                            data-community-toggle
                          >
                            커뮤니티
                            <i className="fas fa-chevron-down"></i>
                          </a>
                          <ul className="dropdown-menu">
                            <li>
                              <a
                                href="/board"
                                className="dropdown-item"
                                onClick={(e) => {
                                  e.preventDefault()
                                  router.push('/board')
                                }}
                              >
                                일반 게시판
                              </a>
                            </li>
                            <li>
                              <a
                                href="/qna"
                                className="dropdown-item"
                                onClick={(e) => {
                                  e.preventDefault()
                                  router.push('/qna')
                                }}
                              >
                                Q&A 게시판
                              </a>
                            </li>
                          </ul>
                        </li>
                      </ul>
                    </nav>
                  </div>
                  <button
                    className="btn header-btn-collapse-nav"
                    data-bs-toggle="collapse"
                    data-bs-target=".header-nav-main nav"
                  >
                    <i className="fas fa-bars"></i>
                  </button>
                </div>

                {/* 로그인 링크 */}
                <div className="header-nav-features header-nav-features-no-border header-nav-features-lg-show-border order-1 order-lg-2">
                  <div className="header-nav-feature d-inline-flex">
                    <a 
                      href="/auth/login" 
                      className="text-muted text-decoration-none"
                      onClick={(e) => {
                        e.preventDefault()
                        router.push('/auth/login')
                      }}
                    >
                      로그인
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </header>
  )
}

// frontend/vue_js/src/fo/components/common/CommonHeader.vue
<template>
  <header
    id="header"
    ref="headerRef"
    class="header-effect-shrink header-spacing"
    data-plugin-options='{"stickyEnabled": true}'
  >
    <!-- <header
    id="header"
    class="header-effect-shrink"
    data-plugin-options="{'stickyEnabled': true, 'stickyEffect': 'shrink', 'stickyEnableOnBoxed': true, 'stickyEnableOnMobile': false, 'stickyChangeLogo': true, 'stickyStartAt': 30, 'stickyHeaderContainerHeight': 70}"
    style="height: 103.2px"
  > -->
    <!-- 로그인 상태 -->
    <div v-if="isLoggedIn" class="header-body border-0">
      <div class="header-container container">
        <div class="header-row justify-content-between">
          <div class="header-left d-flex align-items-center">
            <router-link
              to="/"
              class="text-primary fs-3 text-decoration-none home"
              @click="closeMenu"
            >
              Freelancer<br />
              Service
            </router-link>
          </div>
          <div class="d-flex align-items-center">
            <div
              class="header-nav header-nav-line header-nav-top-line header-nav-top-line-with-border order-2 order-lg-1"
            >
              <div
                class="header-nav-main header-nav-main-square header-nav-main-effect-2 header-nav-main-sub-effect-1"
              >
                <nav class="collapse">
                  <ul class="nav nav-pills" id="mainNav">
                    <li class="dropdown">
                      <router-link
                        class="dropdown-item dropdown-toggle"
                        :class="{
                          active: isAffiliationActive,
                          'current-page-active': true,
                        }"
                        to="/affiliation"
                      >
                        소속
                        <i class="fas fa-chevron-down"></i
                      ></router-link>
                    </li>
                    <li class="dropdown">
                      <router-link
                        class="dropdown-item dropdown-toggle"
                        :class="{
                          active: isProjectActive,
                          'current-page-active': true,
                        }"
                        to="/projectListPage"
                      >
                        프로젝트
                        <i class="fas fa-chevron-down"></i
                      ></router-link>
                    </li>
                    <li
                      class="dropdown"
                      :class="{ open: isCommunityDropdownOpen }"
                    >
                      <a
                        href="#"
                        class="dropdown-item dropdown-toggle"
                        :class="{
                          active: isCommunityActive,
                          'current-page-active': true,
                        }"
                        @click.prevent="toggleCommunityDropdown"
                        data-community-toggle
                      >
                        커뮤니티
                        <i class="fas fa-chevron-down"></i
                      ></a>
                      <ul class="dropdown-menu">
                        <li>
                          <router-link class="dropdown-item" to="/board"
                            >일반 게시판
                          </router-link>
                        </li>
                        <li>
                          <router-link class="dropdown-item" to="/qna"
                            >Q&A 게시판
                          </router-link>
                        </li>
                      </ul>
                    </li>
                  </ul>
                </nav>
              </div>
              <button
                class="btn header-btn-collapse-nav"
                data-bs-toggle="collapse"
                data-bs-target=".header-nav-main nav"
              >
                <i class="fas fa-bars"></i>
              </button>
            </div>
            <div
              class="header-nav-features header-nav-features-no-border header-nav-features-lg-show-border order-1 order-lg-2"
            >
              <div
                class="header-nav-feature d-inline-flex gap-2 align-items-center"
              >
                <!-- 알림 드롭다운 -->
                <div class="dropdown" ref="notificationDropdownRef">
                  <a
                    href="#"
                    role="button"
                    class="btn btn-light d-flex justify-content-center align-items-center position-relative dropdown-toggle no-caret"
                    id="notificationDropdown"
                    data-bs-toggle="dropdown"
                    aria-expanded="false"
                    style="width: 36px; height: 36px; border-radius: 50%"
                  >
                    <i class="bi bi-bell fs-5"></i>

                    <!-- 알림 배지 -->
                    <span
                      class="position-absolute border border-light rounded-circle"
                      style="
                        top: -1px;
                        right: -1px;
                        width: 10px;
                        height: 10px;
                        background-color: var(--bs-primary);
                        opacity: 0.85;
                      "
                    >
                    </span>
                  </a>

                  <div
                    class="dropdown-menu dropdown-menu-end p-2 shadow"
                    aria-labelledby="notificationDropdown"
                    style="
                      min-width: 250px;
                      max-height: 300px;
                      overflow-y: auto;
                    "
                  >
                    <h6 class="dropdown-header">알림</h6>
                    <div class="dropdown-item small text-muted">
                      📌 프로젝트 모집 마감 임박 <br /><small>2분 전</small>
                    </div>
                    <div class="dropdown-item small text-muted">
                      ✅ 프로젝트가 승인되었어요 <br /><small>10분 전</small>
                    </div>
                    <div class="dropdown-item small text-muted">
                      🔔 스크랩 기업 신규 공고 <br /><small>3시간 전</small>
                    </div>
                    <div class="dropdown-item small text-muted">
                      🗨️ 작성하신 게시글에 댓글이 달렸습니다. <br /><small
                        >1시간 전</small
                      >
                    </div>
                    <div class="dropdown-divider"></div>
                    <a
                      class="dropdown-item text-center small text-primary"
                      href="/notifications"
                      >전체 보기</a
                    >
                  </div>
                  <!-- <div
                    class="dropdown-menu dropdown-menu-end p-2 shadow"
                    aria-labelledby="notificationDropdown"
                    style="min-width: 250px"
                  >
                    <div class="dropdown-item small text-muted">
                      🔧 준비 중입니다.
                    </div>
                  </div> -->
                </div>

                <!-- 유저 아이콘 + 이름 (버튼 정렬) -->
                <!-- 유저 아이콘 + 이름 (드롭다운) -->
                <div class="dropdown" ref="userDropdownRef">
                  <a
                    href="#"
                    role="button"
                    class="btn btn-light d-flex align-items-center gap-2 px-3 py-1 dropdown-toggle"
                    style="height: 36px; border-radius: 50px"
                    id="userDropdown"
                    data-bs-toggle="dropdown"
                    aria-expanded="false"
                  >
                    <i class="bi bi-person-circle fs-5"></i>
                    <span>{{ userStore.userNm }}</span>
                  </a>

                  <ul
                    class="dropdown-menu dropdown-menu-end mt-2"
                    aria-labelledby="userDropdown"
                    style="min-width: 150px"
                  >
                    <li>
                      <router-link class="dropdown-item" to="/mypage"
                        >마이페이지</router-link
                      >
                    </li>
                    <li>
                      <hr class="dropdown-divider" />
                    </li>
                    <li>
                      <a class="dropdown-item" href="#" @click.prevent="logout"
                        >로그아웃</a
                      >
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- 비로그인 상태 -->
    <div v-else class="header-body border-0">
      <div class="header-container container">
        <div class="header-row justify-content-between">
          <div class="header-left d-flex align-items-center">
            <router-link
              to="/"
              class="text-primary fs-3 text-decoration-none home"
              @click="closeMenu"
            >
              Freelancer<br />
              Service
            </router-link>
          </div>

          <div class="d-flex align-items-center">
            <!-- 네비게이션 메뉴 -->
            <div
              class="header-nav header-nav-line header-nav-top-line header-nav-top-line-with-border order-2 order-lg-1"
            >
              <div
                class="header-nav-main header-nav-main-square header-nav-main-effect-2 header-nav-main-sub-effect-1"
              >
                <nav class="collapse">
                  <ul class="nav nav-pills" id="mainNav">
                    <li class="dropdown">
                      <router-link
                        class="dropdown-item dropdown-toggle"
                        :class="{
                          active: isAffiliationActive,
                          'current-page-active': true,
                        }"
                        to="/affiliation"
                      >
                        소속
                        <i class="fas fa-chevron-down"></i>
                      </router-link>
                    </li>
                    <li class="dropdown">
                      <router-link
                        class="dropdown-item dropdown-toggle"
                        :class="{
                          active: isProjectActive,
                          'current-page-active': true,
                        }"
                        to="/projectListPage"
                      >
                        프로젝트
                        <i class="fas fa-chevron-down"></i>
                      </router-link>
                    </li>
                    <li
                      class="dropdown"
                      :class="{ open: isCommunityDropdownOpen }"
                    >
                      <a
                        href="#"
                        class="dropdown-item dropdown-toggle"
                        :class="{
                          active: isCommunityActive,
                          'current-page-active': true,
                        }"
                        @click.prevent="toggleCommunityDropdown"
                        data-community-toggle
                      >
                        커뮤니티
                        <i class="fas fa-chevron-down"></i>
                      </a>
                      <ul class="dropdown-menu">
                        <li>
                          <router-link class="dropdown-item" to="/board"
                            >일반 게시판</router-link
                          >
                        </li>
                        <li>
                          <router-link class="dropdown-item" to="/qna"
                            >Q&A 게시판</router-link
                          >
                        </li>
                      </ul>
                    </li>
                  </ul>
                </nav>
              </div>
              <button
                class="btn header-btn-collapse-nav"
                data-bs-toggle="collapse"
                data-bs-target=".header-nav-main nav"
              >
                <i class="fas fa-bars"></i>
              </button>
            </div>

            <!-- 로그인 링크 -->
            <div
              class="header-nav-features header-nav-features-no-border header-nav-features-lg-show-border order-1 order-lg-2"
            >
              <div class="header-nav-feature d-inline-flex">
                <router-link to="/login" class="text-muted text-decoration-none"
                  >로그인</router-link
                >
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
</template>

<script setup>
import { onMounted, onBeforeUnmount, computed, ref, watch } from 'vue'
import { useUserStore } from '@/fo/stores/userStore'
import { useAlertStore } from '@/fo/stores/alertStore'
import router from '@/fo/router'
import { api } from '@/axios'
import { useRoute } from 'vue-router'

const alertStore = useAlertStore()
const userStore = useUserStore()
const isLoggedIn = computed(() => userStore.isLoggedIn)
const route = useRoute()
const headerRef = ref(null)
const notificationDropdownRef = ref(null)
const userDropdownRef = ref(null)

const closeMenu = () => {
  const navCollapse = document.querySelector('.header-nav-main nav.collapse')
  if (navCollapse && navCollapse.classList.contains('show')) {
    const collapseInstance = window.bootstrap.Collapse.getInstance(navCollapse)
    if (collapseInstance) {
      collapseInstance.hide()
    }
  }
}

const handleClickOutside = (event) => {
  if (headerRef.value && !headerRef.value.contains(event.target)) {
    closeMenu()
  }
}

// 현재 경로
const currentPath = computed(() => route.path)

// 각 메뉴의 활성 여부 판별
const isAffiliationActive = computed(() =>
  currentPath.value.startsWith('/affiliation'),
)
const isProjectActive = computed(() =>
  currentPath.value.startsWith('/projectListPage'),
)
const isCommunityActive = computed(() =>
  ['/board', '/qna'].some((path) => currentPath.value.startsWith(path)),
)

// Mobile dropdown state
const isCommunityDropdownOpen = ref(false)

const toggleCommunityDropdown = () => {
  isCommunityDropdownOpen.value = !isCommunityDropdownOpen.value
}

const logout = async () => {
  await api.$post('/logout', {}) // 서버 로그아웃 API 호출

  // 1. 아이디 저장값(개인/기업 아이디, 로그인 타입)만 따로 저장해둠
  const savedPersonalId = localStorage.getItem('savedPersonalId')
  const savedCompanyId = localStorage.getItem('savedCompanyId')
  const savedLoginType = localStorage.getItem('savedLoginType')

  // 2. 로컬스토리지 전체 초기화
  localStorage.clear()

  // 3. 아이디 저장값 복원
  if (savedPersonalId) localStorage.setItem('savedPersonalId', savedPersonalId)
  if (savedCompanyId) localStorage.setItem('savedCompanyId', savedCompanyId)
  if (savedLoginType) localStorage.setItem('savedLoginType', savedLoginType)

  // 4. Pinia 상태 초기화
  userStore.$reset() // userStore가 Pinia store라면 $reset() 으로 초기화 가
  alertStore.show('로그아웃되었습니다.', 'success')
  // 5. 메인 페이지로 이동
  router.push('/')
}

onMounted(() => {
  document.addEventListener('mousedown', handleClickOutside)
  if (notificationDropdownRef.value) {
    notificationDropdownRef.value.addEventListener(
      'show.bs.dropdown',
      closeMenu,
    )
  }
  if (userDropdownRef.value) {
    userDropdownRef.value.addEventListener('show.bs.dropdown', closeMenu)
  }
})

watch(currentPath, () => {
  closeMenu()
  isCommunityDropdownOpen.value = false
})

onBeforeUnmount(() => {
  document.removeEventListener('mousedown', handleClickOutside)
  if (notificationDropdownRef.value) {
    notificationDropdownRef.value.removeEventListener(
      'show.bs.dropdown',
      closeMenu,
    )
  }
  if (userDropdownRef.value) {
    userDropdownRef.value.removeEventListener('show.bs.dropdown', closeMenu)
  }
})
</script>

<style scoped>
.home {
  font-weight: bold;
  display: block;
  text-align: center;
}

.header-body {
  position: fixed !important;
  top: 0;
  z-index: 999;
  width: 100%;
  background: white;
  height: 100px; /* 초기 높이 설정 */
  transition: box-shadow 0.3s ease; /* transition을 box-shadow에만 적용 */
}

.header-body.shrink {
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1); /* 스크롤 시 그림자 효과 */
}

/* dropdown-toggle 클래스의 화살표 제거 */
#notificationDropdown::after {
  display: none !important;
}

/* Mobile Menu Dropdown Styles */
@media (max-width: 991px) {
  .header-nav-main nav .dropdown .dropdown-menu {
    display: none;
    /* position: static; */ /* Caused layout issues */
    border: none;
    box-shadow: none;
    background: transparent;
    padding-left: 15px;
  }

  .header-nav-main nav .dropdown.open > .dropdown-menu {
    display: block;
  }

  .header-nav-main nav .dropdown .dropdown-toggle::after {
    content: '\f078'; /* FontAwesome down arrow */
    font-family: 'Font Awesome 5 Free';
    font-weight: 900;
    transition: transform 0.2s ease;
    position: absolute;
    right: 15px;
    top: 50%;
    transform: translateY(-50%);
  }

  .header-nav-main nav .dropdown.open > .dropdown-toggle::after {
    transform: translateY(-50%) rotate(180deg);
  }
}
</style>
