// frontend/react_js/components/project/ProjectFilterBar.js
import { useState, useEffect, useMemo } from 'react'
import { api } from '@/lib/axios'

export default function ProjectFilterBar({ onUpdate }) {
  // API로부터 가져올 옵션들
  const [localOptions, setLocalOptions] = useState([])
  const [careerOptions, setCareerOptions] = useState([])
  const [educationOptions, setEducationOptions] = useState([])
  const [jobTypeOptions, setJobTypeOptions] = useState([])
  const [isInitialized, setIsInitialized] = useState(false)

  // 선택된 값들 (다중 선택)
  const [selectedRegions, setSelectedRegions] = useState([])
  const [selectedCareers, setSelectedCareers] = useState([])
  const [selectedEducations, setSelectedEducations] = useState([])
  const [selectedJobTypes, setSelectedJobTypes] = useState([])

  // 기타 필터 값
  const [searchKeyword, setSearchKeyword] = useState('')
  const [selectedTargetField, setSelectedTargetField] = useState('전체')
  const [selectedSort, setSelectedSort] = useState('최신순')

  // 드롭다운 버튼 텍스트 (웹용 - 전체 표시)
  const selectedRegionText = useMemo(() => {
    if (selectedRegions.length === 0) return '지역 (전체)'
    if (selectedRegions.length === 1) {
      const selected = localOptions.find(opt => opt.areaSq === selectedRegions[0])
      return selected ? selected.areaName : '지역'
    }
    return `지역 (${selectedRegions.length}개)`
  }, [selectedRegions, localOptions])

  const selectedCareerText = useMemo(() => {
    if (selectedCareers.length === 0) return '경력 (전체)'
    if (selectedCareers.length === 1) {
      const selected = careerOptions.find(opt => opt.common_code_sq === selectedCareers[0])
      return selected ? selected.common_code_nm : '경력'
    }
    return `경력 (${selectedCareers.length}개)`
  }, [selectedCareers, careerOptions])

  const selectedEducationText = useMemo(() => {
    if (selectedEducations.length === 0) return '학력 (전체)'
    if (selectedEducations.length === 1) {
      const selected = educationOptions.find(opt => opt.common_code_sq === selectedEducations[0])
      return selected ? selected.common_code_nm : '학력'
    }
    return `학력 (${selectedEducations.length}개)`
  }, [selectedEducations, educationOptions])

  const selectedJobTypeText = useMemo(() => {
    if (selectedJobTypes.length === 0) return '직종 (전체)'
    if (selectedJobTypes.length === 1) {
      const selected = jobTypeOptions.find(opt => opt.common_code_sq === selectedJobTypes[0])
      return selected ? selected.common_code_nm : '직종'
    }
    return `직종 (${selectedJobTypes.length}개)`
  }, [selectedJobTypes, jobTypeOptions])

  // 모바일용 텍스트 (간략 - 전체 표시 안 함)
  const selectedRegionTextMobile = useMemo(() => {
    if (selectedRegions.length === 0) return '지역'
    if (selectedRegions.length === 1) {
      const selected = localOptions.find(opt => opt.areaSq === selectedRegions[0])
      return selected ? selected.areaName : '지역'
    }
    return `지역 (${selectedRegions.length}개)`
  }, [selectedRegions, localOptions])

  const selectedCareerTextMobile = useMemo(() => {
    if (selectedCareers.length === 0) return '경력'
    if (selectedCareers.length === 1) {
      const selected = careerOptions.find(opt => opt.common_code_sq === selectedCareers[0])
      return selected ? selected.common_code_nm : '경력'
    }
    return `경력 (${selectedCareers.length}개)`
  }, [selectedCareers, careerOptions])

  const selectedEducationTextMobile = useMemo(() => {
    if (selectedEducations.length === 0) return '학력'
    if (selectedEducations.length === 1) {
      const selected = educationOptions.find(opt => opt.common_code_sq === selectedEducations[0])
      return selected ? selected.common_code_nm : '학력'
    }
    return `학력 (${selectedEducations.length}개)`
  }, [selectedEducations, educationOptions])

  const selectedJobTypeTextMobile = useMemo(() => {
    if (selectedJobTypes.length === 0) return '직종'
    if (selectedJobTypes.length === 1) {
      const selected = jobTypeOptions.find(opt => opt.common_code_sq === selectedJobTypes[0])
      return selected ? selected.common_code_nm : '직종'
    }
    return `직종 (${selectedJobTypes.length}개)`
  }, [selectedJobTypes, jobTypeOptions])

  // API에서 필터 옵션 가져오기
  const fetchFilterOptions = async () => {
    try {
      const basePath = '/projects'
      const [regionRes, careerRes, educationRes, jobTypeRes] = await Promise.all([
        api.$get(`${basePath}/filters`, { params: { type: '지역' } }),
        api.$get(`${basePath}/filters`, { params: { type: '경력' } }),
        api.$get(`${basePath}/filters`, { params: { type: '학력' } }),
        api.$get(`${basePath}/filters`, { params: { type: '직종' } })
      ])
      setLocalOptions(regionRes.output || [])
      setCareerOptions(careerRes.output || [])
      setEducationOptions(educationRes.output || [])
      setJobTypeOptions(jobTypeRes.output || [])
    } catch (e) {
      console.error('필터 데이터 불러오기 실패', e)
    }
  }

  useEffect(() => {
    fetchFilterOptions()
  }, [])

  // 필터 변경 시 부모에게 전달
  useEffect(() => {
    // 초기화가 완료된 후에만 onUpdate 호출 (무한 루프 방지)
    if (!isInitialized) {
      setIsInitialized(true)
      return
    }

    const filters = {
      addressCodeSq: selectedRegions,
      projectDeveloperGradeCd: selectedCareers,
      educationCd: selectedEducations,
      jobRoleCd: selectedJobTypes,
      searchKeyword: searchKeyword,
      searchType: selectedTargetField
    }

    if (selectedSort === '최신순') {
      filters.sortBy = 'project_start_dt'
      filters.sortOrder = 'desc'
    } else if (selectedSort === '조회순') {
      filters.sortBy = 'view_count'
      filters.sortOrder = 'desc'
    } else if (selectedSort === '지원자순') {
      filters.sortBy = 'applicant_count'
      filters.sortOrder = 'desc'
    }

    onUpdate(filters)
  }, [selectedRegions, selectedCareers, selectedEducations, selectedJobTypes, searchKeyword, selectedTargetField, selectedSort, onUpdate, isInitialized])

  // 체크박스 토글
  const toggleCheckbox = (value, selectedArray, setSelectedArray) => {
    if (selectedArray.includes(value)) {
      setSelectedArray(selectedArray.filter(item => item !== value))
    } else {
      setSelectedArray([...selectedArray, value])
    }
  }

  // 선택 초기화
  const clearSelection = (type) => {
    if (type === 'regions') setSelectedRegions([])
    if (type === 'careers') setSelectedCareers([])
    if (type === 'educations') setSelectedEducations([])
    if (type === 'jobTypes') setSelectedJobTypes([])
  }

  return (
    <div>
      {/* Web Layout */}
      <div className="filter-bar border rounded p-3 d-none d-lg-flex align-items-center gap-3 flex-wrap" style={{ maxWidth: '880px', margin: '0 auto' }}>
        {/* Region Dropdown */}
        <div className="dropdown">
          <button className="btn btn-outline btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown">
            {selectedRegionText}
          </button>
          <ul className="dropdown-menu" onClick={(e) => e.stopPropagation()}>
            <li>
              <a className="dropdown-item" href="#" onClick={(e) => { e.preventDefault(); clearSelection('regions') }}>전체</a>
            </li>
            {localOptions.map(local => (
              <li key={local.areaSq}>
                <div className="dropdown-item">
                  <input
                    type="checkbox"
                    id={`region-${local.areaSq}`}
                    value={local.areaSq}
                    checked={selectedRegions.includes(local.areaSq)}
                    onChange={() => toggleCheckbox(local.areaSq, selectedRegions, setSelectedRegions)}
                    className="form-check-input me-2"
                  />
                  <label htmlFor={`region-${local.areaSq}`}>{local.areaName}</label>
                </div>
              </li>
            ))}
          </ul>
        </div>

        {/* Career Dropdown */}
        <div className="dropdown">
          <button className="btn btn-outline btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown">
            {selectedCareerText}
          </button>
          <ul className="dropdown-menu" onClick={(e) => e.stopPropagation()}>
            <li>
              <a className="dropdown-item" href="#" onClick={(e) => { e.preventDefault(); clearSelection('careers') }}>전체</a>
            </li>
            {careerOptions.map(career => (
              <li key={career.common_code_sq}>
                <div className="dropdown-item">
                  <input
                    type="checkbox"
                    id={`career-${career.common_code_sq}`}
                    value={career.common_code_sq}
                    checked={selectedCareers.includes(career.common_code_sq)}
                    onChange={() => toggleCheckbox(career.common_code_sq, selectedCareers, setSelectedCareers)}
                    className="form-check-input me-2"
                  />
                  <label htmlFor={`career-${career.common_code_sq}`}>{career.common_code_nm}</label>
                </div>
              </li>
            ))}
          </ul>
        </div>

        {/* Education Dropdown */}
        <div className="dropdown">
          <button className="btn btn-outline btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown">
            {selectedEducationText}
          </button>
          <ul className="dropdown-menu" onClick={(e) => e.stopPropagation()}>
            <li>
              <a className="dropdown-item" href="#" onClick={(e) => { e.preventDefault(); clearSelection('educations') }}>전체</a>
            </li>
            {educationOptions.map(education => (
              <li key={education.common_code_sq}>
                <div className="dropdown-item">
                  <input
                    type="checkbox"
                    id={`education-${education.common_code_sq}`}
                    value={education.common_code_sq}
                    checked={selectedEducations.includes(education.common_code_sq)}
                    onChange={() => toggleCheckbox(education.common_code_sq, selectedEducations, setSelectedEducations)}
                    className="form-check-input me-2"
                  />
                  <label htmlFor={`education-${education.common_code_sq}`}>{education.common_code_nm}</label>
                </div>
              </li>
            ))}
          </ul>
        </div>

        {/* Job Type Dropdown */}
        <div className="dropdown">
          <button className="btn btn-outline btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown">
            {selectedJobTypeText}
          </button>
          <ul className="dropdown-menu" onClick={(e) => e.stopPropagation()}>
            <li>
              <a className="dropdown-item" href="#" onClick={(e) => { e.preventDefault(); clearSelection('jobTypes') }}>전체</a>
            </li>
            {jobTypeOptions.map(job => (
              <li key={job.common_code_sq}>
                <div className="dropdown-item">
                  <input
                    type="checkbox"
                    id={`job-${job.common_code_sq}`}
                    value={job.common_code_sq}
                    checked={selectedJobTypes.includes(job.common_code_sq)}
                    onChange={() => toggleCheckbox(job.common_code_sq, selectedJobTypes, setSelectedJobTypes)}
                    className="form-check-input me-2"
                  />
                  <label htmlFor={`job-${job.common_code_sq}`}>{job.common_code_nm}</label>
                </div>
              </li>
            ))}
          </ul>
        </div>

        {/* Search Input */}
        <div className="flex-grow-1">
          <input
            type="text"
            className="form-control"
            placeholder="검색어를 입력하세요..."
            style={{ maxWidth: '400px' }}
            value={searchKeyword}
            onChange={(e) => setSearchKeyword(e.target.value)}
          />
        </div>

        {/* Search Type Dropdown */}
        <div className="dropdown">
          <button className="btn btn-outline btn-primary dropdown-toggle text-truncate" type="button" data-bs-toggle="dropdown" style={{ maxWidth: '120px' }}>
            {selectedTargetField}
          </button>
          <ul className="dropdown-menu">
            {['전체', '제목', '작성자명', '내용', '태그'].map(type => (
              <li key={type}>
                <a className="dropdown-item" href="#" onClick={(e) => { e.preventDefault(); setSelectedTargetField(type) }}>
                  {type}
                </a>
              </li>
            ))}
          </ul>
        </div>

        {/* Sort Dropdown */}
        <div className="dropdown">
          <button className="btn btn-outline btn-primary dropdown-toggle text-truncate" type="button" data-bs-toggle="dropdown" style={{ maxWidth: '120px' }}>
            {selectedSort}
          </button>
          <ul className="dropdown-menu">
            {['최신순', '조회순', '지원자순'].map(sort => (
              <li key={sort}>
                <a className="dropdown-item" href="#" onClick={(e) => { e.preventDefault(); setSelectedSort(sort) }}>
                  {sort}
                </a>
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Mobile Layout */}
      <div className="filter-bar border rounded p-3 d-lg-none" style={{ maxWidth: '880px', margin: '0 auto' }}>
        <div className="d-flex flex-wrap gap-2 mb-3">
          {/* Region Dropdown */}
          <div className="dropdown flex-grow-1">
            <button className="btn btn-outline btn-primary dropdown-toggle w-100" type="button" data-bs-toggle="dropdown">
              {selectedRegionTextMobile}
            </button>
            <ul className="dropdown-menu" onClick={(e) => e.stopPropagation()}>
              <li>
                <a className="dropdown-item" href="#" onClick={(e) => { e.preventDefault(); clearSelection('regions') }}>전체</a>
              </li>
              {localOptions.map(local => (
                <li key={local.areaSq}>
                  <div className="dropdown-item">
                    <input
                      type="checkbox"
                      id={`region-mobile-${local.areaSq}`}
                      value={local.areaSq}
                      checked={selectedRegions.includes(local.areaSq)}
                      onChange={() => toggleCheckbox(local.areaSq, selectedRegions, setSelectedRegions)}
                      className="form-check-input me-2"
                    />
                    <label htmlFor={`region-mobile-${local.areaSq}`}>{local.areaName}</label>
                  </div>
                </li>
              ))}
            </ul>
          </div>

          {/* Career Dropdown */}
          <div className="dropdown flex-grow-1">
            <button className="btn btn-outline btn-primary dropdown-toggle w-100" type="button" data-bs-toggle="dropdown">
              {selectedCareerTextMobile}
            </button>
            <ul className="dropdown-menu" onClick={(e) => e.stopPropagation()}>
              <li>
                <a className="dropdown-item" href="#" onClick={(e) => { e.preventDefault(); clearSelection('careers') }}>전체</a>
              </li>
              {careerOptions.map(career => (
                <li key={career.common_code_sq}>
                  <div className="dropdown-item">
                    <input
                      type="checkbox"
                      id={`career-mobile-${career.common_code_sq}`}
                      value={career.common_code_sq}
                      checked={selectedCareers.includes(career.common_code_sq)}
                      onChange={() => toggleCheckbox(career.common_code_sq, selectedCareers, setSelectedCareers)}
                      className="form-check-input me-2"
                    />
                    <label htmlFor={`career-mobile-${career.common_code_sq}`}>{career.common_code_nm}</label>
                  </div>
                </li>
              ))}
            </ul>
          </div>

          {/* Education Dropdown */}
          <div className="dropdown flex-grow-1">
            <button className="btn btn-outline btn-primary dropdown-toggle w-100" type="button" data-bs-toggle="dropdown">
              {selectedEducationTextMobile}
            </button>
            <ul className="dropdown-menu" onClick={(e) => e.stopPropagation()}>
              <li>
                <a className="dropdown-item" href="#" onClick={(e) => { e.preventDefault(); clearSelection('educations') }}>전체</a>
              </li>
              {educationOptions.map(education => (
                <li key={education.common_code_sq}>
                  <div className="dropdown-item">
                    <input
                      type="checkbox"
                      id={`education-mobile-${education.common_code_sq}`}
                      value={education.common_code_sq}
                      checked={selectedEducations.includes(education.common_code_sq)}
                      onChange={() => toggleCheckbox(education.common_code_sq, selectedEducations, setSelectedEducations)}
                      className="form-check-input me-2"
                    />
                    <label htmlFor={`education-mobile-${education.common_code_sq}`}>{education.common_code_nm}</label>
                  </div>
                </li>
              ))}
            </ul>
          </div>

          {/* Job Type Dropdown */}
          <div className="dropdown flex-grow-1">
            <button className="btn btn-outline btn-primary dropdown-toggle w-100" type="button" data-bs-toggle="dropdown">
              {selectedJobTypeTextMobile}
            </button>
            <ul className="dropdown-menu" onClick={(e) => e.stopPropagation()}>
              <li>
                <a className="dropdown-item" href="#" onClick={(e) => { e.preventDefault(); clearSelection('jobTypes') }}>전체</a>
              </li>
              {jobTypeOptions.map(job => (
                <li key={job.common_code_sq}>
                  <div className="dropdown-item">
                    <input
                      type="checkbox"
                      id={`job-mobile-${job.common_code_sq}`}
                      value={job.common_code_sq}
                      checked={selectedJobTypes.includes(job.common_code_sq)}
                      onChange={() => toggleCheckbox(job.common_code_sq, selectedJobTypes, setSelectedJobTypes)}
                      className="form-check-input me-2"
                    />
                    <label htmlFor={`job-mobile-${job.common_code_sq}`}>{job.common_code_nm}</label>
                  </div>
                </li>
              ))}
            </ul>
          </div>
        </div>

        <div className="d-flex align-items-center gap-2">
          {/* Search Input */}
          <div className="flex-grow-1">
            <input
              type="text"
              className="form-control"
              placeholder="검색어를 입력하세요..."
              value={searchKeyword}
              onChange={(e) => setSearchKeyword(e.target.value)}
            />
          </div>

          {/* Search Type Dropdown */}
          <div className="dropdown">
            <button className="btn btn-outline btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown">
              {selectedTargetField}
            </button>
            <ul className="dropdown-menu">
              {['전체', '제목', '작성자명', '내용', '태그'].map(type => (
                <li key={type}>
                  <a className="dropdown-item" href="#" onClick={(e) => { e.preventDefault(); setSelectedTargetField(type) }}>
                    {type}
                  </a>
                </li>
              ))}
            </ul>
          </div>

          {/* Sort Dropdown */}
          <div className="dropdown">
            <button className="btn btn-outline btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown">
              {selectedSort}
            </button>
            <ul className="dropdown-menu">
              {['최신순', '조회순', '지원자순'].map(sort => (
                <li key={sort}>
                  <a className="dropdown-item" href="#" onClick={(e) => { e.preventDefault(); setSelectedSort(sort) }}>
                    {sort}
                  </a>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </div>
  )
}

// frontend/vue_js/src/fo/components/common/ProjectFilterBar.vue
<template>
  <div>
    <!-- Web Layout -->
    <div
      class="filter-bar border rounded p-3 d-none d-lg-flex align-items-center gap-3 flex-wrap"
      style="max-width: 880px; margin: 0 auto"
    >
      <!-- Region Dropdown -->
      <div class="dropdown">
        <button
          class="btn btn-outline-primary dropdown-toggle"
          type="button"
          data-bs-toggle="dropdown"
        >
          {{ selectedRegionText }}
        </button>
        <ul class="dropdown-menu" @click.stop>
          <li>
            <a
              class="dropdown-item"
              href="#"
              @click.prevent="clearSelection('regions')"
              >전체</a
            >
          </li>
          <li v-for="local in localOptions" :key="local.areaSq">
            <div class="dropdown-item">
              <input
                type="checkbox"
                :id="'region-' + local.areaSq"
                :value="local.areaSq"
                v-model="selectedRegions"
                class="form-check-input me-2"
              />
              <label :for="'region-' + local.areaSq">{{
                local.areaName
              }}</label>
            </div>
          </li>
        </ul>
      </div>

      <!-- Career Dropdown -->
      <div class="dropdown">
        <button
          class="btn btn-outline btn-primary dropdown-toggle"
          type="button"
          data-bs-toggle="dropdown"
        >
          {{ selectedCareerText }}
        </button>
        <ul class="dropdown-menu" @click.stop>
          <li>
            <a
              class="dropdown-item"
              href="#"
              @click.prevent="clearSelection('careers')"
              >전체</a
            >
          </li>
          <li v-for="career in careerOptions" :key="career.common_code_sq">
            <div class="dropdown-item">
              <input
                type="checkbox"
                :id="'career-' + career.common_code_sq"
                :value="career.common_code_sq"
                v-model="selectedCareers"
                class="form-check-input me-2"
              />
              <label :for="'career-' + career.common_code_sq">{{
                career.common_code_nm
              }}</label>
            </div>
          </li>
        </ul>
      </div>

      <!-- Education Dropdown -->
      <div class="dropdown">
        <button
          class="btn btn-outline btn-primary dropdown-toggle"
          type="button"
          data-bs-toggle="dropdown"
        >
          {{ selectedEducationText }}
        </button>
        <ul class="dropdown-menu" @click.stop>
          <li>
            <a
              class="dropdown-item"
              href="#"
              @click.prevent="clearSelection('educations')"
              >전체</a
            >
          </li>
          <li
            v-for="education in educationOptions"
            :key="education.common_code_sq"
          >
            <div class="dropdown-item">
              <input
                type="checkbox"
                :id="'education-' + education.common_code_sq"
                :value="education.common_code_sq"
                v-model="selectedEducations"
                class="form-check-input me-2"
              />
              <label :for="'education-' + education.common_code_sq">{{
                education.common_code_nm
              }}</label>
            </div>
          </li>
        </ul>
      </div>

      <!-- Job Type Dropdown -->
      <div class="dropdown">
        <button
          class="btn btn-outline btn-primary dropdown-toggle"
          type="button"
          data-bs-toggle="dropdown"
        >
          {{ selectedJobTypeText }}
        </button>
        <ul class="dropdown-menu" @click.stop>
          <li>
            <a
              class="dropdown-item"
              href="#"
              @click.prevent="clearSelection('jobTypes')"
              >전체</a
            >
          </li>
          <li v-for="job in jobTypeOptions" :key="job.common_code_sq">
            <div class="dropdown-item">
              <input
                type="checkbox"
                :id="'job-' + job.common_code_sq"
                :value="job.common_code_sq"
                v-model="selectedJobTypes"
                class="form-check-input me-2"
              />
              <label :for="'job-' + job.common_code_sq">{{
                job.common_code_nm
              }}</label>
            </div>
          </li>
        </ul>
      </div>

      <!-- Search Input -->
      <div class="flex-grow-1">
        <input
          type="text"
          class="form-control"
          placeholder="검색어를 입력하세요..."
          style="max-width: 400px"
          v-model="searchKeyword"
        />
      </div>

      <!-- Search Type Dropdown -->
      <div class="dropdown">
        <button
          class="btn btn-outline btn-primary dropdown-toggle text-truncate"
          type="button"
          data-bs-toggle="dropdown"
          style="max-width: 120px"
        >
          {{ selectedTargetField }}
        </button>
        <ul class="dropdown-menu">
          <li>
            <a
              class="dropdown-item"
              href="#"
              @click.prevent="updateTargetField('전체')"
              >전체</a
            >
          </li>
          <li>
            <a
              class="dropdown-item"
              href="#"
              @click.prevent="updateTargetField('제목')"
              >제목</a
            >
          </li>
          <li>
            <a
              class="dropdown-item"
              href="#"
              @click.prevent="updateTargetField('작성자명')"
              >작성자명</a
            >
          </li>
          <li>
            <a
              class="dropdown-item"
              href="#"
              @click.prevent="updateTargetField('내용')"
              >내용</a
            >
          </li>
          <li>
            <a
              class="dropdown-item"
              href="#"
              @click.prevent="updateTargetField('태그')"
              >태그</a
            >
          </li>
        </ul>
      </div>

      <!-- Sort Dropdown -->
      <div class="dropdown">
        <button
          class="btn btn-outline btn-primary dropdown-toggle text-truncate"
          type="button"
          data-bs-toggle="dropdown"
          style="max-width: 120px"
        >
          {{ selectedSort }}
        </button>
        <ul class="dropdown-menu">
          <li>
            <a
              class="dropdown-item"
              href="#"
              @click.prevent="updateSort('최신순')"
              >최신순</a
            >
          </li>
          <li>
            <a
              class="dropdown-item"
              href="#"
              @click.prevent="updateSort('조회순')"
              >조회순</a
            >
          </li>
          <li>
            <a
              class="dropdown-item"
              href="#"
              @click.prevent="updateSort('지원자순')"
              >지원자순</a
            >
          </li>
        </ul>
      </div>
    </div>

    <!-- Mobile Layout -->
    <div
      class="filter-bar border rounded p-3 d-lg-none"
      style="max-width: 880px; margin: 0 auto"
    >
      <div class="d-flex flex-wrap gap-2 mb-3">
        <!-- Region Dropdown -->
        <div class="dropdown flex-grow-1">
          <button
            class="btn btn-outline btn-primary dropdown-toggle w-100"
            type="button"
            data-bs-toggle="dropdown"
          >
            {{ selectedRegionTextMobile }}
          </button>
          <ul class="dropdown-menu" @click.stop>
            <li>
              <a
                class="dropdown-item"
                href="#"
                @click.prevent="clearSelection('regions')"
                >전체</a
              >
            </li>
            <li v-for="local in localOptions" :key="local.areaSq">
              <div class="dropdown-item">
                <input
                  type="checkbox"
                  :id="'region-mobile-' + local.areaSq"
                  :value="local.areaSq"
                  v-model="selectedRegions"
                  class="form-check-input me-2"
                />
                <label :for="'region-mobile-' + local.areaSq">{{
                  local.areaName
                }}</label>
              </div>
            </li>
          </ul>
        </div>

        <!-- Career Dropdown -->
        <div class="dropdown flex-grow-1">
          <button
            class="btn btn-outline btn-primary dropdown-toggle w-100"
            type="button"
            data-bs-toggle="dropdown"
          >
            {{ selectedCareerTextMobile }}
          </button>
          <ul class="dropdown-menu" @click.stop>
            <li>
              <a
                class="dropdown-item"
                href="#"
                @click.prevent="clearSelection('careers')"
                >전체</a
              >
            </li>
            <li v-for="career in careerOptions" :key="career.common_code_sq">
              <div class="dropdown-item">
                <input
                  type="checkbox"
                  :id="'career-mobile-' + career.common_code_sq"
                  :value="career.common_code_sq"
                  v-model="selectedCareers"
                  class="form-check-input me-2"
                />
                <label :for="'career-mobile-' + career.common_code_sq">{{
                  career.common_code_nm
                }}</label>
              </div>
            </li>
          </ul>
        </div>

        <!-- Education Dropdown -->
        <div class="dropdown flex-grow-1">
          <button
            class="btn btn-outline btn-primary dropdown-toggle w-100"
            type="button"
            data-bs-toggle="dropdown"
          >
            {{ selectedEducationTextMobile }}
          </button>
          <ul class="dropdown-menu" @click.stop>
            <li>
              <a
                class="dropdown-item"
                href="#"
                @click.prevent="clearSelection('educations')"
                >전체</a
              >
            </li>
            <li
              v-for="education in educationOptions"
              :key="education.common_code_sq"
            >
              <div class="dropdown-item">
                <input
                  type="checkbox"
                  :id="'education-mobile-' + education.common_code_sq"
                  :value="education.common_code_sq"
                  v-model="selectedEducations"
                  class="form-check-input me-2"
                />
                <label :for="'education-mobile-' + education.common_code_sq">{{
                  education.common_code_nm
                }}</label>
              </div>
            </li>
          </ul>
        </div>

        <!-- Job Type Dropdown -->
        <div class="dropdown flex-grow-1">
          <button
            class="btn btn-outline btn-primary dropdown-toggle w-100"
            type="button"
            data-bs-toggle="dropdown"
          >
            {{ selectedJobTypeTextMobile }}
          </button>
          <ul class="dropdown-menu" @click.stop>
            <li>
              <a
                class="dropdown-item"
                href="#"
                @click.prevent="clearSelection('jobTypes')"
                >전체</a
              >
            </li>
            <li v-for="job in jobTypeOptions" :key="job.common_code_sq">
              <div class="dropdown-item">
                <input
                  type="checkbox"
                  :id="'job-mobile-' + job.common_code_sq"
                  :value="job.common_code_sq"
                  v-model="selectedJobTypes"
                  class="form-check-input me-2"
                />
                <label :for="'job-mobile-' + job.common_code_sq">{{
                  job.common_code_nm
                }}</label>
              </div>
            </li>
          </ul>
        </div>
      </div>

      <div class="d-flex align-items-center gap-2">
        <!-- Search Input -->
        <div class="flex-grow-1">
          <input
            type="text"
            class="form-control"
            placeholder="검색어를 입력하세요..."
            v-model="searchKeyword"
          />
        </div>

        <!-- Search Type Dropdown -->
        <div class="dropdown">
          <button
            class="btn btn-outline btn-primary dropdown-toggle"
            type="button"
            data-bs-toggle="dropdown"
          >
            {{ selectedTargetField }}
          </button>
          <ul class="dropdown-menu">
            <li>
              <a
                class="dropdown-item"
                href="#"
                @click.prevent="updateTargetField('전체')"
                >전체</a
              >
            </li>
            <li>
              <a
                class="dropdown-item"
                href="#"
                @click.prevent="updateTargetField('제목')"
                >제목</a
              >
            </li>
            <li>
              <a
                class="dropdown-item"
                href="#"
                @click.prevent="updateTargetField('작성자명')"
                >작성자명</a
              >
            </li>
            <li>
              <a
                class="dropdown-item"
                href="#"
                @click.prevent="updateTargetField('내용')"
                >내용</a
              >
            </li>
            <li>
              <a
                class="dropdown-item"
                href="#"
                @click.prevent="updateTargetField('태그')"
                >태그</a
              >
            </li>
          </ul>
        </div>

        <!-- Sort Dropdown -->
        <div class="dropdown">
          <button
            class="btn btn-outline btn-primary dropdown-toggle"
            type="button"
            data-bs-toggle="dropdown"
          >
            {{ selectedSort }}
          </button>
          <ul class="dropdown-menu">
            <li>
              <a
                class="dropdown-item"
                href="#"
                @click.prevent="updateSort('최신순')"
                >최신순</a
              >
            </li>
            <li>
              <a
                class="dropdown-item"
                href="#"
                @click.prevent="updateSort('조회순')"
                >조회순</a
              >
            </li>
            <li>
              <a
                class="dropdown-item"
                href="#"
                @click.prevent="updateSort('지원자순')"
                >지원자순</a
              >
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, defineEmits, onMounted, computed, watch } from 'vue'
import { api } from '@/axios.js'
import { useRoute } from 'vue-router'

const emit = defineEmits(['update'])
const route = useRoute()

// Options from API
const localOptions = ref([])
const careerOptions = ref([])
const educationOptions = ref([])
const jobTypeOptions = ref([])

// Selected values (arrays for multi-select)
const selectedRegions = ref([])
const selectedCareers = ref([])
const selectedEducations = ref([])
const selectedJobTypes = ref([])

// Other filter values
const searchKeyword = ref('')
const selectedTargetField = ref('전체')
const selectedSort = ref('최신순')

// Computed properties for dropdown button text
const createSelectedText = (options, selectedIds, defaultText, keyMap) => {
  return computed(() => {
    if (selectedIds.value.length === 0) return `${defaultText} (전체)`
    if (selectedIds.value.length === 1) {
      const selected = options.value.find(
        (opt) => opt[keyMap.id] === selectedIds.value[0],
      )
      return selected ? selected[keyMap.name] : defaultText
    }
    return `${defaultText} (${selectedIds.value.length}개)`
  })
}

const selectedRegionText = createSelectedText(
  localOptions,
  selectedRegions,
  '지역',
  { id: 'areaSq', name: 'areaName' },
)
const selectedCareerText = createSelectedText(
  careerOptions,
  selectedCareers,
  '경력',
  { id: 'common_code_sq', name: 'common_code_nm' },
)
const selectedEducationText = createSelectedText(
  educationOptions,
  selectedEducations,
  '학력',
  { id: 'common_code_sq', name: 'common_code_nm' },
)
const selectedJobTypeText = createSelectedText(
  jobTypeOptions,
  selectedJobTypes,
  '직종',
  { id: 'common_code_sq', name: 'common_code_nm' },
)

const createSelectedTextMobile = (
  options,
  selectedIds,
  defaultText,
  keyMap,
) => {
  return computed(() => {
    if (selectedIds.value.length === 0) return defaultText
    if (selectedIds.value.length === 1) {
      const selected = options.value.find(
        (opt) => opt[keyMap.id] === selectedIds.value[0],
      )
      return selected ? selected[keyMap.name] : defaultText
    }
    return `${defaultText} (${selectedIds.value.length}개)`
  })
}

const selectedRegionTextMobile = createSelectedTextMobile(
  localOptions,
  selectedRegions,
  '지역',
  { id: 'areaSq', name: 'areaName' },
)
const selectedCareerTextMobile = createSelectedTextMobile(
  careerOptions,
  selectedCareers,
  '경력',
  { id: 'common_code_sq', name: 'common_code_nm' },
)
const selectedEducationTextMobile = createSelectedTextMobile(
  educationOptions,
  selectedEducations,
  '학력',
  { id: 'common_code_sq', name: 'common_code_nm' },
)
const selectedJobTypeTextMobile = createSelectedTextMobile(
  jobTypeOptions,
  selectedJobTypes,
  '직종',
  { id: 'common_code_sq', name: 'common_code_nm' },
)

// Fetch options from API
const basePath = route.path.includes('/affiliation')
  ? '/affiliations'
  : '/projects'
const fetchFilterOptions = async () => {
  try {
    const [regionRes, careerRes, educationRes, jobTypeRes] = await Promise.all([
      api.$get(`${basePath}/filters`, { params: { type: '지역' } }),
      api.$get(`${basePath}/filters`, { params: { type: '경력' } }),
      api.$get(`${basePath}/filters`, { params: { type: '학력' } }),
      api.$get(`${basePath}/filters`, { params: { type: '직종' } }),
    ])
    localOptions.value = regionRes.output
    careerOptions.value = careerRes.output
    educationOptions.value = educationRes.output
    jobTypeOptions.value = jobTypeRes.output
  } catch (e) {
    console.error('필터 데이터 불러오기 실패', e)
  }
}

onMounted(fetchFilterOptions)

// Watch for changes and emit update
watch(
  [
    selectedRegions,
    selectedCareers,
    selectedEducations,
    selectedJobTypes,
    searchKeyword,
    selectedTargetField,
    selectedSort,
  ],
  () => {
    const filters = {
      addressCodeSq: selectedRegions.value,
      projectDeveloperGradeCd: selectedCareers.value,
      educationCd: selectedEducations.value,
      jobRoleCd: selectedJobTypes.value,
      searchKeyword: searchKeyword.value,
      searchType: selectedTargetField.value,
    }
    if (selectedSort.value === '최신순') {
      filters.sortBy = 'project_start_dt'
      filters.sortOrder = 'desc'
    } else if (selectedSort.value === '조회순') {
      filters.sortBy = 'view_count'
      filters.sortOrder = 'desc'
    } else if (selectedSort.value === '지원자순') {
      filters.sortBy = 'applicant_count'
      filters.sortOrder = 'desc'
    }
    emit('update', filters)
  },
  { deep: true },
)

// Methods to handle selection from template
const updateTargetField = (value) => {
  selectedTargetField.value = value
}

const updateSort = (value) => {
  selectedSort.value = value
}

const clearSelection = (type) => {
  if (type === 'regions') selectedRegions.value = []
  if (type === 'careers') selectedCareers.value = []
  if (type === 'educations') selectedEducations.value = []
  if (type === 'jobTypes') selectedJobTypes.value = []
}
</script>

<style scoped></style>
