// frontend/react_js/components/myPage/personal/TrainingModal.js
import { useState } from 'react';
import { useModalStore } from '../../../store/modalStore';
import { useAlertStore } from '../../../store/alertStore';
import DatePicker from 'react-datepicker';
import 'react-datepicker/dist/react-datepicker.css';
import './TrainingModal.css';

const TrainingModal = ({ onComplete }) => {
  const modalStore = useModalStore();
  const alertStore = useAlertStore();

  const [form, setForm] = useState({
    trainingProgramNm: '',
    trainingInstitutionNm: '',
    trainingStartDt: null,
    trainingEndDt: null,
    period: '',
  });

  // 날짜 포맷팅 (YYYY.MM.DD)
  const formatDate = (date) => {
    if (!date) return '';
    
    if (date instanceof Date) {
      const year = date.getFullYear();
      const month = String(date.getMonth() + 1).padStart(2, '0');
      const day = String(date.getDate()).padStart(2, '0');
      return `${year}.${month}.${day}`;
    }
    
    return date.substring(0, 10).replace(/-/g, '.');
  };

  // API용 날짜 포맷팅 (YYYY-MM-DD)
  const formatDateForAPI = (date) => {
    if (!date) return '';
    
    if (date instanceof Date) {
      const year = date.getFullYear();
      const month = String(date.getMonth() + 1).padStart(2, '0');
      const day = String(date.getDate()).padStart(2, '0');
      return `${year}-${month}-${day}`;
    }
    
    return date;
  };

  // 제출
  const submit = () => {
    if (!form.trainingProgramNm) {
      alertStore.show('교육명을 입력해주세요.', 'danger');
      return;
    }
    if (!form.trainingInstitutionNm) {
      alertStore.show('교육 기관을 입력하세요.', 'danger');
      return;
    }
    if (!form.trainingStartDt) {
      alertStore.show('교육 기간을 선택하세요.', 'danger');
      return;
    }

    // 화면 표시용 기간 (YYYY.MM.DD ~ YYYY.MM.DD)
    const period = `${formatDate(form.trainingStartDt)} ~ ${formatDate(form.trainingEndDt)}`;

    // 부모에게 데이터 전달
    onComplete?.({
      trainingProgramNm: form.trainingProgramNm,
      trainingInstitutionNm: form.trainingInstitutionNm,
      trainingStartDt: formatDateForAPI(form.trainingStartDt),
      trainingEndDt: formatDateForAPI(form.trainingEndDt),
      period: period,
    });

    modalStore.closeModal();
  };

  return (
    <div className="modal-layer">
      <div className="modal-content">
        <div className="modal-header">
          <h4 className="modal-title">교육 이력 추가하기</h4>
          <button className="close-btn" onClick={() => modalStore.closeModal()}>
            ×
          </button>
        </div>

        <div className="modal-body">
          <div className="form-row">
            <div className="form-group">
              <label className="modal-label">교육명</label>
              <input
                value={form.trainingProgramNm}
                onChange={(e) =>
                  setForm((prev) => ({ ...prev, trainingProgramNm: e.target.value }))
                }
                type="text"
                className="form-control"
                placeholder="교육명"
              />
            </div>
            <div className="form-group">
              <label className="modal-label">교육 기관</label>
              <input
                value={form.trainingInstitutionNm}
                onChange={(e) =>
                  setForm((prev) => ({
                    ...prev,
                    trainingInstitutionNm: e.target.value,
                  }))
                }
                type="text"
                className="form-control"
                placeholder="교육 기관"
              />
            </div>
          </div>
          <div className="form-row">
            <div className="form-group position-group">
              <label className="modal-label">교육 기간</label>
              <div style={{ display: 'flex', gap: '8px' }}>
                <div className="datepicker-wrapper flex-grow-1">
                  <DatePicker
                    selected={form.trainingStartDt}
                    onChange={(date) =>
                      setForm((prev) => ({ ...prev, trainingStartDt: date }))
                    }
                    dateFormat="yyyy-MM-dd"
                    placeholderText="시작년월"
                    className="form-control"
                    showMonthYearPicker
                    showFullMonthYearPicker
                  />
                  <i className="fas fa-calendar datepicker-icon"></i>
                </div>
                <span style={{ alignSelf: 'center' }}>~</span>
                <div className="datepicker-wrapper flex-grow-1">
                  <DatePicker
                    selected={form.trainingEndDt}
                    onChange={(date) =>
                      setForm((prev) => ({ ...prev, trainingEndDt: date }))
                    }
                    dateFormat="yyyy-MM-dd"
                    placeholderText="종료년월"
                    className="form-control"
                    showMonthYearPicker
                    showFullMonthYearPicker
                  />
                  <i className="fas fa-calendar datepicker-icon"></i>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="modal-footer">
          <button className="btn btn-primary" onClick={submit}>
            저장하기
          </button>
          <button className="btn btn-light" onClick={() => modalStore.closeModal()}>
            닫기
          </button>
        </div>
      </div>
    </div>
  );
};

export default TrainingModal;

// frontend/vue_js/src/fo/components/mypage/personal/TrainingModal.vue
<template>
  <div class="modal-layer">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">교육 이력 추가하기</h4>
        <button class="close-btn" @click="modalStore.closeModal()">×</button>
      </div>

      <div class="modal-body">
        <div class="form-row">
          <div class="form-group">
            <label class="modal-label">교육명</label>
            <input
              v-model="form.trainingProgramNm"
              type="text"
              class="form-control"
              placeholder="교육명"
            />
          </div>
          <div class="form-group">
            <label class="modal-label">교육 기관</label>
            <input
              v-model="form.trainingInstitutionNm"
              type="text"
              class="form-control"
              placeholder="교육 기관"
            />
          </div>
        </div>
        <div class="form-row">
          <div class="form-group position-group">
            <label class="modal-label">교육 기간</label>
            <div style="display: flex; gap: 8px">
              <div class="datepicker-wrapper flex-grow-1">
                <Datepicker
                  :key="datepickerKey1"
                  v-model="form.trainingStartDt"
                  :locale="ko"
                  :inputFormat="inputFormat"
                  placeholder="시작년월"
                  class="form-control"
                  teleport="body"
                  dayPickerHeadingFormat="yyyy년 LLLL"
                  @update:modelValue="datepickerKey1++"
                />
                <i class="fas fa-calendar datepicker-icon"></i>
              </div>
              <span style="align-self: center">~</span>
              <div class="datepicker-wrapper flex-grow-1">
                <Datepicker
                  :key="datepickerKey2"
                  v-model="form.trainingEndDt"
                  :locale="ko"
                  :inputFormat="inputFormat"
                  placeholder="종료년월"
                  class="form-control"
                  teleport="body"
                  dayPickerHeadingFormat="yyyy년 LLLL"
                  @update:modelValue="datepickerKey2++"
                />
                <i class="fas fa-calendar datepicker-icon"></i>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="modal-footer">
        <button class="btn btn-primary" @click="submit">저장하기</button>
        <button class="btn btn-light" @click="modalStore.closeModal()">
          닫기
        </button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, defineProps } from 'vue'
import { useModalStore } from '@/fo/stores/modalStore'
import { useAlertStore } from '@/fo/stores/alertStore'
import Datepicker from 'vue3-datepicker'
import { ko } from 'date-fns/locale'

const props = defineProps({
  onComplete: Function, // 부모에서 내려주는 콜백함수
})
const modalStore = useModalStore()
const alertStore = useAlertStore()

const inputFormat = ref('yyyy-MM-dd')
const datepickerKey1 = ref(0)
const datepickerKey2 = ref(0)

const form = ref({
  trainingProgramNm: '',
  trainingInstitutionNm: '',
  trainingStartDt: '',
  trainingEndDt: '',
  period: '',
})

const submit = () => {
  if (!form.value.trainingProgramNm) {
    alertStore.show('교육명을 입력해주세요.', 'danger')
    return
  }
  if (!form.value.trainingInstitutionNm) {
    alertStore.show('교육 기관을 입력하세요.', 'danger')
    return
  }
  if (!form.value.trainingStartDt) {
    alertStore.show('교육 기간을 선택하세요.', 'danger')
    return
  }
  function formatDate(dateString) {
    // datepicker가 date객체를 반환한 경우 
    if (dateString instanceof Date) {
      const year = dateString.getFullYear()
      const month = String(dateString.getMonth() + 1).padStart(2, '0')
      const day = String(dateString.getDate()).padStart(2, '0')
      return `${year}.${month}.${day}`
    }

    if (typeof dateString === 'string') {
      return dateString.substring(0, 10).replace(/-/g, '.')
    }

    return ''
  }

  const toDateString = (dateString) => {
    if (!dateString) return ''
    if (dateString instanceof Date) {
      const year = dateString.getFullYear()
      const month = String(dateString.getMonth() + 1).padStart(2, '0')
      const day = String(dateString.getDate()).padStart(2, '0')
      return `${year}.${month}.${day}`
    }
    return dateString
  }

  form.value.period = `${formatDate(form.value.trainingStartDt)} ~ ${formatDate(form.value.trainingEndDt)}`
  // props.onComplete({ ...form.value }) // 부모에게 데이터 전달
  props.onComplete({
    trainingProgramNm: form.value.trainingProgramNm,
    trainingInstitutionNm: form.value.trainingInstitutionNm,
    trainingStartDt: toDateString(form.value.trainingStartDt),
    trainingEndDt: toDateString(form.value.trainingEndDt),
    period: form.value.period,
  })
  modalStore.closeModal()
}
</script>

<style scoped>
.modal-layer {
  position: fixed;
  top: 0;
  left: 0;
  z-index: 9999;
  width: 100vw;
  height: 100vh;
  background: rgba(0, 0, 0, 0.4);
  display: flex;
  align-items: center;
  justify-content: center;
}
.modal-content {
  position: relative;
  width: 540px;
  max-width: 95vw;
  background: #fff;
  padding: 28px 20px 16px 20px;
  overflow-x: visible;
  overflow-y: visible;
  box-sizing: border-box;
  border-radius: 8px;
}
.modal-header {
  height: 40px;
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  padding-bottom: 4px;
  padding-top: 0;
}
.modal-title {
  color: #222;
  font-size: 1.2rem;
  font-weight: bold;
  margin-top: 0;
  margin-bottom: 0;
}
.close-btn {
  background: transparent;
  border: none;
  font-size: 1.8rem;
  cursor: pointer;
  display: block;
  line-height: 1;
  padding: 0 8px;
  color: #888;
  position: relative;
  top: -6px;
}
.modal-label {
  color: #222;
  font-size: 1rem;
  font-weight: 500;
  margin-bottom: 4px;
  display: inline-block;
}
.modal-body .form-group {
  margin-bottom: 0;
}
.form-row {
  display: flex;
  gap: 16px;
  margin-bottom: 16px;
}
.form-row .form-group {
  flex: 1 1 0;
}

.form-control {
  width: 100%;
  padding: 8px;
  box-sizing: border-box;
}
.modal-footer {
  display: flex;
  justify-content: flex-end;
  gap: 8px;
  margin-top: 20px;
}

.datepicker-wrapper {
  position: relative;
  --vdp-hover-bg-color: #007bff;
  --vdp-selected-bg-color: #007bff;
  --vdp-hover-color: #ffffff;
  --vdp-selected-color: #ffffff;
}

.datepicker-wrapper :deep(.form-control) {
  padding-right: 3rem; /* 아이콘 공간 확보 */
  height: auto;
  padding-top: 8px;
  padding-bottom: 8px;
}

.datepicker-icon {
  position: absolute;
  top: 50%;
  right: 1rem;
  transform: translateY(-50%);
  color: #adb5bd;
  pointer-events: none;
}
</style>
