// frontend/vue_js/src/fo/components/login&signup/CompanySignUpForm.vue
<template>
  <form @submit.prevent="validateAll">
    <!-- 아이디 -->
    <div class="row">
      <div class="form-group col-lg-6">
        <label class="form-label"
          >아이디<i
            v-if="idValid"
            class="bi bi-check-circle-fill ms-1"
            style="color: #007bff"
          ></i
        ></label>
        <input
          type="text"
          v-model="form.id"
          id="signup-id"
          class="form-control form-control-lg"
          @input="onIdInput"
        />
        <div v-if="idError" class="invalid-feedback">{{ idError }}</div>
      </div>
    </div>

    <!-- 비밀번호 -->
    <div class="row">
      <div class="form-group col-lg-6">
        <label class="form-label"
          >비밀번호
          <i
            v-if="passwordValid"
            class="bi bi-check-circle-fill ms-1"
            style="color: #007bff"
          ></i
        ></label>
        <input
          type="password"
          v-model="form.password"
          id="signup-password"
          class="form-control form-control-lg"
          @input="validatePassword"
        />
        <div v-if="passwordError" class="invalid-feedback">
          {{ passwordError }}
        </div>
      </div>
      <div class="form-group col-lg-6">
        <label class="form-label">
          비밀번호 확인
          <i
            v-if="confirmPasswordValid"
            class="bi bi-check-circle-fill ms-1"
            style="color: #007bff"
          ></i>
        </label>
        <input
          type="password"
          v-model="form.confirmPassword"
          id="signup-confirmPassword"
          class="form-control form-control-lg"
          @input="passwordValid ? validateConfirmPassword() : ''"
        />
        <div v-if="confirmPasswordError" class="invalid-feedback">
          {{ confirmPasswordError }}
        </div>
      </div>
    </div>

    <!-- 담당자 이름 -->
    <div class="row">
      <div class="form-group col-lg-6">
        <label class="form-label"
          >담당자 이름
          <i
            v-if="nameValid"
            class="bi bi-check-circle-fill ms-1"
            style="color: #007bff"
          ></i
        ></label>
        <input
          type="text"
          v-model="form.name"
          id="signup-name"
          class="form-control form-control-lg"
          @input="validateName"
        />
        <div v-if="nameError" class="invalid-feedback">{{ nameError }}</div>
      </div>
    </div>

    <!-- 휴대폰 -->
    <div class="row">
      <div class="form-group col-lg-6">
        <label class="form-label"
          >휴대폰 번호
          <i
            v-if="phoneValid"
            class="bi bi-check-circle-fill ms-1"
            style="color: #007bff"
          ></i
        ></label>
        <input
          type="text"
          v-model="form.phone"
          id="signup-phone"
          class="form-control form-control-lg"
          @input="validatePhone"
        />
        <div v-if="phoneError" class="invalid-feedback">{{ phoneError }}</div>
      </div>
    </div>

    <!-- 기업명 -->
    <div class="row">
      <div class="form-group col-lg-6">
        <label class="form-label"
          >기업명
          <i
            v-if="companyValid"
            class="bi bi-check-circle-fill ms-1"
            style="color: #007bff"
          ></i
        ></label>
        <input
          type="text"
          v-model="form.companyName"
          id="signup-companyName"
          class="form-control form-control-lg"
          @change="validateCompany"
        />
      </div>
      <div v-if="companyError" class="invalid-feedback">{{ companyError }}</div>
    </div>

    <!-- 회사 주소 -->
    <div class="row">
      <div class="form-group col-lg-7 mb-2">
        <label class="form-label"
          >회사 주소
          <i
            v-if="addressValid"
            class="bi bi-check-circle-fill ms-1"
            style="color: #007bff"
          ></i
        ></label>
        <input
          type="text"
          v-model="form.address"
          id="signup-address"
          class="form-control form-control-lg"
          placeholder="주소를 검색하세요"
          readonly
          @click="openPostcode"
          @input="validateAddress"
        />
        <div v-if="addressError" class="invalid-feedback">
          {{ addressError }}
        </div>
      </div>

      <div class="form-group col-lg-5">
        <label class="form-label">상세 주소</label>
        <input
          type="text"
          v-model="form.addressDetail"
          class="form-control form-control-lg"
          placeholder=""
        />
      </div>
    </div>

    <!-- 이메일 -->
    <div class="row">
      <div class="form-group col-lg-12">
        <label class="form-label"
          >이메일 주소
          <i
            v-if="emailValid"
            class="bi bi-check-circle-fill ms-1"
            style="color: #007bff"
          ></i
        ></label>
        <div class="input-group">
          <input
            type="text"
            v-model="form.emailId"
            id="signup-emailId"
            class="form-control form-control-lg"
            @input="validateEmail"
            placeholder="이메일 아이디"
          />
          <span class="input-group-text">@</span>

          <!-- 도메인 입력 인풋 -->
          <input
            type="text"
            v-model="form.emailDomain"
            :readonly="!isCustomDomain"
            class="form-control form-control-lg"
            @input="validateEmail"
            placeholder="도메인 입력"
          />

          <!-- 셀렉트 박스 -->
          <select
            v-model="selectedDomain"
            @change="handleDomainChange"
            class="form-control form-control-lg"
          >
            <option value="custom">직접입력</option>
            <option value="naver.com">naver.com</option>
            <option value="gmail.com">gmail.com</option>
            <option value="daum.net">daum.net</option>
            <option value="nate.com">nate.com</option>
            <option value="hotmail.com">hotmail.com</option>
          </select>

          <button
            type="button"
            class="btn btn-primary btn-lg"
            @click="sendVerification"
          >
            인증 요청
          </button>
        </div>
        <div v-if="emailError" class="invalid-feedback">{{ emailError }}</div>
      </div>
    </div>

    <!-- 인증번호 -->
    <div class="row">
      <div class="form-group col-lg-8">
        <label class="form-label"
          >인증번호
          <i
            v-if="verifyCodeValid"
            class="bi bi-check-circle-fill ms-1"
            style="color: #007bff"
          ></i
        ></label>
        <div class="input-group">
          <input
            type="text"
            v-model="form.verificationCode"
            id="signup-verificationCode"
            class="form-control form-control-lg"
            @input="validateVerifycode"
          />
          <button
            type="button"
            class="btn btn-primary btn-lg"
            @click="verifyCode"
          >
            확인
          </button>
        </div>
        <div v-if="verifycodeError" class="invalid-feedback">
          {{ verifycodeError }}
        </div>
      </div>
    </div>

    <!-- 약관 동의 -->
    <div class="row">
      <div class="form-group col">
        <div class="form-check">
          <input
            type="checkbox"
            v-model="form.terms"
            id="terms"
            class="form-check-input"
            @change="validateTerms"
          />
          <label for="terms" class="form-check-label me-1">
            약관에 동의합니다.
          </label>
          <a class="font-primary" @click="openTermsModal">이용약관</a>
        </div>
        <div v-if="termsError" class="invalid-feedback">{{ termsError }}</div>
      </div>
    </div>

    <!-- 회원가입 버튼 -->
    <div class="row">
      <div class="form-group col text-6">
        <input
          type="submit"
          value="회원가입"
          class="btn btn-primary btn-modern w-100"
        />
      </div>
    </div>
  </form>
</template>

<script setup>
import { reactive, ref, onMounted, defineEmits, watch } from 'vue'
import { useModalStore } from '@/fo/stores/modalStore'
import { personalAgreementText } from '@/assets/terms'
import TermsAgreementModal from '@/fo/components/login&signup/TermsAgreementModal.vue'
import { useAlertStore } from '@/fo/stores/alertStore'
import { api } from '@/axios'
import { debounce } from 'lodash'

const emit = defineEmits(['submit'])

const validateAll = async () => {
  await validateIdCore(form.id)
  validatePassword()
  validateConfirmPassword()
  validateName()
  validateCompany()
  validatePhone()
  validateAddress()
  validateEmail()
  validateVerifycode()
  validateTerms()

  //유효성 검사 항목 위에서부터 순서대로 체크
  const validationItems = [
    { valid: idValid.value, error: idError.value, id: 'signup-id' },
    {
      valid: passwordValid.value,
      error: passwordError.value,
      id: 'signup-password',
    },
    {
      valid: confirmPasswordValid.value,
      error: confirmPasswordError.value,
      id: 'signup-confirmPassword',
    },
    { valid: nameValid.value, error: nameError.value, id: 'signup-name' },
    { valid: phoneValid.value, error: phoneError.value, id: 'signup-phone' },
    {
      valid: companyValid.value,
      error: companyError.value,
      id: 'signup-companyName',
    },
    {
      valid: addressValid.value,
      error: addressError.value,
      id: 'signup-address',
    },
    { valid: emailValid.value, error: emailError.value, id: 'signup-emailId' },
    {
      valid: !!verifyCodeValid.value,
      error: verifycodeError.value,
      id: 'signup-verificationCode',
    },
    { valid: termsValid.value, error: termsError.value, id: 'terms' },
  ]

  const firstError = validationItems.find((item) => !item.valid)

  if (firstError) {
    alertStore.show(firstError.error || '입력 정보를 확인해주세요.', 'danger')
    //해당 위치로 이동 및 포커스
    const element = document.getElementById(firstError.id)
    if (element) {
      element.scrollIntoView({ behavior: 'smooth', block: 'center' })
      element.focus()
    }
  } else {
    emit('submit', { ...form })
  }
}

const form = reactive({
  id: '',
  password: '',
  confirmPassword: '',
  name: '',
  phone: '',
  emailId: '',
  emailDomain: '',
  verificationCode: '',
  terms: false,
  companyName: '',
  companyCeoName: null,
  companyBizNumber: null,
  companyOpenDate: null,
  sigunguCode: '',
  address: '',
  addressDetail: '',
  latitude: '',
  longitude: '',
  typeCode: 302, // 기업
  signupTypeCode: 204, // 이메일
})

const modalStore = useModalStore()
const alertStore = useAlertStore()

const selectedDomain = ref('custom')
const isCustomDomain = ref(true)

function handleDomainChange() {
  if (selectedDomain.value === 'custom') {
    form.emailDomain = ''
    isCustomDomain.value = true
  } else {
    form.emailDomain = selectedDomain.value
    isCustomDomain.value = false
  }

  validateEmail()
}

const sendVerification = async () => {
  const email = `${form.emailId}@${form.emailDomain}`

  try {
    // const response =
    await api.$post('/email/send-code', { email })
    // console.log('인증 이메일 전송 완료', response)
    // alertStore.show(
    //   '인증 코드를 전송했습니다. 인증 코드 : ' + response.output.code,
    //   'info',
    // )
    alertStore.show('인증 코드를 전송했습니다. ', 'info')
  } catch (error) {
    console.error('이메일 인증 요청 실패:', error)

    // 백엔드가 보내준 에러 메시지 꺼내기 (API 응답 구조에 따라 조정)
    const message =
      error.response?.data?.message || '이메일 인증 요청에 실패했습니다.'
    emailValid.value = false
    emailError.value = message
  }
}

// 인증 코드 확인 함수 (개선 버전)
const verifyCode = async () => {
  verifycodeError.value = ''
  verifyCodeValid.value = false

  const email = `${form.emailId}@${form.emailDomain}`
  const code = form.verificationCode

  if (!code) {
    verifycodeError.value = '인증번호를 입력하세요.'
    return
  }

  try {
    // const response =
    await api.$post('/email/verify-code', { email, code })
    // console.log('인증 성공', response)
    alertStore.show('이메일 인증에 성공하였습니다.', 'info')
    verifyCodeValid.value = true
  } catch (error) {
    console.error('인증 코드 검증 실패:', error)
    verifycodeError.value = '인증번호가 일치하지 않습니다.'
    alertStore.show('이메일 인증에 실패하였습니다.', 'danger')
    verifyCodeValid.value = false
  }
}
const idError = ref('')
const passwordError = ref('')
const confirmPasswordError = ref('')
const nameError = ref('')
const phoneError = ref('')
const companyError = ref('')
const addressError = ref('')
const emailError = ref('')
const verifycodeError = ref('')
const termsError = ref('')

const idValid = ref(false)
const passwordValid = ref(false)
const confirmPasswordValid = ref(false)
const nameValid = ref(false)
const phoneValid = ref(false)
const companyValid = ref(false)
const addressValid = ref(false)
const emailValid = ref(false)
const verifyCodeValid = ref('')
const termsValid = ref(false)

// 1. 실제 유효성 검사 + API 호출 함수 (비동기)
const validateIdCore = async (id) => {
  idError.value = ''
  idValid.value = false

  if (!id) {
    idError.value = '아이디를 입력해주세요.'
    return
  }
  if (!/^[a-zA-Z0-9]{5,20}$/.test(id)) {
    idError.value = '영문 또는 숫자 5~20자로 입력해주세요.'
    return
  }

  try {
    const res = await api.$get(`/check-id?userId=${id}`)
    if (res) {
      idError.value = '이미 사용 중인 아이디입니다.'
      idValid.value = false
    } else {
      idValid.value = true
    }
  } catch (e) {
    idError.value = '서버 오류가 발생했습니다.'
    idValid.value = false
  }
}

// 2. 디바운스 적용 함수
const validateId = debounce((id) => {
  validateIdCore(id)
}, 500) // 500ms 딜레이

// 3. input 이벤트 핸들러 (v-model과 함께)
const onIdInput = (e) => {
  const id = e.target.value
  validateId(id)
}

// 비밀번호 유효성 검사
const validatePassword = () => {
  passwordError.value = ''
  passwordValid.value = false
  if (!form.password) {
    passwordError.value = '비밀번호를 입력해주세요.'
  } else if (
    !/^(?=.*[A-Za-z])(?=.*\d)(?=.*[!@#$%^&*]).{8,}$/.test(form.password)
  ) {
    passwordError.value = '8자 이상, 영문·숫자·특수문자를 조합해 입력해주세요.'
  } else {
    passwordValid.value = true
  }
}

// 비밀번호 확인 유효성 검사
const validateConfirmPassword = () => {
  confirmPasswordError.value = ''
  confirmPasswordValid.value = false
  if (!form.confirmPassword) {
    confirmPasswordError.value = '비밀번호 확인을 입력해주세요.'
  } else if (form.confirmPassword !== form.password) {
    confirmPasswordError.value = '비밀번호가 일치하지 않습니다.'
  } else {
    confirmPasswordValid.value = true
  }
}

// 담당자 이름 유효성 검사
const validateName = () => {
  nameError.value = ''
  nameValid.value = false
  if (!form.name) {
    nameError.value = '이름을 입력해주세요.'
  } else if (form.name.length < 2) {
    nameError.value = '이름은 두 글자 이상 입력해주세요.'
  } else {
    nameValid.value = true
  }
}

// 휴대폰 번호 유효성 검사
const validatePhone = () => {
  phoneError.value = ''
  phoneValid.value = false
  if (!form.phone) {
    phoneError.value = '휴대폰 번호를 입력해주세요.'
  } else if (!/^\d{10,11}$/.test(form.phone)) {
    phoneError.value = '올바른 휴대폰 번호 형식이 아닙니다. (하이픈 제외)'
  } else {
    phoneValid.value = true
  }
}

// 기업명&사업자번호 유효성 검사
const validateCompany = () => {
  companyError.value = ''
  companyValid.value = false
  if (!form.companyName) {
    companyError.value = '기업 인증을 진행해주세요.'
  } else {
    companyValid.value = true
  }
}

// 다음 주소 API
function openPostcode() {
  new window.daum.Postcode({
    oncomplete: function (data) {
      let addr = ''
      if (data.userSelectedType === 'R') {
        addr = data.roadAddress
      } else {
        addr = data.jibunAddress
      }

      form.postcode = data.zonecode
      form.address = addr
      form.detailAddress = ''

      // 시군구 추출
      form.sigunguCode = data.sigunguCode

      // 주소 → 좌표 변환
      const geocoder = new window.kakao.maps.services.Geocoder()
      geocoder.addressSearch(addr, function (result, status) {
        if (status === window.kakao.maps.services.Status.OK) {
          form.latitude = result[0].y
          form.longitude = result[0].x
        } else {
          form.latitude = null
          form.longitude = null
        }
      })
    },
  }).open()
}

onMounted(() => {
  // 1. Daum 우편번호 API 확인
  if (!window.daum) {
    console.warn('❌ Daum 우편번호 API (postcode.v2.js)가 로드되지 않았습니다.')
  } else {
    // console.log('✅ Daum 우편번호 API 로드됨')
  }

  // 2. Kakao 지도 API 확인 및 동적 로드
  if (!window.kakao || !window.kakao.maps) {
    console.warn(
      '❌ Kakao 지도 API가 로드되지 않았습니다. 스크립트를 동적으로 추가합니다.',
    )

    const kakaoScript = document.createElement('script')
    kakaoScript.src =
      'https://dapi.kakao.com/v2/maps/sdk.js?appkey=90610faa13d02b09f83a700d0885a872&libraries=services'
    kakaoScript.async = true

    // console.log('📦 Kakao 지도 API 스크립트를 추가합니다:', kakaoScript.src)

    kakaoScript.onload = () => {
      // console.log('✅ Kakao 지도 API 스크립트 onload 실행됨')
      if (window.kakao && window.kakao.maps) {
        // console.log('✅ Kakao 지도 API가 동적으로 로드되었습니다.')
      } else {
        console.error(
          '❌ Kakao 지도 API 로드 실패: maps 객체가 여전히 존재하지 않습니다.',
        )
      }
    }

    kakaoScript.onerror = () => {
      console.error('❌ Kakao 지도 API 스크립트 로드 실패')
    }

    document.head.appendChild(kakaoScript)
  } else {
    // console.log('✅ Kakao 지도 API가 이미 로드되어 있습니다.')
  }
})

// 주소 유효성 검사
const validateAddress = () => {
  addressError.value = ''
  addressValid.value = false
  if (!form.address) {
    addressError.value = '주소를 입력해주세요.'
  } else {
    addressValid.value = true
  }
}

watch(() => form.address, validateAddress)

// 이메일 주소 유효성 검사
const validateEmail = () => {
  emailError.value = ''
  emailValid.value = false

  // 이메일 아이디와 도메인 결합
  const fullEmail =
    form.emailId +
    '@' +
    (isCustomDomain.value ? form.emailDomain : selectedDomain.value)

  // 이메일 아이디가 없거나, 이메일 도메인이 없을 경우
  if (!form.emailId) {
    emailError.value = '이메일 아이디를 입력해주세요.'
  } else if (isCustomDomain.value && !form.emailDomain) {
    emailError.value = '도메인을 입력해주세요.'
  }
  // 이메일 형식 검사
  else if (!/\S+@\S+\.\S+/.test(fullEmail)) {
    emailError.value = '올바른 이메일 주소 형식이 아닙니다.'
  } else {
    emailValid.value = true
  }
}

const validateVerifycode = () => {
  verifycodeError.value = ''
  if (!form.verificationCode) {
    verifycodeError.value = '인증번호를 입력하세요.'
  } else if (!verifyCodeValid.value) {
    verifycodeError.value = '인증을 진행해주세요.'
  }
  // 인증번호 유효성 여부는 서버 검증 결과에 따라 판단 → 여기서는 설정하지 않음
}

// 약관 동의 유효성 검사
const validateTerms = () => {
  termsError.value = ''
  termsValid.value = false
  if (!form.terms) {
    termsError.value = '필수 약관에 동의해주세요.'
  } else {
    termsValid.value = true
  }
}

// 약관 모달을 열기 위한 함수
function openTermsModal() {
  modalStore.openModal(TermsAgreementModal, {
    title: '개인정보 수집 및 이용 동의서',
    body: personalAgreementText,
    onConfirm: () => {
      alertStore.show('약관 동의 처리되었습니다.', 'success')
      form.terms = true
      modalStore.closeModal()
    },
  })
}
</script>
<style scoped>
select.form-control,
select.form-control-lg {
  line-height: 1.6;
  padding-top: 0.5rem;
  padding-bottom: 0.5rem;
  height: auto;
}

.invalid-feedback {
  color: #007bff;
  display: block;
}
</style>

// frontend/nextjs/components/auth/CompanySignUpForm.tsx
'use client'
// Mirrors vue_js/src/fo/components/login&signup/CompanySignUpForm.vue
// Personal 폼과 구조 동일, 생년월일/성별 제거 + 기업 정보 추가
import { useCallback, useRef, useState } from 'react'
import Script from 'next/script'
import { CheckCircle2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Checkbox } from '@/components/ui/checkbox'
import { useEmailVerification } from '@/hooks/useEmailVerification'
import { alertStore } from '@/stores/alertStore'
import api from '@/lib/api'
import { DaumPostcodeResult } from '@/types'

const EMAIL_DOMAINS = ['naver.com', 'gmail.com', 'daum.net', 'nate.com', 'hotmail.com']

interface Props {
  onSubmit: (data: Record<string, unknown>) => void
}

function useField(initialValue = '') {
  const [value, setValue] = useState(initialValue)
  const [error, setError] = useState('')
  const [valid, setValid] = useState(false)
  return { value, setValue, error, setError, valid, setValid }
}

export default function CompanySignUpForm({ onSubmit }: Props) {
  const idField = useField()
  const pwField = useField()
  const cpwField = useField()
  const nameField = useField()      // 담당자 이름
  const phoneField = useField()
  const companyNameField = useField()
  const ceoNameField = useField()
  const bizNumField = useField()
  const openDateField = useField()
  const addressField = useField()
  const [addressDetail, setAddressDetail] = useState('')
  const [postcode, setPostcode] = useState('')
  const [sigunguCode, setSigunguCode] = useState('')
  const [latitude, setLatitude] = useState('')
  const [longitude, setLongitude] = useState('')
  const emailIdField = useField()
  const [emailDomain, setEmailDomain] = useState('')
  const [customDomain, setCustomDomain] = useState('')
  const [isCustomDomain, setIsCustomDomain] = useState(false)
  const [verifyCode, setVerifyCode] = useState('')
  const [verifyError, setVerifyError] = useState('')
  const [terms, setTerms] = useState(false)
  const [termsError, setTermsError] = useState('')
  const idDebounce = useRef<ReturnType<typeof setTimeout> | null>(null)

  const emailVerify = useEmailVerification({ sendCodeEndpoint: '/email/send-code' })
  const fullEmail = () => `${emailIdField.value}@${isCustomDomain ? customDomain : emailDomain}`

  const validateId = useCallback(async (val: string) => {
    idField.setError(''); idField.setValid(false)
    if (!val) { idField.setError('아이디를 입력해주세요.'); return }
    if (!/^[a-zA-Z0-9]{5,20}$/.test(val)) { idField.setError('영문 또는 숫자 5~20자로 입력해주세요.'); return }
    try {
      const { data } = await api.get<boolean>(`/check-id?userId=${val}`)
      if (data) idField.setError('이미 사용 중인 아이디입니다.')
      else idField.setValid(true)
    } catch { idField.setError('서버 오류가 발생했습니다.') }
  }, [idField])

  const onIdChange = (val: string) => {
    idField.setValue(val)
    if (idDebounce.current) clearTimeout(idDebounce.current)
    idDebounce.current = setTimeout(() => validateId(val), 500)
  }

  const validatePw = () => {
    pwField.setError(''); pwField.setValid(false)
    if (!pwField.value) { pwField.setError('비밀번호를 입력해주세요.'); return }
    if (!/^(?=.*[A-Za-z])(?=.*\d)(?=.*[!@#$%^&*]).{8,}$/.test(pwField.value)) {
      pwField.setError('8자 이상, 영문·숫자·특수문자를 조합해 입력해주세요.'); return
    }
    pwField.setValid(true)
  }

  const validateCpw = () => {
    cpwField.setError(''); cpwField.setValid(false)
    if (!cpwField.value) { cpwField.setError('비밀번호 확인을 입력해주세요.'); return }
    if (cpwField.value !== pwField.value) { cpwField.setError('비밀번호가 일치하지 않습니다.'); return }
    cpwField.setValid(true)
  }

  const req = (field: ReturnType<typeof useField>, msg: string) => {
    field.setError(''); field.setValid(false)
    if (!field.value) { field.setError(msg); return false }
    field.setValid(true); return true
  }

  const validatePhone = () => {
    phoneField.setError(''); phoneField.setValid(false)
    if (!phoneField.value) { phoneField.setError('휴대폰 번호를 입력해주세요.'); return }
    if (!/^\d{10,11}$/.test(phoneField.value)) { phoneField.setError('올바른 휴대폰 번호 형식이 아닙니다. (하이픈 제외)'); return }
    phoneField.setValid(true)
  }

  const validateEmail = () => {
    emailIdField.setError(''); emailIdField.setValid(false)
    const email = fullEmail()
    if (!emailIdField.value) { emailIdField.setError('이메일 아이디를 입력해주세요.'); return }
    if (isCustomDomain && !customDomain) { emailIdField.setError('도메인을 입력해주세요.'); return }
    if (!/\S+@\S+\.\S+/.test(email)) { emailIdField.setError('올바른 이메일 주소 형식이 아닙니다.'); return }
    emailIdField.setValid(true)
  }

  const openPostcode = () => {
    if (!window.daum) return
    new window.daum.Postcode({
      oncomplete: (data: DaumPostcodeResult) => {
        const addr = data.userSelectedType === 'R' ? data.roadAddress : data.jibunAddress
        setPostcode(data.zonecode)
        addressField.setValue(addr); addressField.setError(''); addressField.setValid(true)
        setSigunguCode(data.sigunguCode); setAddressDetail('')
        if (window.kakao?.maps) {
          new window.kakao.maps.services.Geocoder().addressSearch(addr, (result, status) => {
            if (status === window.kakao.maps.services.Status.OK) {
              setLatitude(result[0].y); setLongitude(result[0].x)
            }
          })
        }
      },
    }).open()
  }

  const handleDomainChange = (val: string) => {
    if (val === 'custom') { setIsCustomDomain(true); setCustomDomain(''); setEmailDomain('custom') }
    else { setIsCustomDomain(false); setEmailDomain(val) }
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    await validateId(idField.value)
    validatePw(); validateCpw()
    req(nameField, '담당자 이름을 입력해주세요.')
    validatePhone()
    req(companyNameField, '기업명을 입력해주세요.')
    req(ceoNameField, '대표자 이름을 입력해주세요.')
    req(bizNumField, '사업자 번호를 입력해주세요.')
    req(openDateField, '개업일을 입력해주세요.')
    req(addressField, '주소를 입력해주세요.')
    validateEmail()
    const vcOk = emailVerify.verified || (setVerifyError('인증을 완료해주세요.'), false)
    const tOk = terms || (setTermsError('필수 약관에 동의해주세요.'), false)

    const allValid =
      idField.valid && pwField.valid && cpwField.valid && nameField.valid &&
      phoneField.valid && companyNameField.valid && ceoNameField.valid &&
      bizNumField.valid && openDateField.valid && addressField.valid &&
      emailIdField.valid && vcOk && tOk

    if (!allValid) { alertStore.show('입력 정보를 확인해주세요.', 'danger'); return }

    onSubmit({
      id: idField.value, password: pwField.value, name: nameField.value,
      phone: phoneField.value, companyName: companyNameField.value,
      companyCeoName: ceoNameField.value, companyBizNumber: bizNumField.value,
      companyOpenDate: openDateField.value, address: addressField.value,
      addressDetail, postcode, sigunguCode, latitude, longitude,
      emailId: emailIdField.value,
      emailDomain: isCustomDomain ? customDomain : emailDomain,
      terms, typeCode: 302, signupTypeCode: 204,
    })
  }

  const FieldLabel = ({ label, valid }: { label: string; valid: boolean }) => (
    <label className="mb-1 flex items-center gap-1 text-sm font-medium">
      {label} {valid && <CheckCircle2 className="h-3.5 w-3.5 text-primary" />}
    </label>
  )
  const ErrorMsg = ({ msg }: { msg: string }) =>
    msg ? <p className="mt-1 text-xs text-destructive">{msg}</p> : null

  return (
    <>
      <Script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js" strategy="lazyOnload" />
      <form onSubmit={handleSubmit} className="space-y-4">
        <div>
          <FieldLabel label="아이디" valid={idField.valid} />
          <Input value={idField.value} onChange={(e) => onIdChange(e.target.value)} placeholder="영문·숫자 5~20자" />
          <ErrorMsg msg={idField.error} />
        </div>

        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          <div>
            <FieldLabel label="비밀번호" valid={pwField.valid} />
            <Input type="password" value={pwField.value} onChange={(e) => pwField.setValue(e.target.value)} onBlur={validatePw} />
            <ErrorMsg msg={pwField.error} />
          </div>
          <div>
            <FieldLabel label="비밀번호 확인" valid={cpwField.valid} />
            <Input type="password" value={cpwField.value} onChange={(e) => cpwField.setValue(e.target.value)} onBlur={validateCpw} />
            <ErrorMsg msg={cpwField.error} />
          </div>
        </div>

        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          <div>
            <FieldLabel label="담당자 이름" valid={nameField.valid} />
            <Input value={nameField.value} onChange={(e) => nameField.setValue(e.target.value)} onBlur={() => req(nameField, '담당자 이름을 입력해주세요.')} />
            <ErrorMsg msg={nameField.error} />
          </div>
          <div>
            <FieldLabel label="휴대폰 번호" valid={phoneField.valid} />
            <Input value={phoneField.value} onChange={(e) => phoneField.setValue(e.target.value)} onBlur={validatePhone} placeholder="하이픈 제외" />
            <ErrorMsg msg={phoneField.error} />
          </div>
        </div>

        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          <div>
            <FieldLabel label="기업명" valid={companyNameField.valid} />
            <Input value={companyNameField.value} onChange={(e) => companyNameField.setValue(e.target.value)} onBlur={() => req(companyNameField, '기업명을 입력해주세요.')} />
            <ErrorMsg msg={companyNameField.error} />
          </div>
          <div>
            <FieldLabel label="대표자 이름" valid={ceoNameField.valid} />
            <Input value={ceoNameField.value} onChange={(e) => ceoNameField.setValue(e.target.value)} onBlur={() => req(ceoNameField, '대표자 이름을 입력해주세요.')} />
            <ErrorMsg msg={ceoNameField.error} />
          </div>
        </div>

        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          <div>
            <FieldLabel label="사업자 번호" valid={bizNumField.valid} />
            <Input value={bizNumField.value} onChange={(e) => bizNumField.setValue(e.target.value)} onBlur={() => req(bizNumField, '사업자 번호를 입력해주세요.')} placeholder="숫자만" />
            <ErrorMsg msg={bizNumField.error} />
          </div>
          <div>
            <FieldLabel label="개업일" valid={openDateField.valid} />
            <Input type="date" value={openDateField.value} onChange={(e) => openDateField.setValue(e.target.value)} onBlur={() => req(openDateField, '개업일을 입력해주세요.')} max={new Date().toISOString().split('T')[0]} />
            <ErrorMsg msg={openDateField.error} />
          </div>
        </div>

        <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
          <div>
            <FieldLabel label="주소" valid={addressField.valid} />
            <Input value={addressField.value} readOnly onClick={openPostcode} placeholder="클릭하여 검색" className="cursor-pointer" />
            <ErrorMsg msg={addressField.error} />
          </div>
          <div>
            <label className="mb-1 block text-sm font-medium">상세 주소</label>
            <Input value={addressDetail} onChange={(e) => setAddressDetail(e.target.value)} />
          </div>
        </div>

        <div>
          <FieldLabel label="이메일 주소" valid={emailIdField.valid} />
          <div className="flex flex-wrap gap-1">
            <Input className="w-28 min-w-0 flex-1" value={emailIdField.value} onChange={(e) => emailIdField.setValue(e.target.value)} onBlur={validateEmail} placeholder="아이디" />
            <span className="flex items-center px-1 text-sm">@</span>
            <Input className="w-28 min-w-0 flex-1" value={isCustomDomain ? customDomain : emailDomain} readOnly={!isCustomDomain} onChange={(e) => setCustomDomain(e.target.value)} placeholder="도메인" />
            <select value={isCustomDomain ? 'custom' : emailDomain} onChange={(e) => handleDomainChange(e.target.value)} className="h-8 rounded-lg border border-border bg-background px-2 text-sm">
              <option value="" disabled>선택</option>
              {EMAIL_DOMAINS.map((d) => <option key={d} value={d}>{d}</option>)}
              <option value="custom">직접입력</option>
            </select>
            <Button type="button" size="sm" onClick={async () => { validateEmail(); await emailVerify.sendCode(fullEmail()) }} disabled={emailVerify.sending}>
              {emailVerify.sending ? '전송 중...' : '인증 요청'}
            </Button>
          </div>
          <ErrorMsg msg={emailIdField.error} />
        </div>

        <div>
          <FieldLabel label="인증번호" valid={emailVerify.verified} />
          <div className="flex gap-2">
            <Input value={verifyCode} onChange={(e) => setVerifyCode(e.target.value)} placeholder="인증번호 입력" />
            <Button type="button" size="sm" onClick={() => emailVerify.verifyCode(fullEmail(), verifyCode)} disabled={emailVerify.verifying}>
              {emailVerify.verifying ? '확인 중...' : '확인'}
            </Button>
          </div>
          <ErrorMsg msg={verifyError} />
        </div>

        <div>
          <label className="flex cursor-pointer items-center gap-2 text-sm">
            <Checkbox checked={terms} onCheckedChange={(v) => { setTerms(!!v); if (v) setTermsError('') }} />
            약관에 동의합니다.
          </label>
          <ErrorMsg msg={termsError} />
        </div>

        <Button type="submit" className="w-full">회원가입</Button>
      </form>
    </>
  )
}
