// frontend/vue_js/src/fo/views/company/AffiliationListPage.vue
<template>
  <section>
    <CommonPageHeader
      title=""
      strongText="소속 모집 공고"
      :breadcrumbs="[{ text: 'Home', link: '/' }, { text: '소속' }]"
    />
    <div class="container py-4">
      <!-- 검색창 및 필터 영역 -->
      <div
        class="row align-items-center justify-content-between py-3 border-bottom mb-3"
      >
        <!-- 왼쪽: 정렬, 지역 필터 -->
        <div class="col-md-auto">
          <div class="d-flex">
            <select
              class="form-select w-auto me-2"
              v-model="sortType"
              @change="getAfltnList"
            >
              <option selected value="latest">최신순</option>
              <option value="oldest">오래된순</option>
              <option value="view">조회순</option>
              <option value="scrap">스크랩순</option>
              <option value="applicant">지원자순</option>
            </select>
            <!-- 부모 선택 -->
            <select
              v-model="selectedParent"
              @change="onParentChange"
              class="form-select w-auto me-2"
            >
              <option selected value="all">시/도 선택</option>
              <option
                v-for="parent in addressCdList"
                :key="parent.areaCodeSq"
                :value="parent.areaCodeSq"
              >
                {{ removeAllTxt(parent.areaSigungu) }}
              </option>
            </select>

            <!-- 자식 선택 -->
            <select
              v-model="addressCd"
              @change="changeFilter"
              class="form-select w-auto"
            >
              <option :value="selectedParent">전체</option>
              <option
                v-for="address in childrenAddressCdList.children"
                :key="address.areaCodeSq"
                :value="address.areaCodeSq"
              >
                {{ address.areaSigungu }}
              </option>
            </select>
          </div>
        </div>
        <!-- 오른쪽: 검색 -->
        <div class="col-md-auto mt-3 mt-md-0">
          <form class="d-flex" @submit.prevent="changeFilter">
            <select v-model="searchType" class="form-select w-auto me-2">
              <option selected value="all">전체</option>
              <option value="company">회사명</option>
              <option value="content">내용</option>
              <option value="tag">태그</option>
            </select>
            <input
              v-model="keyword"
              class="form-control w-auto me-2"
              type="search"
              placeholder="검색어 입력"
              @keyup.enter="submit"
            />
            <button class="btn btn-primary px-3" type="submit">검색</button>
          </form>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <div class="blog-posts">
            <div v-if="isLoading" class="text-center py-5">
              <div class="spinner-border text-primary mb-3" role="status"></div>
              <p class="text-muted">공고 목록을 불러오는 중입니다...</p>
            </div>
            <template v-else>
              <div class="row" v-if="afltnList.length > 0">
                <div
                  v-for="afltn in afltnList"
                  :key="afltn.sq"
                  class="col-md-4 col-lg-3 mb-4"
                >
                  <article
                    class="post post-medium border-0 pb-0 mb-0 shadow-sm rounded overflow-hidden bg-white d-flex flex-column h-100"
                  >
                    <div
                      class="post-image position-relative d-flex align-items-center justify-content-center bg-light"
                      style="height: 160px; padding: 10px"
                    >
                      <div
                        class="d-block h-100 w-100 position-relative d-flex align-items-center justify-content-center"
                      >
                        <img
                          :src="
                            afltn.profileImg || '/img/logos/Company_logo.png'
                          "
                          @error="
                            $event.target.src = '/img/logos/Company_logo.png'
                          "
                          class="img-fluid rounded-0"
                          style="
                            max-height: 100%;
                            max-width: 100%;
                            object-fit: contain;
                          "
                          alt="기업 이미지"
                        />
                        <div
                          class="position-absolute top-0 end-0 m-2 px-2 py-1 text-white rounded d-flex align-items-center gap-1"
                          style="
                            background-color: rgba(0, 0, 0, 0.5);
                            font-size: 0.8rem;
                          "
                        >
                          <i class="bi bi-eye"></i>
                          <span>{{ formatNum(afltn.viewCnt) }}</span>
                        </div>
                      </div>
                    </div>

                    <div
                      class="post-content p-3 bg-white d-flex flex-column flex-grow-1"
                    >
                      <div
                        class="d-flex justify-content-between align-items-start mb-2"
                      >
                        <h2
                          class="font-weight-bold line-height-2 mb-0 text-truncate"
                          style="font-size: 1rem; max-width: 85%"
                        >
                          <button
                            type="button"
                            class="text-primary fw-bold text-decoration-none border-0 bg-transparent p-0 text-start"
                            @click="clickApplication(afltn)"
                          >
                            {{ afltn.companyNm }}
                          </button>
                        </h2>
                        <button
                          type="button"
                          class="text-muted border-0 bg-transparent p-0"
                          @click="clickScrap(afltn.sq)"
                        >
                          <i
                            class="bi bi-heart-fill"
                            :class="{ active: afltn.isScrap }"
                          ></i>
                        </button>
                      </div>

                      <div
                        class="d-flex flex-wrap gap-1 mb-2 overflow-hidden"
                        style="height: 25px"
                      >
                        <span
                          v-for="tag in afltn.tags"
                          :key="tag"
                          class="badge bg-light text-grey border fw-normal"
                          style="font-size: 0.7rem"
                          >{{ tag }}</span
                        >
                      </div>

                      <div
                        class="description p-2 mb-3 rounded bg-color-grey flex-grow-1"
                        style="min-height: 70px"
                      >
                        <p
                          class="mb-0 text-dark line-clamp-3"
                          style="font-size: 0.85rem; line-height: 1.4"
                        >
                          {{
                            afltn.greeting && afltn.greeting.trim() !== ''
                              ? afltn.greeting
                              : '등록된 소개 문구가 없습니다.'
                          }}
                        </p>
                      </div>

                      <div class="d-grid mt-auto">
                        <button
                          type="button"
                          class="btn btn-sm"
                          :class="
                            afltn.isApply
                              ? 'btn-light disabled'
                              : 'btn-outline-primary'
                          "
                          @click="clickApplication(afltn)"
                        >
                          {{
                            afltn.isApply ? '소속 신청 완료' : '소속 신청하기'
                          }}
                        </button>
                      </div>
                    </div>
                  </article>
                </div>
              </div>
              <div v-else class="text-center py-5 border rounded bg-light">
                <i class="bi bi-info-circle text-muted fs-1 mb-3"></i>
                <p class="mb-0 text-muted">등록된 소속 공고가 없습니다.</p>
              </div>
              <CommonPagination
                :currentPage="currentPage"
                :totalPages="totalPages"
                @update:currentPage="currentPage = $event"
              />
            </template>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
<script setup>
import { api } from '@/axios'
import CommonPageHeader from '@/fo/components/common/CommonPageHeader.vue'
import CommonPagination from '@/fo/components/common/CommonPagination.vue'
import AffiliationRecruit from '@/fo/components/company/AffiliationRecruit.vue'
import { useAffiliationStore } from '@/fo/stores/AffiliationStore'
import { useAlertStore } from '@/fo/stores/alertStore'
import { useModalStore } from '@/fo/stores/modalStore'
import { onMounted, ref, watch } from 'vue'

const isLoading = ref(false)

const modalStore = useModalStore()
const alertStore = useAlertStore()
const affiliationStore = useAffiliationStore()

const afltnList = ref([])

const formatNum = (num) => {
  if (num < 1000) {
    return num.toString()
  } else if (num < 1000000) {
    return (num / 1000).toFixed(1).replace(/\.0$/, '') + 'K'
  } else {
    return (num / 1000000).toFixed(1).replace(/\.0$/, '') + 'M'
  }
}

// 한 화면에 보일 박스 숫자 설정
const size = 8

const currentPage = ref(1)

const totalPages = ref(1)

// 필터
const searchType = ref('all')
const keyword = ref('')
const sortType = ref('latest')

// 주소 코드 리스트
const addressCdList = ref([])
const childrenAddressCdList = ref({})
const selectedParent = ref('all') // 선택된 부모 코드
const addressCd = ref('all')

// 부모 변경 시 자식 초기화
const onParentChange = () => {
  addressCd.value = 'all' // 자식 초기화
  childrenAddressCdList.value = {}
  const parent = addressCdList.value.find(
    (item) => item.areaCodeSq === selectedParent.value,
  )
  childrenAddressCdList.value = parent || {}
  addressCd.value = selectedParent.value
  getAfltnList()
}

// 주소 필터 리스트 불러오기
const getAllAddress = async () => {
  try {
    const res = await api.$get(`/affiliation/address`)
    if (res.status == 'OK') {
      addressCdList.value = res.output
        .filter((tag) => tag.parentAreaCodeSq === null)
        .map((parent) => {
          const children = res.output.filter(
            (cd) => cd.parentAreaCodeSq === parent.areaCodeSq,
          )
          return {
            ...parent,
            children,
          }
        })
    }
  } catch (error) {
    alertStore.show('주소 정보 로드에 실패하였습니다.', 'danger')
  }
}

// 공고 목록 가져오기
const getAfltnList = async () => {
  isLoading.value = true
  try {
    const searchKeyword = keyword.value.trim()
    const searchFilter =
      searchKeyword == null || searchKeyword == ''
        ? ''
        : `&searchType=${searchType.value}&keyword=${searchKeyword}`

    const address = addressCd.value
    const addressFilter =
      address == null || address == 'all' ? '' : `&addressCd=${addressCd.value}`

    const res = await api.$get(
      `/affiliation?page=${currentPage.value}&size=${size}&sortType=${sortType.value}${searchFilter}${addressFilter}`,
    )
    // console.log(res.output)
    if (res) {
      if (res.output.totalElements == 0) {
        totalPages.value = 1
      } else {
        totalPages.value = Math.floor(
          (res.output.totalElements + size - 1) / size,
        )
      }
      afltnList.value = res.output.companies
      affiliationStore.viewerSq = res.output.viewerSq
    }
  } catch (error) {
    alertStore.show('소속 공고를 불러올 수 없습니다.', 'danger')
  } finally {
    isLoading.value = false
  }
}

// 스크랩 버튼 클릭
const clickScrap = async (sq) => {
  if (!affiliationStore.viewerSq) {
    alertStore.show('로그인 후 이용해주세요.', 'danger')
  }
  try {
    const res = await api.$post(`/affiliation/${sq}/scrap`)
    if (res.status == 'OK') {
      alertStore.show(res.message, 'success')
      getAfltnList()
    } else {
      alertStore.show('추천 반영에 실패하였습니다.', 'danger')
    }
  } catch (error) {
    alertStore.show('로그인 후 이용해주세요.', 'danger')
  }
}

// 소속 신청하기 모달
const clickApplication = async (afltnInfo) => {
  await api.$patch(`/affiliation/${afltnInfo.sq}/increment-view`)

  modalStore.openModal(AffiliationRecruit, {
    afltnInfo: afltnInfo,
    onConfirm: getAfltnList,
  })
}

// 검색 또는 채택 상태 변경 시 전체 페이지 수가 변경되므로 현재 페이지를 1페이지로 초기화 후 리스트 갱신
const changeFilter = () => {
  currentPage.value = 1
  getAfltnList()
}

// 전체 글자 없애기
const removeAllTxt = (str) => {
  if (str.endsWith('전체')) {
    return str.slice(0, -2)
  }
  return str
}

watch(currentPage, () => {
  getAfltnList()
})

onMounted(() => {
  getAllAddress()
  getAfltnList()
})
</script>
<style>
.line-clamp-3 {
  display: -webkit-box;
  -webkit-line-clamp: 3; /* 보여줄 줄 수 */
  -webkit-box-orient: vertical;
  overflow: hidden;
  text-overflow: ellipsis;
  word-break: break-all;
}
.bi.bi-heart-fill {
  color: lightgray;
}
.bi.bi-heart-fill.active {
  color: red;
}

article.post:hover {
  transform: translateY(-5px);
  transition: transform 0.3s ease;
  box-shadow: 0 10px 20px rgba(0, 0, 0, 0.1) !important;
}
</style>

// frontend/nextjs/components/company/AffiliationListPage.tsx
'use client'
// Mirrors vue_js/src/fo/views/company/AffiliationListPage.vue
import { useCallback, useEffect, useState } from 'react'
import { Heart, Eye, Search } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Skeleton } from '@/components/ui/skeleton'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import CommonPagination from '@/components/community/CommonPagination'
import { useUserStore } from '@/stores/userStore'
import { alertStore } from '@/stores/alertStore'
import api from '@/lib/api'
import { cn } from '@/lib/utils'

interface AreaCode {
  areaCodeSq: number
  areaSigungu: string
  parentAreaCodeSq: number | null
  children?: AreaCode[]
}

interface AffiliationItem {
  sq: number
  companyNm: string
  profileImg?: string
  viewCnt: number
  isScrap: boolean
  isApply: boolean
  tags: string[]
  greeting?: string
  ceoNm?: string
  openYear?: number
  address?: string
}

interface ResumeOption {
  resumeSq: number
  resumeTtl: string
}

type SortType = 'latest' | 'oldest' | 'view' | 'scrap' | 'applicant'
type SearchType = 'all' | 'company' | 'content' | 'tag'

const formatNum = (n: number) => {
  if (n < 1000) return String(n)
  if (n < 1_000_000) return (n / 1000).toFixed(1).replace(/\.0$/, '') + 'K'
  return (n / 1_000_000).toFixed(1).replace(/\.0$/, '') + 'M'
}

const removeAllTxt = (str: string) =>
  str.endsWith('전체') ? str.slice(0, -2) : str

const PAGE_SIZE = 8

export default function AffiliationListPage() {
  const { affiliatedCompanySq, isLoggedIn, getUserType } = useUserStore()

  const [isLoading, setIsLoading] = useState(false)
  const [list, setList] = useState<AffiliationItem[]>([])
  const [currentPage, setCurrentPage] = useState(1)
  const [totalPages, setTotalPages] = useState(1)

  // 필터 UI 상태
  const [sortType, setSortType] = useState<SortType>('latest')
  const [searchType, setSearchType] = useState<SearchType>('all')
  const [keyword, setKeyword] = useState('')
  // 실제 검색에 적용된 값 (제출 시에만 반영)
  const [activeKeyword, setActiveKeyword] = useState('')
  const [activeSearchType, setActiveSearchType] = useState<SearchType>('all')

  const [addressCdList, setAddressCdList] = useState<AreaCode[]>([])
  const [selectedParent, setSelectedParent] = useState<number | 'all'>('all')
  const [addressCd, setAddressCd] = useState<number | 'all'>('all')
  const [childList, setChildList] = useState<AreaCode[]>([])

  // 신청 모달
  const [modalOpen, setModalOpen] = useState(false)
  const [selectedAfltn, setSelectedAfltn] = useState<AffiliationItem | null>(null)
  const [applyLoading, setApplyLoading] = useState(false)
  const [resumes, setResumes] = useState<ResumeOption[]>([])
  const [selectedResumeSq, setSelectedResumeSq] = useState<number | ''>('')
  const [applyGreeting, setApplyGreeting] = useState('')

  const fetchAddresses = useCallback(async () => {
    try {
      const { data } = await api.get<{ output: AreaCode[] }>('/affiliation/address')
      const parents = data.output
        .filter((a) => a.parentAreaCodeSq === null)
        .map((parent) => ({
          ...parent,
          children: data.output.filter((a) => a.parentAreaCodeSq === parent.areaCodeSq),
        }))
        // 이슈 3: 시/도 가나다순 정렬
        .sort((a, b) => a.areaSigungu.localeCompare(b.areaSigungu, 'ko'))
      setAddressCdList(parents)
    } catch {
      alertStore.show('주소 정보 로드에 실패하였습니다.', 'danger')
    }
  }, [])

  // 이슈 4: keyword/searchType은 deps에서 제외 → 제출 시에만 activeKeyword/activeSearchType 업데이트
  const fetchList = useCallback(async (page: number) => {
    setIsLoading(true)
    try {
      const params: Record<string, unknown> = { page, size: PAGE_SIZE, sortType }
      if (activeKeyword.trim()) {
        params.searchType = activeSearchType
        params.keyword = activeKeyword.trim()
      }
      if (addressCd !== 'all') params.addressCd = addressCd

      const { data } = await api.get<{ output: { companies: AffiliationItem[]; totalElements: number } }>(
        '/affiliation', { params },
      )
      const total = data.output.totalElements
      setTotalPages(total === 0 ? 1 : Math.ceil(total / PAGE_SIZE))
      setList(data.output.companies)
    } catch {
      alertStore.show('소속 공고를 불러올 수 없습니다.', 'danger')
    } finally {
      setIsLoading(false)
    }
  }, [sortType, activeKeyword, activeSearchType, addressCd])

  useEffect(() => { fetchAddresses() }, [fetchAddresses])
  useEffect(() => { fetchList(currentPage) }, [currentPage, fetchList])

  const handleParentChange = (val: string) => {
    const sq = val === 'all' ? 'all' : Number(val)
    setSelectedParent(sq)
    setAddressCd(sq)
    if (sq === 'all') {
      setChildList([])
    } else {
      const parent = addressCdList.find((a) => a.areaCodeSq === sq)
      setChildList(parent?.children ?? [])
    }
    setCurrentPage(1)
  }

  // 이슈 4: 검색은 버튼/Enter 클릭 시에만
  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault()
    setActiveKeyword(keyword)
    setActiveSearchType(searchType)
    setCurrentPage(1)
  }

  const clickScrap = async (sq: number, e: React.MouseEvent) => {
    e.stopPropagation()
    if (!isLoggedIn()) {
      alertStore.show('로그인 후 이용해주세요.', 'danger')
      return
    }
    try {
      const { data } = await api.post<{ message: string }>(`/affiliation/${sq}/scrap`)
      alertStore.show(data.message, 'success')
      fetchList(currentPage)
    } catch {
      alertStore.show('로그인 후 이용해주세요.', 'danger')
    }
  }

  const fetchResumes = async () => {
    try {
      // 이슈 6: 올바른 이력서 목록 endpoint
      const { data } = await api.get<{ output: ResumeOption[] }>('/mypage/resume/select-list')
      setResumes(data.output ?? [])
    } catch {
      setResumes([])
    }
  }

  const clickApplication = async (afltn: AffiliationItem) => {
    api.patch(`/affiliation/${afltn.sq}/increment-view`).catch(() => {})
    setSelectedAfltn(afltn)
    setSelectedResumeSq('')
    setApplyGreeting('')
    setModalOpen(true)
    if (!afltn.isApply && isLoggedIn()) {
      await fetchResumes()
    }
  }

  const handleApply = async () => {
    if (!selectedAfltn) return
    if (!isLoggedIn()) { alertStore.show('로그인 후 이용해주세요.', 'danger'); return }
    // Vue clickRecruit: 기업 회원은 소속(클랜) 신청 불가 — 이력서 체크보다 먼저
    if (getUserType() === 'COMPANY') { alertStore.show('기업 회원은 소속 신청할 수 없습니다.', 'danger'); return }
    if (!selectedResumeSq) { alertStore.show('이력서를 선택해주세요.', 'danger'); return }
    setApplyLoading(true)
    try {
      const { data } = await api.post<{ message: string }>('/affiliation/apply', {
        companySq: selectedAfltn.sq,
        resumeSq: selectedResumeSq,
        companyApplicationGreetingTxt: applyGreeting,
      })
      alertStore.show(data.message ?? '소속 신청이 완료되었습니다.', 'success')
      setModalOpen(false)
      fetchList(currentPage)
    } catch (e) {
      const msg = (e as { response?: { data?: { message?: string } } }).response?.data?.message
      alertStore.show(msg ?? '소속 신청에 실패하였습니다.', 'danger')
    } finally {
      setApplyLoading(false)
    }
  }

  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="mb-6 text-2xl font-bold">소속 모집 공고</h1>

      {/* 필터 영역 */}
      <div className="mb-6 flex flex-col gap-3 border-b pb-4 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex flex-wrap gap-2">
          <select
            value={sortType}
            onChange={(e) => { setSortType(e.target.value as SortType); setCurrentPage(1) }}
            className="cursor-pointer rounded-md border border-input bg-background px-3 py-1.5 text-sm"
          >
            <option value="latest">최신순</option>
            <option value="oldest">오래된순</option>
            <option value="view">조회순</option>
            <option value="scrap">스크랩순</option>
            <option value="applicant">지원자순</option>
          </select>

          <select
            value={String(selectedParent)}
            onChange={(e) => handleParentChange(e.target.value)}
            className="cursor-pointer rounded-md border border-input bg-background px-3 py-1.5 text-sm"
          >
            <option value="all">시/도 선택</option>
            {addressCdList.map((a) => (
              <option key={a.areaCodeSq} value={String(a.areaCodeSq)}>
                {removeAllTxt(a.areaSigungu)}
              </option>
            ))}
          </select>

          {childList.length > 0 && (
            <select
              value={String(addressCd)}
              onChange={(e) => {
                setAddressCd(e.target.value === String(selectedParent) ? (selectedParent as number) : Number(e.target.value))
                setCurrentPage(1)
              }}
              className="cursor-pointer rounded-md border border-input bg-background px-3 py-1.5 text-sm"
            >
              <option value={String(selectedParent)}>전체</option>
              {childList.map((a) => (
                <option key={a.areaCodeSq} value={String(a.areaCodeSq)}>
                  {a.areaSigungu}
                </option>
              ))}
            </select>
          )}
        </div>

        {/* 검색 — Enter 또는 버튼 클릭 시에만 반영 */}
        <form onSubmit={handleSearch} className="flex gap-2">
          <select
            value={searchType}
            onChange={(e) => setSearchType(e.target.value as SearchType)}
            className="cursor-pointer rounded-md border border-input bg-background px-3 py-1.5 text-sm"
          >
            <option value="all">전체</option>
            <option value="company">회사명</option>
            <option value="content">내용</option>
            <option value="tag">태그</option>
          </select>
          <Input
            value={keyword}
            onChange={(e) => setKeyword(e.target.value)}
            placeholder="검색어 입력"
            className="w-40 text-sm"
          />
          <Button type="submit" size="sm">
            <Search className="h-4 w-4" />
          </Button>
        </form>
      </div>

      {/* 목록 — 이슈 1: Vue 원본과 동일한 카드 계층 구조 */}
      {isLoading ? (
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {Array.from({ length: 8 }).map((_, i) => (
            <Skeleton key={i} className="h-72 rounded-xl" />
          ))}
        </div>
      ) : list.length > 0 ? (
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {list.map((item) => (
            <article
              key={item.sq}
              className="flex flex-col overflow-hidden rounded-xl bg-white shadow-sm transition-transform hover:-translate-y-1 hover:shadow-lg"
            >
              {/* 이미지 영역 */}
              <div className="relative flex h-40 items-center justify-center border-b bg-gray-50 p-3">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={item.profileImg || '/img/logos/Company_logo.png'}
                  alt="기업 이미지"
                  className="max-h-full max-w-full object-contain"
                  onError={(e) => { (e.target as HTMLImageElement).src = '/img/logos/Company_logo.png' }}
                />
                <div className="absolute right-2 top-2 flex items-center gap-1 rounded bg-black/50 px-1.5 py-0.5 text-xs text-white">
                  <Eye className="h-3 w-3" />
                  <span>{formatNum(item.viewCnt)}</span>
                </div>
              </div>

              {/* 콘텐츠 영역 */}
              <div className="flex flex-1 flex-col bg-white p-3">
                {/* 회사명 + 스크랩 */}
                <div className="mb-2 flex items-start justify-between">
                  <button
                    type="button"
                    onClick={() => clickApplication(item)}
                    className="max-w-[85%] cursor-pointer truncate text-base font-bold text-primary hover:underline"
                  >
                    {item.companyNm}
                  </button>
                  <button
                    type="button"
                    onClick={(e) => clickScrap(item.sq, e)}
                    className="ml-1 shrink-0 cursor-pointer"
                  >
                    <Heart
                      className={cn(
                        'h-4 w-4 transition-colors',
                        item.isScrap ? 'fill-red-500 text-red-500' : 'text-muted-foreground',
                      )}
                    />
                  </button>
                </div>

                {/* 태그 */}
                <div className="mb-2 flex h-6 flex-wrap gap-1 overflow-hidden">
                  {item.tags.map((tag) => (
                    <span
                      key={tag}
                      className="inline-flex items-center rounded border border-gray-300 bg-gray-100 px-1.5 py-0.5 text-[0.68rem] text-gray-600"
                    >
                      {tag}
                    </span>
                  ))}
                </div>

                {/* 회사 소개 */}
                <div className="mb-3 min-h-[70px] flex-1 rounded bg-gray-100 p-2">
                  <p className="line-clamp-3 text-[0.85rem] leading-[1.4] text-gray-700">
                    {item.greeting?.trim() || '등록된 소개 문구가 없습니다.'}
                  </p>
                </div>

                {/* 신청 버튼 */}
                <button
                  type="button"
                  disabled={affiliatedCompanySq === item.sq || item.isApply}
                  onClick={() => clickApplication(item)}
                  className={cn(
                    'w-full cursor-pointer rounded-md py-1.5 text-sm font-medium transition-colors',
                    affiliatedCompanySq === item.sq || item.isApply
                      ? 'cursor-default bg-gray-100 text-gray-400'
                      : 'border border-primary text-primary hover:bg-primary hover:text-primary-foreground',
                  )}
                >
                  {affiliatedCompanySq === item.sq
                    ? '소속 중'
                    : item.isApply
                      ? '소속 신청 완료'
                      : '소속 신청하기'}
                </button>
              </div>
            </article>
          ))}
        </div>
      ) : (
        <div className="rounded-xl border bg-muted/30 py-16 text-center">
          <p className="text-sm text-muted-foreground">등록된 소속 공고가 없습니다.</p>
        </div>
      )}

      <div className="mt-6">
        <CommonPagination
          currentPage={currentPage}
          totalPages={totalPages}
          onPageChange={(p) => setCurrentPage(p)}
        />
      </div>

      {/* 소속 신청/정보 모달 */}
      <Dialog
        open={modalOpen}
        onOpenChange={(open) => {
          if (!open) { setApplyGreeting(''); setSelectedResumeSq('') }
          setModalOpen(open)
        }}
      >
        <DialogContent className="max-h-[85vh] overflow-y-auto sm:max-w-md">
          <DialogHeader>
            <DialogTitle>
              {selectedAfltn?.isApply ? '소속 정보' : '소속 신청하기'}
            </DialogTitle>
          </DialogHeader>

          {selectedAfltn && (
            <div className="space-y-4 py-2 text-sm">
              <InfoRow label="회사명" value={selectedAfltn.companyNm} />
              <InfoRow label="대표자명" value={selectedAfltn.ceoNm} />
              <InfoRow label="개업년수" value={selectedAfltn.openYear != null ? `${selectedAfltn.openYear}년차` : undefined} />
              <InfoRow label="회사위치" value={selectedAfltn.address} />
              <InfoRow label="회사 설명" value={selectedAfltn.greeting} />

              {selectedAfltn.tags.length > 0 && (
                <div>
                  <p className="mb-1 font-semibold text-primary">관련 태그</p>
                  <div className="flex flex-wrap gap-1">
                    {selectedAfltn.tags.map((tag) => (
                      <Badge key={tag} variant="secondary" className="text-xs">{tag}</Badge>
                    ))}
                  </div>
                </div>
              )}

              {!selectedAfltn.isApply && (
                <>
                  <div>
                    <p className="mb-1 font-semibold text-primary">소속 신청할 이력서</p>
                    {resumes.length > 0 ? (
                      <select
                        value={String(selectedResumeSq)}
                        onChange={(e) => setSelectedResumeSq(Number(e.target.value))}
                        className="w-full cursor-pointer rounded-md border border-input bg-background px-3 py-2 text-sm"
                      >
                        <option value="">이력서를 선택하세요.</option>
                        {resumes.map((r) => (
                          <option key={r.resumeSq} value={String(r.resumeSq)}>{r.resumeTtl}</option>
                        ))}
                      </select>
                    ) : (
                      <p className="text-xs text-muted-foreground">등록된 이력서가 없습니다.</p>
                    )}
                  </div>
                  <div>
                    <p className="mb-1 font-semibold text-primary">간단한 자기소개</p>
                    <textarea
                      value={applyGreeting}
                      onChange={(e) => setApplyGreeting(e.target.value)}
                      placeholder="자기소개를 입력해주세요."
                      rows={4}
                      className="w-full rounded-md border border-input bg-white px-3 py-2 text-sm placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-ring"
                    />
                  </div>
                </>
              )}
            </div>
          )}

          <div className="flex justify-end gap-2 pt-2">
            {selectedAfltn?.isApply ? (
              <Button variant="outline" disabled>
                {affiliatedCompanySq === selectedAfltn?.sq ? '소속 중' : '소속 신청 완료'}
              </Button>
            ) : (
              <Button onClick={handleApply} disabled={applyLoading}>
                {applyLoading ? '신청 중...' : '소속 신청하기'}
              </Button>
            )}
            <Button variant="outline" onClick={() => setModalOpen(false)}>닫기</Button>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  )
}

function InfoRow({ label, value }: { label: string; value?: string | number }) {
  return (
    <div>
      <p className="font-semibold text-primary">{label}</p>
      <p className="text-foreground">{value ?? '-'}</p>
    </div>
  )
}
