// frontend/nextjs/components/main/MainPage.tsx
'use client'
// Mirrors vue_js/src/fo/views/MainPage.vue
import { useCallback, useEffect, useRef, useState } from 'react'
import { useRouter } from 'next/navigation'
import { ChevronLeft, ChevronRight } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { getSkillIconUrl } from '@/lib/skillIconMap'
import { useUserStore } from '@/stores/userStore'
import { alertStore } from '@/stores/alertStore'
import api from '@/lib/api'
import { cn } from '@/lib/utils'

interface PopularProject {
  projectSq: number
  projectTtl: string
  companyNm: string
  projectAddress?: string
  projectExperience?: string
  formattedSalary: string
  projectSkills: string[]
  userTypeCd?: number
}

type SortType = 'views' | 'scraps' | 'apps'

const SLIDES = [
  {
    title: '관심있는 프로젝트 공고 일정\n달력에서 바로 확인하세요',
    subtitle: '스크랩한 기업 프로젝트의 모집 일정 캘린더에서 한눈에 확인하세요',
    action: 'calendar' as const,
  },
  {
    title: '광고 1\n광고가 들어갈 예정입니다.',
    subtitle: '광고 내용',
    action: 'ad' as const,
  },
  {
    title: '광고 2\n광고가 들어갈 예정입니다.',
    subtitle: '광고 내용',
    action: 'ad' as const,
  },
]

const FAQS = [
  {
    q: '프로젝트 지원은 어떻게 하나요?',
    a: '상세보기 페이지에서 지원하기 버튼을 클릭하여 포트폴리오와 함께 지원하실 수 있습니다.',
  },
  {
    q: '회원가입은 필수인가요?',
    a: '공고 열람은 비회원도 가능하나, 프로젝트 지원 및 스크랩 기능을 이용하시려면 회원가입이 필요합니다.',
  },
]

export default function MainPage() {
  const router = useRouter()
  const { getUserType, userTypeCd, isLoggedIn } = useUserStore()
  const userType = getUserType()

  const [currentSlide, setCurrentSlide] = useState(0)
  const [projects, setProjects] = useState<PopularProject[]>([])
  const [currentSort, setCurrentSort] = useState<SortType>('views')
  const [activeFaq, setActiveFaq] = useState<number | null>(null)
  const autoRef = useRef<ReturnType<typeof setInterval> | null>(null)

  const total = SLIDES.length

  const nextSlide = useCallback(() => setCurrentSlide((s) => (s + 1) % total), [total])
  const prevSlide = () => setCurrentSlide((s) => (s - 1 + total) % total)

  // 자동 슬라이드 (Vue 원본에는 없으나 UX 개선)
  useEffect(() => {
    autoRef.current = setInterval(nextSlide, 5000)
    return () => { if (autoRef.current) clearInterval(autoRef.current) }
  }, [nextSlide])

  const handleSlideClick = (action: 'calendar' | 'ad') => {
    if (action === 'calendar') {
      if (!isLoggedIn()) {
        alertStore.show('로그인이 필요한 서비스입니다.', 'danger')
        router.push('/login')
        return
      }
      router.push('/mypage/calendar')
    } else {
      alertStore.show('준비중입니다.', 'danger')
    }
  }

  const fetchPopularProjects = useCallback(async (sortType: SortType) => {
    setCurrentSort(sortType)
    try {
      // /projects/popular 는 ApiResponse 없이 List<> 직접 반환
      const { data } = await api.get<PopularProject[]>('/projects/popular', {
        params: { sortType },
      })
      setProjects(Array.isArray(data) ? data : [])
    } catch {
      console.error('[MainPage] 인기 프로젝트 로드 실패')
    }
  }, [])

  useEffect(() => {
    fetchPopularProjects('views')
  }, [fetchPopularProjects])

  const goToProject = (project: PopularProject) => {
    // userTypeCd 302 = COMPANY → company spec, else user spec
    const path = userTypeCd === 302
      ? `/projects/company/${project.projectSq}`
      : `/projects/user/${project.projectSq}`
    router.push(path)
  }

  // userType 사용 억제 (Vue 원본과 동일하게 userType 기반 라우팅)
  void userType

  const toggleFaq = (i: number) => setActiveFaq(activeFaq === i ? null : i)

  return (
    <div className="bg-[#f8f9fa]">
      {/* ── 배너 캐러셀 ── */}
      <section className="relative h-[64vh] w-full overflow-hidden">
        {SLIDES.map((slide, i) => (
          <div
            key={i}
            onClick={() => handleSlideClick(slide.action)}
            className={cn(
              'absolute inset-0 flex cursor-pointer flex-col items-center justify-center bg-white px-8 transition-opacity duration-500 md:px-[140px]',
              i === currentSlide ? 'z-10 opacity-100' : 'z-0 opacity-0',
            )}
          >
            <h1 className="mb-6 whitespace-pre-line text-center text-3xl font-bold leading-snug text-[#2c3e50] md:text-4xl">
              {slide.title}
            </h1>
            <p className="text-center text-base text-muted-foreground md:text-lg">
              {slide.subtitle}
            </p>
          </div>
        ))}

        {/* 이전/다음 버튼 */}
        <button
          onClick={prevSlide}
          className="absolute left-6 top-1/2 z-20 flex h-10 w-10 -translate-y-1/2 cursor-pointer items-center justify-center rounded-full bg-white/90 shadow-md hover:bg-white"
        >
          <ChevronLeft className="h-5 w-5" />
        </button>
        <button
          onClick={nextSlide}
          className="absolute right-6 top-1/2 z-20 flex h-10 w-10 -translate-y-1/2 cursor-pointer items-center justify-center rounded-full bg-white/90 shadow-md hover:bg-white"
        >
          <ChevronRight className="h-5 w-5" />
        </button>

        {/* 도트 */}
        <div className="absolute bottom-6 right-12 z-20 flex gap-3">
          {SLIDES.map((_, i) => (
            <button
              key={i}
              onClick={() => setCurrentSlide(i)}
              className={cn(
                'h-3 cursor-pointer rounded-full border-2 border-muted-foreground transition-all',
                i === currentSlide ? 'w-8 bg-muted-foreground' : 'w-3 bg-transparent',
              )}
            />
          ))}
        </div>
      </section>

      {/* ── 인기 프로젝트 ── */}
      <section className="border-t border-[#e9ecef] bg-[#f8f9fa] px-4 py-10 md:px-[140px]">
        <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <h2 className="mb-0 text-xl font-bold">인기 프로젝트</h2>
            <p className="text-sm text-muted-foreground">많은 관심을 받고 있는 프로젝트들을 확인해보세요</p>
          </div>
          <div className="flex gap-2">
            {(['views', 'scraps', 'apps'] as SortType[]).map((sort) => (
              <button
                key={sort}
                onClick={() => fetchPopularProjects(sort)}
                className={cn(
                  'cursor-pointer rounded-full px-4 py-1.5 text-sm font-medium transition-colors',
                  currentSort === sort
                    ? 'bg-primary text-primary-foreground'
                    : 'border border-input bg-background text-muted-foreground hover:bg-muted',
                )}
              >
                {sort === 'views' ? '조회순' : sort === 'scraps' ? '스크랩순' : '지원순'}
              </button>
            ))}
          </div>
        </div>

        {projects.length > 0 ? (
          <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">
            {projects.map((p) => (
              <div
                key={p.projectSq}
                onClick={() => goToProject(p)}
                className="cursor-pointer rounded-xl border bg-white p-4 transition-all hover:-translate-y-1 hover:shadow-lg"
              >
                <h5 className="mb-1 truncate text-base font-bold">{p.projectTtl}</h5>
                <p className="mb-1 text-sm text-muted-foreground">{p.companyNm}</p>
                {(p.projectAddress || p.projectExperience) && (
                  <p className="mb-2 text-xs text-muted-foreground">
                    {[p.projectAddress, p.projectExperience].filter(Boolean).join(' / ')}
                  </p>
                )}
                <div className="mb-3 inline-block rounded bg-blue-50 px-2 py-1 text-sm font-extrabold text-primary">
                  {p.formattedSalary}
                </div>
                <div className="flex flex-wrap gap-1">
                  {p.projectSkills.map((skill) => (
                    <Badge key={skill} variant="secondary" className="flex items-center gap-1 text-xs">
                      {/* eslint-disable-next-line @next/next/no-img-element */}
                      <img src={getSkillIconUrl(skill)} alt={skill} width={14} height={14} />
                      {skill}
                    </Badge>
                  ))}
                </div>
              </div>
            ))}
          </div>
        ) : (
          <p className="py-8 text-center text-sm text-muted-foreground">프로젝트를 불러오는 중...</p>
        )}
      </section>

      {/* ── FAQ ── */}
      <section className="border-t border-[#e9ecef] bg-white px-4 py-12 md:px-[140px]">
        <div className="mb-6">
          <h2 className="text-xl font-bold">FAQ</h2>
          <p className="text-sm text-muted-foreground">궁금한 점이 있으시면 FAQ를 확인해보세요</p>
        </div>
        <div className="space-y-3">
          {FAQS.map((faq, i) => (
            <div key={i} className="overflow-hidden rounded-xl border bg-white shadow-sm">
              <button
                onClick={() => toggleFaq(i)}
                className="flex w-full cursor-pointer items-center justify-between px-5 py-4 text-left text-sm font-semibold hover:bg-muted/30"
              >
                {faq.q}
                <ChevronRight
                  className={cn('h-4 w-4 shrink-0 text-muted-foreground transition-transform', activeFaq === i && 'rotate-90')}
                />
              </button>
              {activeFaq === i && (
                <div className="border-t bg-[#fafafa] px-5 py-4 text-sm leading-relaxed text-muted-foreground">
                  {faq.a}
                </div>
              )}
            </div>
          ))}
        </div>
      </section>
    </div>
  )
}

// frontend/vue_js/src/fo/views/MainPage.vue
<template>
  <div class="mainPage">
    <section class="bannerCarouselSection">
      <div class="carouselWrapper">
        <button @click="prevSlide" class="carouselArrow leftArrow">
          <i class="bi bi-chevron-left"></i>
        </button>

        <div class="carouselTrack">
          <div
            class="carouselSlide"
            :class="{ active: currentSlide === 0 }"
            @click="goToCalendar"
          >
            <div class="centerTextArea text-center cursor-pointer">
              <h1 class="heroTitle">
                관심있는 프로젝트 공고 일정<br />달력에서 바로 확인하세요
              </h1>
              <p class="heroSubtitle">
                스크랩한 기업 프로젝트의 모집 일정 캘린더에서 한눈에 확인하세요
              </p>
            </div>
          </div>
          <div
            class="carouselSlide"
            :class="{ active: currentSlide === 1 }"
            @click="goToPage('#')"
          >
            <div class="centerTextArea text-center cursor-pointer">
              <h1 class="heroTitle">광고 1<br />광고가 들어갈 예정입니다.</h1>
              <p class="heroSubtitle">광고 내용</p>
            </div>
          </div>
          <div
            class="carouselSlide"
            :class="{ active: currentSlide === 2 }"
            @click="goToPage('#')"
          >
            <div class="centerTextArea text-center cursor-pointer">
              <h1 class="heroTitle">광고 2<br />광고가 들어갈 예정입니다.</h1>
              <p class="heroSubtitle">광고 내용</p>
            </div>
          </div>
        </div>

        <button @click="nextSlide" class="carouselArrow rightArrow">
          <i class="bi bi-chevron-right"></i>
        </button>

        <div class="carouselDots">
          <button
            v-for="n in totalSlides"
            :key="n"
            class="dot"
            :class="{ active: currentSlide === n - 1 }"
            @click="moveSlide(n - 1)"
          ></button>
        </div>
      </div>
    </section>

    <section class="popularProjectsSection">
      <div class="sectionInner">
        <div class="d-flex justify-content-between align-items-center mb-3">
          <div class="sectionHeaderLeft">
            <h2 class="mb-0">인기 프로젝트</h2>
            <p class="text-muted">
              많은 관심을 받고 있는 프로젝트들을 확인해보세요
            </p>
          </div>
          <div class="filter-tabs d-flex gap-2">
            <button
              class="btn btn-sm btnRounded"
              :class="
                currentSort === 'views'
                  ? 'btn-primary'
                  : 'btn-outline-secondary'
              "
              @click="fetchPopularProjects('views')"
            >
              조회순
            </button>
            <button
              class="btn btn-sm btnRounded"
              :class="
                currentSort === 'scraps'
                  ? 'btn-primary'
                  : 'btn-outline-secondary'
              "
              @click="fetchPopularProjects('scraps')"
            >
              스크랩순
            </button>
            <button
              class="btn btn-sm btnRounded"
              :class="
                currentSort === 'apps' ? 'btn-primary' : 'btn-outline-secondary'
              "
              @click="fetchPopularProjects('apps')"
            >
              지원순
            </button>
          </div>
        </div>

        <div class="projectGrid">
          <div
            v-for="project in projects"
            :key="project.projectSq"
            class="projectCard card h-100"
            @click="goToDetailPage(project.projectSq)"
          >
            <div class="card-body">
              <h5 class="card-title text-truncate">{{ project.projectTtl }}</h5>
              <p class="card-text text-muted mb-1">{{ project.companyNm }}</p>
              <p class="card-text small text-muted mb-2">
                {{ project.projectAddress }} / {{ project.projectExperience }}
              </p>

              <div class="projectPrice text-primary mb-3">
                {{ project.formattedSalary }}
              </div>

              <div class="skillSection mt-auto">
                <div
                  v-for="skillGroup in project.projectSkills"
                  :key="skillGroup"
                  class="mb-2"
                >
                  <div class="btn btn-rounded btn-3d btn-light btn-xs mb-2">
                    <div class="skillIconItem" v-tooltip="skillGroup">
                      <img
                        :src="getSkillIconUrl(skillGroup)"
                        :alt="skillGroup"
                        width="22"
                        height="22"
                      />
                      <span class="skillName ms-2">{{ skillGroup }}</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="faqSection">
      <div class="faqSectionInner">
        <div class="mb-4">
          <h2 class="font-weight-bold">FAQ</h2>
          <p class="text-muted">궁금한 점이 있으시면 FAQ를 확인해보세요</p>
        </div>

        <div class="toggle toggle-primary">
          <section class="toggle" :class="{ active: activeFaq === 0 }">
            <a class="toggle-title" @click.prevent="toggleFaq(0)">
              프로젝트 지원은 어떻게 하나요?
            </a>
            <div class="toggle-content-wrapper" v-show="activeFaq === 0">
              <div class="toggle-content">
                <p>
                  상세보기 페이지에서 지원하기 버튼을 클릭하여 포트폴리오와 함께
                  지원하실 수 있습니다.
                </p>
              </div>
            </div>
          </section>

          <section class="toggle" :class="{ active: activeFaq === 1 }">
            <a class="toggle-title" @click.prevent="toggleFaq(1)">
              회원가입은 필수인가요?
            </a>
            <div class="toggle-content-wrapper" v-show="activeFaq === 1">
              <div class="toggle-content">
                <p>
                  공고 열람은 비회원도 가능하나, 프로젝트 지원 및 스크랩 기능을
                  이용하시려면 회원가입이 필요합니다.
                </p>
              </div>
            </div>
          </section>
        </div>
      </div>
    </section>
    <PopupModal />
  </div>
</template>

<script setup>
import { onMounted, ref } from 'vue'
import { useAlertStore } from '../stores/alertStore'
import { useUserStore } from '../stores/userStore'
import { api } from '@/axios'
import skillIconMap from '@/assets/skillIconMap.js'
import { navigateByUserTypeAndProjectSq } from '../router/userTypeRouter'
import { useRouter } from 'vue-router'
import PopupModal from '../components/common/PopupModal.vue'

const alertStore = useAlertStore()
const userStore = useUserStore()
const userType = userStore.getUserType
const router = useRouter()

const goToCalendar = () => {
  router.push({ name: 'ScheduleCalendar' })
}

const goToPage = (path) => {
  if (path === '#') {
    alertStore.show('준비중입니다.', 'danger')
    return
  }
  // 실제 페이지가 생기면 아래 코드로 이동 가능
  // router.push(path);
}

// 1. 슬라이드 기능 로직
const currentSlide = ref(0)
const totalSlides = 3 // 광고 1, 광고 2

const nextSlide = () => {
  currentSlide.value = (currentSlide.value + 1) % totalSlides
}
const prevSlide = () => {
  currentSlide.value = (currentSlide.value - 1 + totalSlides) % totalSlides
}
const moveSlide = (index) => {
  currentSlide.value = index
}

// 2. 인기 프로젝트 데이터
const projects = ref([])
const currentSort = ref('views')

const fetchPopularProjects = async (sortType) => {
  currentSort.value = sortType
  try {
    const response = await api.$get('/projects/popular', {
      params: { sortType },
    })
    // console.log(response)
    projects.value = response
    // console.log(projects.value)
  } catch (error) {
    console.error('데이터 로드 실패:', error)
  }
}

const goToDetailPage = (projectSq) => {
  navigateByUserTypeAndProjectSq(userType, projectSq)
}

// --- 기술 아이콘 로직 ---
const getSkillIconUrl = (name) => {
  const key = name.toLowerCase().replace(/[\s.]+/g, '')
  return skillIconMap[key] || skillIconMap.default
}

// 3. FAQ 토글 로직
const activeFaq = ref(null) // 기본값 null (모두 닫힘)
const toggleFaq = (index) => {
  activeFaq.value = activeFaq.value === index ? null : index
}

onMounted(() => {
  fetchPopularProjects('views')
})
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
/* 전달해주신 CSS를 표준 클래스로 변환하여 적용 */
body {
  margin: 0;
  padding: 0;
  font-family: 'Pretendard', sans-serif;
}
.mainPage {
  background-color: #f8f9fa;
}

/* 캐러셀 배너 섹션 */
.bannerCarouselSection {
  position: relative;
  width: 100%;
  overflow: hidden;
}
.carouselWrapper {
  position: relative;
  width: 100%;
  height: 64vh;
  overflow: hidden;
}
.carouselTrack {
  position: relative;
  width: 100%;
  height: 100%;
}
.carouselSlide {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  opacity: 0;
  visibility: hidden;
  transition: opacity 0.6s ease-in-out;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 0 140px;
  background-color: white;
}
.carouselSlide.active {
  opacity: 1;
  visibility: visible;
  z-index: 1;
}

.heroTitle {
  font-size: 2.5rem;
  font-weight: bold;
  color: #2c3e50;
  margin-bottom: 1.5rem;
  line-height: 1.4;
}
.heroSubtitle {
  font-size: 1.1rem;
  color: #6c757d;
  line-height: 1.6;
}

.mapSlideWhite {
  gap: 40px;
}
.leftTextArea {
  flex: 0 0 38%;
  z-index: 5;
}
.miniMapWrapper {
  flex: 1;
  max-width: 1100px;
  background: #e9ecef;
  height: 580px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 8px;
}

.carouselArrow {
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
  z-index: 10;
  width: 50px;
  height: 50px;
  border-radius: 50%;
  border: none;
  background: rgba(255, 255, 255, 0.9);
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.15);
}
.leftArrow {
  left: 30px;
}
.rightArrow {
  right: 30px;
}

.carouselDots {
  position: absolute;
  bottom: 30px;
  right: 50px;
  z-index: 10;
  display: flex;
  gap: 12px;
}
.dot {
  width: 12px;
  height: 12px;
  border-radius: 50%;
  border: 2px solid #6c757d;
  background: transparent;
  cursor: pointer;
  padding: 0;
}
.dot.active {
  background: #6c757d;
  width: 32px;
  border-radius: 6px;
}

.cursor-pointer {
  cursor: pointer;
}

/* 인기 프로젝트 섹션 */
.popularProjectsSection {
  padding: 45px 0 35px;
  background: #f8f9fa;
  border-top: 1px solid #e9ecef;
}
.sectionInner {
  padding: 0 140px;
  max-width: 100%;
}
.projectGrid {
  display: grid;
  grid-template-columns: repeat(5, 1fr);
  gap: 2rem;
  margin-top: 2rem;
}
.projectCard {
  border: 1px solid #e9ecef;
  border-radius: 12px;
  background: white;
  transition: all 0.3s ease;
  cursor: pointer;
}
.projectCard:hover {
  transform: translateY(-3px);
  box-shadow: 0 8px 20px rgba(0, 0, 0, 0.1);
}

.projectPrice {
  font-size: 1.15rem;
  font-weight: 800;
  background: #f0f7ff;
  padding: 5px 10px;
  border-radius: 6px;
  display: inline-block;
}

.btnRounded {
  border-radius: 50px;
  padding: 0.4rem 1.2rem;
  font-weight: 500;
}

.filter-tabs {
  display: flex;
  gap: 10px; /* 버튼 사이 간격 */
}

.card-title {
  font-weight: 700;
  font-size: 1.1rem;
}
.faqSection {
  padding: 50px 0 40px;
  background: white;
  border-top: 1px solid #e9ecef;
}

.faqSectionInner {
  padding: 0 140px;
}

/* FAQ 섹션 */
/* 
.faqSectionInner {
  padding: 0 140px;
}
.faqItem {
  background: white;
  border-radius: 12px;
  margin-bottom: 1rem;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);
  overflow: hidden;
}
.faqQuestion {
  width: 100%;
  border: none;
  background: white;
  padding: 1.2rem 1.5rem;
  text-align: left;
  display: flex;
  justify-content: space-between;
  align-items: center;
  font-weight: 600;
}
.faqAnswer {
  padding: 1rem 1.5rem 1.5rem;
  color: #666;
  border-top: 1px solid #f8f9fa;
  line-height: 1.8;
  background-color: #fafafa;
} */

/* 모달 (기본적으로 숨김) */
.modalOverlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: rgba(0, 0, 0, 0.5);
  display: none;
  align-items: center;
  justify-content: center;
  z-index: 9999;
}
.modalContent {
  background: white;
  border-radius: 8px;
  padding: 20px;
  max-width: 400px;
  width: 90%;
}

@media (max-width: 1200px) {
  .sectionInner,
  .faqSectionInner,
  .carouselSlide {
    padding: 0 40px;
  }
  .projectGrid {
    grid-template-columns: repeat(3, 1fr);
  }
}
@media (max-width: 768px) {
  .projectGrid {
    grid-template-columns: repeat(1, 1fr);
  }
  .miniMapWrapper {
    display: none;
  }
  .carouselSlide {
    flex-direction: column;
    text-align: center;
  }
}
</style>
