// frontend/react_js/pages/_app.js
import { useEffect, useState } from 'react'
import { AuthProvider, useAuth } from '@/contexts/AuthContext'
import { AlertProvider } from '@/contexts/AlertContext'
import { api, setClearLoginState } from '@/lib/axios'
import CommonHeader from '@/components/common/CommonHeader'
import CommonFooter from '@/components/common/CommonFooter'
import CommonAlert from '@/components/common/CommonAlert'

function MyApp({ Component, pageProps }) {
  return (
    <AuthProvider>
      <AlertProvider>
        <AppContent Component={Component} pageProps={pageProps} />
      </AlertProvider>
    </AuthProvider>
  )
}

function AppContent({ Component, pageProps }) {
  const { setUserInfo, clearUser } = useAuth()
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
    
    // axios에 clearUser 함수 등록
    setClearLoginState(clearUser)

    // 자동 로그인 체크
    const fetchUserInfo = async () => {
      try {
        const res = await api.$post('/me')
        const data = res.output

        setUserInfo({
          userSq: data.userSq,
          userNm: data.userNm,
          userTypeCd: data.userTypeCd,
        })
      } catch (error) {
        // 자동 로그인 실패 시 로그인 정보 초기화
        console.log('자동 로그인 실패 (정상)')
        // clearUser()는 호출하지 않음 (무한 루프 방지)
      }
    }

    fetchUserInfo()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  // 클라이언트에서만 렌더링 (Hydration 오류 방지)
  if (!mounted) {
    return (
      <div id="app">
        <div className="main">
          <Component {...pageProps} />
        </div>
      </div>
    )
  }

  return (
    <div id="app">
      <CommonHeader />
      <CommonAlert />
      <div className="main">
        <Component {...pageProps} />
      </div>
      <CommonFooter />

      <style jsx global>{`
        #app {
          display: flex;
          flex-direction: column;
          min-height: 100vh;
        }

        .main {
          flex: 1;
          min-height: 700px;
          padding-top: 100px;
        }
      `}</style>
    </div>
  )
}

export default MyApp

// frontend/vue_js/src/App.vue
<template>
  <div>
    <CommonHeader />
    <CommonAlert />
    <div class="main">
      <router-view />
      <CommonModalContainer />
    </div>
    <CommonFooter />
  </div>
</template>

<script setup>
import { onMounted } from 'vue'
import CommonHeader from './fo/components/common/CommonHeader.vue'
import CommonFooter from './fo/components/common/CommonFooter.vue'
import CommonModalContainer from './fo/components/common/CommonModalContainer.vue'
import CommonAlert from './fo/components/common/CommonAlert.vue'
import { useUserStore } from './fo/stores/userStore'
import { api } from '@/axios'
import { setClearLoginState } from '@/axios'

const userStore = useUserStore()

const fetchUserInfo = async () => {
  try {
    const res = await api.$post('/me')
    const data = res.output

    localStorage.setItem('userNm', data.userNm)
    localStorage.setItem('userTypeCd', data.userTypeCd)

    userStore.setUser({
      // 인턴 추가 작업: userSq 추가
      userSq: data.userSq,
      userNm: data.userNm,
      userTypeCd: data.userTypeCd,
    })
  } catch (error) {
    // console.error('자동 로그인 실패:', error)

    // 리프레시 토큰도 없을 경우까지 포함해서 처리
    clearLoginState()
  }
}

const clearLoginState = () => {
  localStorage.removeItem('userNm')
  localStorage.removeItem('userTypeCd')
  localStorage.removeItem('autoLogin')

  userStore.clearUser()
}

function clearLoginStateFunc() {
  localStorage.removeItem('userNm')
  localStorage.removeItem('userTypeCd')
  localStorage.removeItem('autoLogin')
  userStore.clearUser() // store에 로그인 정보 초기화 메서드가 있어야 합니다.
}

setClearLoginState(clearLoginStateFunc)

onMounted(() => {
  fetchUserInfo()
})
</script>

<style>
#app {
  flex-direction: column;
}

.main {
  flex: 1;
  min-height: 700px;
  padding-top: 100px;
}
</style>
