// frontend/react_js/components/auth/CompanySignUpForm.js
import { useState, useEffect, useCallback } from 'react'
import { useAlert } from '@/contexts/AlertContext'
import { api } from '@/lib/axios'
import debounce from 'lodash/debounce'
import CompanyVerificationModal from './CompanyVerificationModal'
import styles from './CompanySignUpForm.module.css'

export default function CompanySignUpForm({ onSubmit }) {
  const { showAlert } = useAlert()

  // 기업 인증 모달 상태
  const [showCompanyModal, setShowCompanyModal] = useState(false)

  // 폼 데이터
  const [form, setForm] = useState({
    id: '',
    password: '',
    confirmPassword: '',
    name: '',
    phone: '',
    emailId: '',
    emailDomain: '',
    verificationCode: '',
    terms: false,
    companyName: '',
    companyCeoName: '',
    companyBizNumber: '',
    companyOpenDate: '',
    sigunguCode: '',
    address: '',
    addressDetail: '',
    latitude: '',
    longitude: '',
    typeCode: 302, // 기업
    signupTypeCode: 204, // 이메일
  })

  // 이메일 도메인 선택
  const [selectedDomain, setSelectedDomain] = useState('')
  const [isCustomDomain, setIsCustomDomain] = useState(false)

  // 유효성 검사 상태
  const [errors, setErrors] = useState({})
  const [validFields, setValidFields] = useState({})

  // 필드 업데이트 함수
  const updateField = (field, value) => {
    setForm(prev => ({ ...prev, [field]: value }))
  }

  // 에러 설정 함수
  const setError = (field, message) => {
    setErrors(prev => ({ ...prev, [field]: message }))
    setValidFields(prev => ({ ...prev, [field]: false }))
  }

  // 유효성 통과 설정 함수
  const setValid = (field) => {
    setErrors(prev => {
      const newErrors = { ...prev }
      delete newErrors[field]
      return newErrors
    })
    setValidFields(prev => ({ ...prev, [field]: true }))
  }

  // ==================== 유효성 검사 함수들 ====================

  // 아이디 중복 검사 (서버 API 호출)
  const validateIdCore = async (id) => {
    if (!id) {
      setError('id', '아이디를 입력해주세요.')
      return
    }
    if (!/^[a-zA-Z0-9]{5,20}$/.test(id)) {
      setError('id', '영문 또는 숫자 5~20자로 입력해주세요.')
      return
    }

    try {
      const res = await api.$get(`/check-id?userId=${id}`)
      if (res) {
        setError('id', '이미 사용 중인 아이디입니다.')
      } else {
        setValid('id')
      }
    } catch (e) {
      setError('id', '서버 오류가 발생했습니다.')
    }
  }

  // 디바운스 적용된 아이디 검사
  const validateId = useCallback(
    debounce((id) => {
      validateIdCore(id)
    }, 500),
    []
  )

  // 비밀번호 유효성 검사
  const validatePassword = () => {
    if (!form.password) {
      setError('password', '비밀번호를 입력해주세요.')
    } else if (!/^(?=.*[A-Za-z])(?=.*\d)(?=.*[!@#$%^&*]).{8,}$/.test(form.password)) {
      setError('password', '8자 이상, 영문·숫자·특수문자를 조합해 입력해주세요.')
    } else {
      setValid('password')
    }
  }

  // 비밀번호 확인 유효성 검사
  const validateConfirmPassword = () => {
    if (!form.confirmPassword) {
      setError('confirmPassword', '비밀번호 확인을 입력해주세요.')
    } else if (form.confirmPassword !== form.password) {
      setError('confirmPassword', '비밀번호가 일치하지 않습니다.')
    } else {
      setValid('confirmPassword')
    }
  }

  // 이름 유효성 검사
  const validateName = () => {
    if (!form.name) {
      setError('name', '담당자 이름을 입력해주세요.')
    } else if (form.name.length < 2) {
      setError('name', '이름은 두 글자 이상 입력해주세요.')
    } else {
      setValid('name')
    }
  }

  // 휴대폰 번호 유효성 검사
  const validatePhone = () => {
    if (!form.phone) {
      setError('phone', '휴대폰 번호를 입력해주세요.')
    } else if (!/^\d{10,11}$/.test(form.phone)) {
      setError('phone', '올바른 휴대폰 번호 형식이 아닙니다. (하이픈 제외)')
    } else {
      setValid('phone')
    }
  }

  // 기업명 유효성 검사
  const validateCompany = () => {
    if (!form.companyName) {
      setError('company', '기업명을 입력해주세요.')
    } else {
      setValid('company')
    }
  }

  // 주소 유효성 검사
  const validateAddress = () => {
    if (!form.address) {
      setError('address', '주소를 입력해주세요.')
    } else {
      setValid('address')
    }
  }

  // 이메일 유효성 검사
  const validateEmail = () => {
    const fullEmail = `${form.emailId}@${form.emailDomain}`
    
    if (!form.emailId) {
      setError('email', '이메일 아이디를 입력해주세요.')
    } else if (isCustomDomain && !form.emailDomain) {
      setError('email', '도메인을 입력해주세요.')
    } else if (!/\S+@\S+\.\S+/.test(fullEmail)) {
      setError('email', '올바른 이메일 주소 형식이 아닙니다.')
    } else {
      setValid('email')
    }
  }

  // 인증번호 유효성 검사
  const validateVerifyCode = () => {
    console.log('verificationCode = ', form.verificationCode)
    if (!form.verificationCode) {
      setError('verifyCode', '인증번호를 입력하세요.')
    } else if (!validFields.verifyCode) {
      setError('verifyCode', '인증을 진행해주세요.')
    }
  }

  // 약관 동의 유효성 검사
  const validateTerms = () => {
    if (!form.terms) {
      setError('terms', '필수 약관에 동의해주세요.')
    } else {
      setValid('terms')
    }
  }

  // ==================== 이벤트 핸들러 ====================

  // 입력 필드 변경 핸들러
  const handleInputChange = (e) => {
    const { name, value, type, checked } = e.target
    updateField(name, type === 'checkbox' ? checked : value)
  }

  // 아이디 입력 핸들러
  const handleIdInput = (e) => {
    const id = e.target.value
    updateField('id', id)
    validateId(id)
  }

  // 도메인 선택 핸들러
  const handleDomainChange = (e) => {
    const value = e.target.value
    setSelectedDomain(value)
    
    if (value === 'custom') {
      updateField('emailDomain', '')
      setIsCustomDomain(true)
    } else {
      updateField('emailDomain', value)
      setIsCustomDomain(false)
    }
    
    validateEmail()
  }

  // 기업 인증 모달 열기
  const openCompanyModal = () => {
    setShowCompanyModal(true)
  }

  // 기업 인증 완료
  const handleCompanyVerificationConfirm = (companyData) => {
    setForm(prev => ({
      ...prev,
      companyName: companyData.companyName,
      companyCeoName: companyData.ceoName,
      companyBizNumber: companyData.bizNumber,
      companyOpenDate: companyData.openDate
    }))
    setShowCompanyModal(false)
    validateCompany()
  }

  // 다음 우편번호 API
  const openPostcode = () => {
    new window.daum.Postcode({
      oncomplete: function(data) {
        let addr = ''
        if (data.userSelectedType === 'R') {
          addr = data.roadAddress
        } else {
          addr = data.jibunAddress
        }

        setForm(prev => ({
          ...prev,
          postcode: data.zonecode,
          address: addr,
          addressDetail: '',
          sigunguCode: data.sigunguCode
        }))

        // 주소 → 좌표 변환
        const geocoder = new window.kakao.maps.services.Geocoder()
        geocoder.addressSearch(addr, function(result, status) {
          if (status === window.kakao.maps.services.Status.OK) {
            setForm(prev => ({
              ...prev,
              latitude: result[0].y,
              longitude: result[0].x
            }))
          }
        })

        validateAddress()
      }
    }).open()
  }

  // 이메일 인증 요청
  const sendVerification = async () => {
    const email = `${form.emailId}@${form.emailDomain}`

    try {
      const response = await api.$post('/email/send-code', { email })
      console.log('인증 이메일 전송 완료', response)
      showAlert(`인증 코드를 전송했습니다. 인증 코드: ${response.output.code}`, 'info')
    } catch (error) {
      console.error('이메일 인증 요청 실패:', error)
      const message = error.response?.data?.message || '이메일 인증 요청에 실패했습니다.'
      setError('email', message)
    }
  }

  // 인증 코드 확인
  const verifyCode = async () => {
    const email = `${form.emailId}@${form.emailDomain}`
    const code = form.verificationCode

    if (!code) {
      setError('verifyCode', '인증번호를 입력하세요.')
      return
    }

    try {
      const response = await api.$post('/email/verify-code', { email, code })
      console.log('인증 성공', response)
      showAlert('이메일 인증에 성공하였습니다.', 'info')
      setValid('verifyCode')
    } catch (error) {
      console.error('인증 코드 검증 실패:', error)
      setError('verifyCode', '인증번호가 일치하지 않습니다.')
      showAlert('이메일 인증에 실패하였습니다.', 'danger')
    }
  }

  // 약관 모달 열기
  const openTermsModal = () => {
    showAlert('약관 모달 기능은 구현 예정입니다.', 'info')
    updateField('terms', true)
  }

  // 폼 제출 핸들러
  const handleSubmit = async (e) => {
    e.preventDefault()

    // 모든 유효성 검사 실행
    await validateIdCore(form.id)
    validatePassword()
    validateConfirmPassword()
    validateName()
    validatePhone()
    validateAddress()
    validateEmail()
    validateVerifyCode()
    validateTerms()

    // 모든 유효성 통과 여부 확인
    const isFormValid = validFields.id &&
      validFields.password &&
      validFields.confirmPassword &&
      validFields.name &&
      validFields.phone &&
      validFields.address &&
      validFields.email &&
      validFields.verifyCode &&
      validFields.terms
    console.log({
      id: validFields.id,
      password : validFields.password,
      confirmPassword : validFields.confirmPassword,
      name : validFields.name,
      phone : validFields.phone,
      address : validFields.address,
      email : validFields.email,
      verifyCode : validFields.verifyCode,
      terms : validFields.terms
    })
    if (isFormValid) {
      onSubmit({ ...form })
    } else {
      console.warn('❌ 유효성 검사 실패. 폼 제출 불가.')
      showAlert('모든 필드를 올바르게 입력해주세요.', 'danger')
    }
  }

  // 주소 변경 감지
  useEffect(() => {
    if (form.address) {
      validateAddress()
    }
  }, [form.address])

  return (
    <>
      <form onSubmit={handleSubmit}>
      {/* 아이디 */}
      <div className="row">
        <div className="form-group col-lg-6">
          <label className="form-label">
            아이디
            {validFields.id && <i className="bi bi-check-circle-fill ms-1" style={{ color: '#007bff' }}></i>}
          </label>
          <input
            type="text"
            name="id"
            value={form.id}
            onChange={handleIdInput}
            className="form-control form-control-lg"
          />
          {errors.id && <div className="invalid-feedback">{errors.id}</div>}
        </div>
      </div>

      {/* 비밀번호 */}
      <div className="row">
        <div className="form-group col-lg-6">
          <label className="form-label">
            비밀번호
            {validFields.password && <i className="bi bi-check-circle-fill ms-1" style={{ color: '#007bff' }}></i>}
          </label>
          <input
            type="password"
            name="password"
            value={form.password}
            onChange={(e) => {
              handleInputChange(e)
              validatePassword()
            }}
            className="form-control form-control-lg"
          />
          {errors.password && <div className="invalid-feedback">{errors.password}</div>}
        </div>
        <div className="form-group col-lg-6">
          <label className="form-label">
            비밀번호 확인
            {validFields.confirmPassword && <i className="bi bi-check-circle-fill ms-1" style={{ color: '#007bff' }}></i>}
          </label>
          <input
            type="password"
            name="confirmPassword"
            value={form.confirmPassword}
            onChange={(e) => {
              handleInputChange(e)
              if (validFields.password) validateConfirmPassword()
            }}
            className="form-control form-control-lg"
          />
          {errors.confirmPassword && <div className="invalid-feedback">{errors.confirmPassword}</div>}
        </div>
      </div>

      {/* 담당자 이름 */}
      <div className="row">
        <div className="form-group col-lg-6">
          <label className="form-label">
            담당자 이름
            {validFields.name && <i className="bi bi-check-circle-fill ms-1" style={{ color: '#007bff' }}></i>}
          </label>
          <input
            type="text"
            name="name"
            value={form.name}
            onChange={(e) => {
              handleInputChange(e)
              validateName()
            }}
            className="form-control form-control-lg"
          />
          {errors.name && <div className="invalid-feedback">{errors.name}</div>}
        </div>
      </div>

      {/* 휴대폰 */}
      <div className="row">
        <div className="form-group col-lg-6">
          <label className="form-label">
            휴대폰 번호
            {validFields.phone && <i className="bi bi-check-circle-fill ms-1" style={{ color: '#007bff' }}></i>}
          </label>
          <input
            type="text"
            name="phone"
            value={form.phone}
            onChange={(e) => {
              handleInputChange(e)
              validatePhone()
            }}
            className="form-control form-control-lg"
          />
          {errors.phone && <div className="invalid-feedback">{errors.phone}</div>}
        </div>
      </div>

      {/* 기업명 */}
      <div className="row">
        <div className="form-group col-lg-6">
          <label className="form-label">
            기업명
            {validFields.company && <i className="bi bi-check-circle-fill ms-1" style={{ color: '#007bff' }}></i>}
          </label>
          <input
            type="text"
            name="companyName"
            value={form.companyName}
            onClick={openCompanyModal}
            onChange={(e) => {
              handleInputChange(e)
              validateCompany()
            }}
            readOnly
            className="form-control form-control-lg"
          />
          {errors.company && <div className="invalid-feedback">{errors.company}</div>}
        </div>
        <div className="form-group col-lg-6">
          <label className="form-label">
            사업자 번호
            {validFields.company && <i className="bi bi-check-circle-fill ms-1" style={{ color: '#007bff' }}></i>}
          </label>
          <input
            type="text"
            name="companyBizNumber"
            value={form.companyBizNumber}
            onChange={handleInputChange}
            className="form-control form-control-lg"
          />
        </div>
      </div>

      {/* 회사 주소 */}
      <div className="row">
        <div className="form-group col-lg-7 mb-2">
          <label className="form-label">
            회사 주소
            {validFields.address && <i className="bi bi-check-circle-fill ms-1" style={{ color: '#007bff' }}></i>}
          </label>
          <input
            type="text"
            name="address"
            value={form.address}
            onClick={openPostcode}
            readOnly
            placeholder="주소를 검색하세요"
            className="form-control form-control-lg"
          />
          {errors.address && <div className="invalid-feedback">{errors.address}</div>}
        </div>

        <div className="form-group col-lg-5">
          <label className="form-label">상세 주소</label>
          <input
            type="text"
            name="addressDetail"
            value={form.addressDetail}
            onChange={handleInputChange}
            className="form-control form-control-lg"
          />
        </div>
      </div>

      {/* 이메일 */}
      <div className="row">
        <div className="form-group col-lg-12">
          <label className="form-label">
            이메일 주소
            {validFields.email && <i className="bi bi-check-circle-fill ms-1" style={{ color: '#007bff' }}></i>}
          </label>
          <div className="input-group">
            <input
              type="text"
              name="emailId"
              value={form.emailId}
              onChange={(e) => {
                handleInputChange(e)
                validateEmail()
              }}
              placeholder="이메일 아이디"
              className="form-control form-control-lg"
            />
            <span className="input-group-text">@</span>

            <input
              type="text"
              name="emailDomain"
              value={form.emailDomain}
              onChange={(e) => {
                handleInputChange(e)
                validateEmail()
              }}
              readOnly={!isCustomDomain}
              placeholder="도메인 입력"
              className="form-control form-control-lg"
            />

            <select
              value={selectedDomain}
              onChange={handleDomainChange}
              className="form-control form-control-lg"
            >
              <option disabled value="">선택하세요</option>
              <option value="naver.com">naver.com</option>
              <option value="gmail.com">gmail.com</option>
              <option value="daum.net">daum.net</option>
              <option value="nate.com">nate.com</option>
              <option value="hotmail.com">hotmail.com</option>
              <option value="custom">직접입력</option>
            </select>

            <button
              type="button"
              className="btn btn-primary btn-lg"
              onClick={sendVerification}
            >
              인증 요청
            </button>
          </div>
          {errors.email && <div className="invalid-feedback">{errors.email}</div>}
        </div>
      </div>

      {/* 인증번호 */}
      <div className="row">
        <div className="form-group col-lg-8">
          <label className="form-label">
            인증번호
            {validFields.verifyCode && <i className="bi bi-check-circle-fill ms-1" style={{ color: '#007bff' }}></i>}
          </label>
          <div className="input-group">
            <input
              type="text"
              name="verificationCode"
              value={form.verificationCode}
              onChange={(e) => {
                handleInputChange(e)
                validateVerifyCode()
              }}
              className="form-control form-control-lg"
            />
            <button
              type="button"
              className="btn btn-primary btn-lg"
              onClick={verifyCode}
            >
              확인
            </button>
          </div>
          {errors.verifyCode && <div className="invalid-feedback">{errors.verifyCode}</div>}
        </div>
      </div>

      {/* 약관 동의 */}
      <div className="row">
        <div className="form-group col">
          <div className="form-check">
            <input
              type="checkbox"
              name="terms"
              id="terms"
              checked={form.terms}
              onChange={(e) => {
                handleInputChange(e)
                validateTerms()
              }}
              className="form-check-input"
            />
            <label htmlFor="terms" className="form-check-label me-1">
              약관에 동의합니다.
            </label>
            <a className="font-primary" style={{ cursor: 'pointer' }} onClick={openTermsModal}>이용약관</a>
          </div>
          {errors.terms && <div className="invalid-feedback">{errors.terms}</div>}
        </div>
      </div>

      {/* 회원가입 버튼 */}
      <div className="row">
        <div className="form-group col text-6">
          <input
            type="submit"
            value="회원가입"
            className="btn btn-primary btn-modern w-100"
          />
        </div>
      </div>
    </form>

    {/* 기업 인증 모달 */}
    {showCompanyModal && (
      <CompanyVerificationModal
        onConfirm={handleCompanyVerificationConfirm}
        onClose={() => setShowCompanyModal(false)}
      />
    )}
    </>
  )
}

// frontend/vue_js/src/fo/components/login&signup/CompanySignUpForm.vue
<template>
  <form @submit.prevent="validateAll">
    <!-- 아이디 -->
    <div class="row">
      <div class="form-group col-lg-6">
        <label class="form-label"
          >아이디<i
            v-if="idValid"
            class="bi bi-check-circle-fill ms-1"
            style="color: #007bff"
          ></i
        ></label>
        <input
          type="text"
          v-model="form.id"
          class="form-control form-control-lg"
          @input="onIdInput"
        />
        <div v-if="idError" class="invalid-feedback">{{ idError }}</div>
      </div>
    </div>

    <!-- 비밀번호 -->
    <div class="row">
      <div class="form-group col-lg-6">
        <label class="form-label"
          >비밀번호
          <i
            v-if="passwordValid"
            class="bi bi-check-circle-fill ms-1"
            style="color: #007bff"
          ></i
        ></label>
        <input
          type="password"
          v-model="form.password"
          class="form-control form-control-lg"
          @input="validatePassword"
        />
        <div v-if="passwordError" class="invalid-feedback">
          {{ passwordError }}
        </div>
      </div>
      <div class="form-group col-lg-6">
        <label class="form-label">
          비밀번호 확인
          <i
            v-if="confirmPasswordValid"
            class="bi bi-check-circle-fill ms-1"
            style="color: #007bff"
          ></i>
        </label>
        <input
          type="password"
          v-model="form.confirmPassword"
          class="form-control form-control-lg"
          @input="passwordValid ? validateConfirmPassword() : ''"
        />
        <div v-if="confirmPasswordError" class="invalid-feedback">
          {{ confirmPasswordError }}
        </div>
      </div>
    </div>

    <!-- 담당자 이름 -->
    <div class="row">
      <div class="form-group col-lg-6">
        <label class="form-label"
          >담당자 이름
          <i
            v-if="nameValid"
            class="bi bi-check-circle-fill ms-1"
            style="color: #007bff"
          ></i
        ></label>
        <input
          type="text"
          v-model="form.name"
          class="form-control form-control-lg"
          @input="validateName"
        />
        <div v-if="nameError" class="invalid-feedback">{{ nameError }}</div>
      </div>
    </div>

    <!-- 휴대폰 -->
    <div class="row">
      <div class="form-group col-lg-6">
        <label class="form-label"
          >휴대폰 번호
          <i
            v-if="phoneValid"
            class="bi bi-check-circle-fill ms-1"
            style="color: #007bff"
          ></i
        ></label>
        <input
          type="text"
          v-model="form.phone"
          class="form-control form-control-lg"
          @input="validatePhone"
        />
        <div v-if="phoneError" class="invalid-feedback">{{ phoneError }}</div>
      </div>
    </div>

    <!-- 기업명 -->
    <div class="row">
      <div class="form-group col-lg-6">
        <label class="form-label"
          >기업명
          <i
            v-if="companyValid"
            class="bi bi-check-circle-fill ms-1"
            style="color: #007bff"
          ></i
        ></label>
        <input
          type="text"
          v-model="form.companyName"
          class="form-control form-control-lg"
          @change="validateCompany"
        />
      </div>
      <div v-if="companyError" class="invalid-feedback">{{ companyError }}</div>
    </div>

    <!-- 회사 주소 -->
    <div class="row">
      <div class="form-group col-lg-7 mb-2">
        <label class="form-label"
          >회사 주소
          <i
            v-if="addressValid"
            class="bi bi-check-circle-fill ms-1"
            style="color: #007bff"
          ></i
        ></label>
        <input
          type="text"
          v-model="form.address"
          class="form-control form-control-lg"
          placeholder="주소를 검색하세요"
          readonly
          @click="openPostcode"
          @input="validateAddress"
        />
        <div v-if="addressError" class="invalid-feedback">
          {{ addressError }}
        </div>
      </div>

      <div class="form-group col-lg-5">
        <label class="form-label">상세 주소</label>
        <input
          type="text"
          v-model="form.addressDetail"
          class="form-control form-control-lg"
          placeholder=""
        />
      </div>
    </div>

    <!-- 이메일 -->
    <div class="row">
      <div class="form-group col-lg-12">
        <label class="form-label"
          >이메일 주소
          <i
            v-if="emailValid"
            class="bi bi-check-circle-fill ms-1"
            style="color: #007bff"
          ></i
        ></label>
        <div class="input-group">
          <input
            type="text"
            v-model="form.emailId"
            class="form-control form-control-lg"
            @input="validateEmail"
            placeholder="이메일 아이디"
          />
          <span class="input-group-text">@</span>

          <!-- 도메인 입력 인풋 -->
          <input
            type="text"
            v-model="form.emailDomain"
            :readonly="!isCustomDomain"
            class="form-control form-control-lg"
            @input="validateEmail"
            placeholder="도메인 입력"
          />

          <!-- 셀렉트 박스 -->
          <select
            v-model="selectedDomain"
            @change="handleDomainChange"
            class="form-control form-control-lg"
          >
            <option disabled value="">선택하세요</option>
            <option value="naver.com">naver.com</option>
            <option value="gmail.com">gmail.com</option>
            <option value="daum.net">daum.net</option>
            <option value="nate.com">nate.com</option>
            <option value="hotmail.com">hotmail.com</option>
            <option value="custom">직접입력</option>
          </select>

          <button
            type="button"
            class="btn btn-primary btn-lg"
            @click="sendVerification"
          >
            인증 요청
          </button>
        </div>
        <div v-if="emailError" class="invalid-feedback">{{ emailError }}</div>
      </div>
    </div>

    <!-- 인증번호 -->
    <div class="row">
      <div class="form-group col-lg-8">
        <label class="form-label"
          >인증번호
          <i
            v-if="verifyCodeValid"
            class="bi bi-check-circle-fill ms-1"
            style="color: #007bff"
          ></i
        ></label>
        <div class="input-group">
          <input
            type="text"
            v-model="form.verificationCode"
            class="form-control form-control-lg"
            @input="validateVerifycode"
          />
          <button
            type="button"
            class="btn btn-primary btn-lg"
            @click="verifyCode"
          >
            확인
          </button>
        </div>
        <div v-if="verifycodeError" class="invalid-feedback">
          {{ verifycodeError }}
        </div>
      </div>
    </div>

    <!-- 약관 동의 -->
    <div class="row">
      <div class="form-group col">
        <div class="form-check">
          <input
            type="checkbox"
            v-model="form.terms"
            id="terms"
            class="form-check-input"
            @change="validateTerms"
          />
          <label for="terms" class="form-check-label me-1">
            약관에 동의합니다.
          </label>
          <a class="font-primary" @click="openTermsModal">이용약관</a>
        </div>
        <div v-if="termsError" class="invalid-feedback">{{ termsError }}</div>
      </div>
    </div>

    <!-- 회원가입 버튼 -->
    <div class="row">
      <div class="form-group col text-6">
        <input
          type="submit"
          value="회원가입"
          class="btn btn-primary btn-modern w-100"
        />
      </div>
    </div>
  </form>
</template>

<script setup>
import { reactive, ref, onMounted, defineEmits, watch } from 'vue'
import { useModalStore } from '@/fo/stores/modalStore'
import { personalAgreementText } from '@/assets/terms'
import TermsAgreementModal from '@/fo/components/login&signup/TermsAgreementModal.vue'
import { useAlertStore } from '@/fo/stores/alertStore'
import { api } from '@/axios'
import { debounce } from 'lodash'

const emit = defineEmits(['submit'])

const validateAll = async () => {
  await validateIdCore(form.id)
  validatePassword()
  validateConfirmPassword()
  validateName()
  validateCompany()
  validatePhone()
  validateAddress()
  validateEmail()
  validateVerifycode()
  validateTerms()

  // 모든 유효성 통과 여부 확인
  const isFormValid =
    idValid.value &&
    passwordValid.value &&
    confirmPasswordValid.value &&
    nameValid.value &&
    companyValid.value &&
    phoneValid.value &&
    addressValid.value &&
    emailValid.value &&
    verifyCodeValid.value && // 인증번호 유효성 처리 보완 필요
    termsValid.value

  if (isFormValid) {
    emit('submit', { ...form })
  } else {
    console.warn('❌ 유효성 검사 실패. 폼 제출 불가.')
  }
}

const form = reactive({
  id: '',
  password: '',
  confirmPassword: '',
  name: '',
  phone: '',
  emailId: '',
  emailDomain: '',
  verificationCode: '',
  terms: false,
  companyName: '',
  companyCeoName: null,
  companyBizNumber: null,
  companyOpenDate: null,
  sigunguCode: '',
  address: '',
  addressDetail: '',
  latitude: '',
  longitude: '',
  typeCode: 302, // 기업
  signupTypeCode: 204, // 이메일
})

const modalStore = useModalStore()
const alertStore = useAlertStore()

const selectedDomain = ref('')
const isCustomDomain = ref(false)

function handleDomainChange() {
  if (selectedDomain.value === 'custom') {
    form.emailDomain = ''
    isCustomDomain.value = true
  } else {
    form.emailDomain = selectedDomain.value
    isCustomDomain.value = false
  }

  validateEmail()
}

const sendVerification = async () => {
  const email = `${form.emailId}@${form.emailDomain}`

  try {
    const response = await api.$post('/email/send-code', { email })
    console.log('인증 이메일 전송 완료', response)
    alertStore.show(
      '인증 코드를 전송했습니다. 인증 코드 : ' + response.output.code,
      'info',
    )
  } catch (error) {
    console.error('이메일 인증 요청 실패:', error)

    // 백엔드가 보내준 에러 메시지 꺼내기 (API 응답 구조에 따라 조정)
    const message =
      error.response?.data?.message || '이메일 인증 요청에 실패했습니다.'
    emailValid.value = false
    emailError.value = message
  }
}

// 인증 코드 확인 함수 (개선 버전)
const verifyCode = async () => {
  verifycodeError.value = ''
  verifyCodeValid.value = false

  const email = `${form.emailId}@${form.emailDomain}`
  const code = form.verificationCode

  if (!code) {
    verifycodeError.value = '인증번호를 입력하세요.'
    return
  }

  try {
    const response = await api.$post('/email/verify-code', { email, code })
    console.log('인증 성공', response)
    alertStore.show('이메일 인증에 성공하였습니다.', 'info')
    verifyCodeValid.value = true
  } catch (error) {
    console.error('인증 코드 검증 실패:', error)
    verifycodeError.value = '인증번호가 일치하지 않습니다.'
    alertStore.show('이메일 인증에 실패하였습니다.', 'danger')
    verifyCodeValid.value = false
  }
}
const idError = ref('')
const passwordError = ref('')
const confirmPasswordError = ref('')
const nameError = ref('')
const phoneError = ref('')
const companyError = ref('')
const addressError = ref('')
const emailError = ref('')
const verifycodeError = ref('')
const termsError = ref('')

const idValid = ref(false)
const passwordValid = ref(false)
const confirmPasswordValid = ref(false)
const nameValid = ref(false)
const phoneValid = ref(false)
const companyValid = ref(false)
const addressValid = ref(false)
const emailValid = ref(false)
const verifyCodeValid = ref('')
const termsValid = ref(false)

// 1. 실제 유효성 검사 + API 호출 함수 (비동기)
const validateIdCore = async (id) => {
  idError.value = ''
  idValid.value = false

  if (!id) {
    idError.value = '아이디를 입력해주세요.'
    return
  }
  if (!/^[a-zA-Z0-9]{5,20}$/.test(id)) {
    idError.value = '영문 또는 숫자 5~20자로 입력해주세요.'
    return
  }

  try {
    const res = await api.$get(`/check-id?userId=${id}`)
    if (res) {
      idError.value = '이미 사용 중인 아이디입니다.'
      idValid.value = false
    } else {
      idValid.value = true
    }
  } catch (e) {
    idError.value = '서버 오류가 발생했습니다.'
    idValid.value = false
  }
}

// 2. 디바운스 적용 함수
const validateId = debounce((id) => {
  validateIdCore(id)
}, 500) // 500ms 딜레이

// 3. input 이벤트 핸들러 (v-model과 함께)
const onIdInput = (e) => {
  const id = e.target.value
  validateId(id)
}

// 비밀번호 유효성 검사
const validatePassword = () => {
  passwordError.value = ''
  passwordValid.value = false
  if (!form.password) {
    passwordError.value = '비밀번호를 입력해주세요.'
  } else if (
    !/^(?=.*[A-Za-z])(?=.*\d)(?=.*[!@#$%^&*]).{8,}$/.test(form.password)
  ) {
    passwordError.value = '8자 이상, 영문·숫자·특수문자를 조합해 입력해주세요.'
  } else {
    passwordValid.value = true
  }
}

// 비밀번호 확인 유효성 검사
const validateConfirmPassword = () => {
  confirmPasswordError.value = ''
  confirmPasswordValid.value = false
  if (!form.confirmPassword) {
    confirmPasswordError.value = '비밀번호 확인을 입력해주세요.'
  } else if (form.confirmPassword !== form.password) {
    confirmPasswordError.value = '비밀번호가 일치하지 않습니다.'
  } else {
    confirmPasswordValid.value = true
  }
}

// 담당자 이름 유효성 검사
const validateName = () => {
  nameError.value = ''
  nameValid.value = false
  if (!form.name) {
    nameError.value = '이름을 입력해주세요.'
  } else if (form.name.length < 2) {
    nameError.value = '이름은 두 글자 이상 입력해주세요.'
  } else {
    nameValid.value = true
  }
}

// 휴대폰 번호 유효성 검사
const validatePhone = () => {
  phoneError.value = ''
  phoneValid.value = false
  if (!form.phone) {
    phoneError.value = '휴대폰 번호를 입력해주세요.'
  } else if (!/^\d{10,11}$/.test(form.phone)) {
    phoneError.value = '올바른 휴대폰 번호 형식이 아닙니다. (하이픈 제외)'
  } else {
    phoneValid.value = true
  }
}

// 기업명&사업자번호 유효성 검사
const validateCompany = () => {
  companyError.value = ''
  companyValid.value = false
  if (!form.companyName) {
    companyError.value = '기업 인증을 진행해주세요.'
  } else {
    companyValid.value = true
  }
}

// 다음 주소 API
function openPostcode() {
  new window.daum.Postcode({
    oncomplete: function (data) {
      let addr = ''
      if (data.userSelectedType === 'R') {
        addr = data.roadAddress
      } else {
        addr = data.jibunAddress
      }

      form.postcode = data.zonecode
      form.address = addr
      form.detailAddress = ''

      // 시군구 추출
      form.sigunguCode = data.sigunguCode

      // 주소 → 좌표 변환
      const geocoder = new window.kakao.maps.services.Geocoder()
      geocoder.addressSearch(addr, function (result, status) {
        if (status === window.kakao.maps.services.Status.OK) {
          form.latitude = result[0].y
          form.longitude = result[0].x
        } else {
          form.latitude = null
          form.longitude = null
        }
      })
    },
  }).open()
}

onMounted(() => {
  // 1. Daum 우편번호 API 확인
  if (!window.daum) {
    console.warn('❌ Daum 우편번호 API (postcode.v2.js)가 로드되지 않았습니다.')
  } else {
    console.log('✅ Daum 우편번호 API 로드됨')
  }

  // 2. Kakao 지도 API 확인 및 동적 로드
  if (!window.kakao || !window.kakao.maps) {
    console.warn(
      '❌ Kakao 지도 API가 로드되지 않았습니다. 스크립트를 동적으로 추가합니다.',
    )

    const kakaoScript = document.createElement('script')
    kakaoScript.src =
      'https://dapi.kakao.com/v2/maps/sdk.js?appkey=90610faa13d02b09f83a700d0885a872&libraries=services'
    kakaoScript.async = true

    console.log('📦 Kakao 지도 API 스크립트를 추가합니다:', kakaoScript.src)

    kakaoScript.onload = () => {
      console.log('✅ Kakao 지도 API 스크립트 onload 실행됨')
      if (window.kakao && window.kakao.maps) {
        console.log('✅ Kakao 지도 API가 동적으로 로드되었습니다.')
      } else {
        console.error(
          '❌ Kakao 지도 API 로드 실패: maps 객체가 여전히 존재하지 않습니다.',
        )
      }
    }

    kakaoScript.onerror = () => {
      console.error('❌ Kakao 지도 API 스크립트 로드 실패')
    }

    document.head.appendChild(kakaoScript)
  } else {
    console.log('✅ Kakao 지도 API가 이미 로드되어 있습니다.')
  }
})

// 주소 유효성 검사
const validateAddress = () => {
  addressError.value = ''
  addressValid.value = false
  if (!form.address) {
    addressError.value = '주소를 입력해주세요.'
  } else {
    addressValid.value = true
  }
}

watch(() => form.address, validateAddress)

// 이메일 주소 유효성 검사
const validateEmail = () => {
  emailError.value = ''
  emailValid.value = false

  // 이메일 아이디와 도메인 결합
  const fullEmail =
    form.emailId +
    '@' +
    (isCustomDomain.value ? form.emailDomain : selectedDomain.value)

  // 이메일 아이디가 없거나, 이메일 도메인이 없을 경우
  if (!form.emailId) {
    emailError.value = '이메일 아이디를 입력해주세요.'
  } else if (isCustomDomain.value && !form.emailDomain) {
    emailError.value = '도메인을 입력해주세요.'
  }
  // 이메일 형식 검사
  else if (!/\S+@\S+\.\S+/.test(fullEmail)) {
    emailError.value = '올바른 이메일 주소 형식이 아닙니다.'
  } else {
    emailValid.value = true
  }
}

const validateVerifycode = () => {
  verifycodeError.value = ''
  if (!form.verificationCode) {
    verifycodeError.value = '인증번호를 입력하세요.'
  } else if (!verifyCodeValid.value) {
    verifycodeError.value = '인증을 진행해주세요.'
  }
  // 인증번호 유효성 여부는 서버 검증 결과에 따라 판단 → 여기서는 설정하지 않음
}

// 약관 동의 유효성 검사
const validateTerms = () => {
  termsError.value = ''
  termsValid.value = false
  if (!form.terms) {
    termsError.value = '필수 약관에 동의해주세요.'
  } else {
    termsValid.value = true
  }
}

// 약관 모달을 열기 위한 함수
function openTermsModal() {
  modalStore.openModal(TermsAgreementModal, {
    title: '개인정보 수집 및 이용 동의서',
    body: personalAgreementText,
    onConfirm: () => {
      alertStore.show('약관 동의 처리되었습니다.', 'success')
      form.terms = true
      modalStore.closeModal()
    },
  })
}
</script>
<style scoped>
select.form-control,
select.form-control-lg {
  line-height: 1.6;
  padding-top: 0.5rem;
  padding-bottom: 0.5rem;
  height: auto;
}

.invalid-feedback {
  color: #007bff;
  display: block;
}
</style>
