// frontend/vue_js/src/fo/components/mypage/personal/ProjectHistorySkillTagModal.vue
<template>
  <Teleport to="body">
    <div class="modal-backdrop">
      <div class="modal-content-wrapper">
        <div class="modal-header">
          <h5 class="modal-title" id="customModalLabel">기술 선택</h5>
        </div>
        <div class="modal-body">
          <form id="techForm">
            <div
              v-for="group in groupedSkillTags"
              :key="group.skillTagSq"
              class="mb-3"
            >
              <h6 class="section-title">{{ group.skillTagNm }}</h6>
              <div class="row row-cols-3 card-grid">
                <div
                  class="col"
                  v-for="skill in group.children"
                  :key="skill.skillTagNm"
                >
                  <button
                    type="button"
                    class="tech-card"
                    :class="{ selected: isSelected(skill) }"
                    @click="toggleSkill(skill)"
                  >
                    <img
                      :src="getSkillIcon(skill.skillTagNm)"
                      :alt="skill.skillTagNm"
                    />
                    <span>{{ skill.skillTagNm }}</span>
                  </button>
                </div>
              </div>
            </div>
            <div class="mt-4 d-flex justify-content-end">
              <button
                @click="handleConfirm"
                type="button"
                class="btn btn-primary"
              >
                선택 완료
              </button>
              <button
                @click="closeModal"
                type="button"
                class="btn btn-secondary ms-2"
              >
                닫기
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </Teleport>
</template>

<script setup>
import { api } from '@/axios'
import { useAlertStore } from '@/fo/stores/alertStore'
import { useModalStore } from '@/fo/stores/modalStore'
import { useProjectStore } from '@/fo/stores/ProjectHistoryStore'
import { ref, onMounted, watch, defineProps } from 'vue'
import skillIconMap from '@/assets/skillIconMap.js'

const props = defineProps({
  projectId: {
    type: [String, Number],
    required: true,
  },
})

const projectStore = useProjectStore()
const alertStore = useAlertStore()
const modalStore = useModalStore()

const selectedSkills = ref([])
const skillList = ref([])
const groupedSkillTags = ref([])

const getSkills = async () => {
  try {
    const res = await api.$get(`/mypage/resume/project-history/skill-tags`)
    if (res.status == 'OK') {
      skillList.value = [...res.output]
      groupedSkillTags.value = skillList.value
        .filter((tag) => tag.skillTagLvl === 1)
        .map((parent) => ({
          ...parent,
          children: skillList.value.filter(
            (tag) => tag.parentSkillTagSq === parent.skillTagSq,
          ),
        }))
    }
  } catch {
    alertStore.show('기술 태그 리스트를 불러올 수 없습니다.', 'danger')
  }
}

const toggleSkill = (skill) => {
  const idx = selectedSkills.value.findIndex(
    (s) => s.skillTagSq === skill.skillTagSq,
  )
  if (idx === -1) {
    selectedSkills.value.push(skill)
  } else {
    selectedSkills.value.splice(idx, 1)
  }
}

const isSelected = (skill) =>
  selectedSkills.value.some((s) => s.skillTagSq === skill.skillTagSq)

const getSkillIcon = (name) => {
  const key = name.toLowerCase().replace(/[\s.]+/g, '')
  return skillIconMap[key] || skillIconMap.default
}

const syncSelectedSkillsWithStore = () => {
  const projectSkills = projectStore.getSkills(props.projectId)
  const allSkills = []
  for (const category in projectSkills) {
    if (Array.isArray(projectSkills[category])) {
      allSkills.push(...projectSkills[category])
    }
  }
  selectedSkills.value = allSkills.map((s) => ({ ...s }))
}

const handleConfirm = () => {
  const categoryMap = {
    기종: 'device',
    Os: 'os',
    운영체제: 'os',
    dbms: 'dbms',
    DB: 'dbms',
    언어: 'language',
    툴: 'tool',
    TOOL: 'tool',
    프레임워크: 'framework',
    FW: 'framework',
  }

  const grouped = {
    device: [],
    os: [],
    dbms: [],
    language: [],
    tool: [],
    framework: [],
  }

  selectedSkills.value.forEach((skill) => {
    const parent = groupedSkillTags.value.find(
      (g) => g.skillTagSq === skill.parentSkillTagSq,
    )
    if (!parent) return
    const parentNameKey = parent.skillTagNm.toLowerCase().replace(/[\s.]+/g, '')

    const category =
      categoryMap[parentNameKey] || categoryMap[parent.skillTagNm.toLowerCase()]

    if (category && category in grouped) {
      grouped[category].push(skill)
    }
  })

  projectStore.setSkills(props.projectId, grouped)
  closeModal()
}

const closeModal = () => modalStore.closeModal()

onMounted(async () => {
  await getSkills()
  syncSelectedSkillsWithStore()
})

watch(
  () => modalStore.isOpen,
  async (isOpen) => {
    if (isOpen) {
      await getSkills()
      syncSelectedSkillsWithStore()
    }
  },
)
</script>

<style scoped>
.modal-backdrop {
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  background-color: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 9999;
}
.modal-content-wrapper {
  background-color: white;
  border-radius: 12px;
  padding: 24px;
  width: 720px;
  max-height: 90vh;
  overflow-y: auto;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
}
.tech-card {
  width: 100%;
  height: 60px;
  border: 1px solid #ccc;
  border-radius: 8px;
  background-color: white;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  cursor: pointer;
  font-weight: 500;
  transition: all 0.2s ease-in-out;
  padding: 0.5rem;
}
.tech-card img {
  width: 20px;
  height: 20px;
}
.tech-card:hover {
  background-color: #d9d9d9;
  border-color: #0d6efd;
}
.tech-card.selected {
  background-color: #d9d9d9 !important;
  border-color: #0d6efd;
  box-shadow: 0 0 0 2px #0d6efd33;
}
</style>

// frontend/react_js/components/myPage/personal/ProjectHistorySkillTagModal.js
import { useState, useEffect } from 'react';
import { createPortal } from 'react-dom';
import { useAlertStore } from '../../../store/alertStore';
import { useModalStore } from '../../../store/modalStore';
import { useProjectStore } from '../../../store/ProjectHistoryStore';
import api from '../../../utils/api';
import skillIconMap from '../../../assets/skillIconMap';
import './ProjectHistorySkillTagModal.css';

const ProjectHistorySkillTagModal = ({ projectId }) => {
  const projectStore = useProjectStore();
  const alertStore = useAlertStore();
  const modalStore = useModalStore();

  const [selectedSkills, setSelectedSkills] = useState([]);
  const [skillList, setSkillList] = useState([]);
  const [groupedSkillTags, setGroupedSkillTags] = useState([]);

  // 기술 태그 목록 조회
  const getSkills = async () => {
    try {
      const res = await api.get(`/mypage/resume/project-history/skill-tags`);
      if (res.status === 'OK') {
        setSkillList([...res.output]);
        
        // 부모-자식 구조로 그룹화
        const grouped = res.output
          .filter((tag) => tag.skillTagLvl === 1)
          .map((parent) => ({
            ...parent,
            children: res.output.filter(
              (tag) => tag.parentSkillTagSq === parent.skillTagSq
            ),
          }));
        
        setGroupedSkillTags(grouped);
      }
    } catch {
      alertStore.show('기술 태그 리스트를 불러올 수 없습니다.', 'danger');
    }
  };

  // 기술 선택/해제 토글
  const toggleSkill = (skill) => {
    setSelectedSkills((prev) => {
      const idx = prev.findIndex((s) => s.skillTagSq === skill.skillTagSq);
      if (idx === -1) {
        return [...prev, skill];
      } else {
        return prev.filter((_, i) => i !== idx);
      }
    });
  };

  // 선택 여부 확인
  const isSelected = (skill) => {
    return selectedSkills.some((s) => s.skillTagSq === skill.skillTagSq);
  };

  // 스킬 아이콘 URL 생성
  const getSkillIcon = (name) => {
    const key = name.toLowerCase().replace(/[\s.]+/g, '');
    return skillIconMap[key] || skillIconMap.default;
  };

  // 스토어에서 선택된 기술 동기화
  const syncSelectedSkillsWithStore = () => {
    const projectSkills = projectStore.getSkills(projectId);
    const allSkills = [];
    
    for (const category in projectSkills) {
      if (Array.isArray(projectSkills[category])) {
        allSkills.push(...projectSkills[category]);
      }
    }
    
    setSelectedSkills(allSkills.map((s) => ({ ...s })));
  };

  // 선택 완료
  const handleConfirm = () => {
    const grouped = {
      device: [],
      os: [],
      dbms: [],
      language: [],
      tool: [],
      framework: [],
    };

    selectedSkills.forEach((skill) => {
      const parent = groupedSkillTags.find(
        (g) => g.skillTagSq === skill.parentSkillTagSq
      );
      if (!parent) return;

      const category = parent.skillTagNm.toLowerCase();
      if (category in grouped) {
        grouped[category].push(skill);
      }
    });

    projectStore.setSkills(projectId, grouped);
    closeModal();
  };

  // 모달 닫기
  const closeModal = () => {
    modalStore.closeModal();
  };

  // 초기 로드
  useEffect(() => {
    const init = async () => {
      await getSkills();
      syncSelectedSkillsWithStore();
    };
    init();
  }, []);

  // 모달 열림 감지
  useEffect(() => {
    const loadData = async () => {
      if (modalStore.isOpen) {
        await getSkills();
        syncSelectedSkillsWithStore();
      }
    };
    loadData();
  }, [modalStore.isOpen]);

  // Portal을 사용하여 body에 렌더링
  return createPortal(
    <div className="modal-backdrop">
      <div className="modal-content-wrapper">
        <div className="modal-header">
          <h5 className="modal-title" id="customModalLabel">
            기술 선택
          </h5>
        </div>
        <div className="modal-body">
          <form id="techForm">
            {groupedSkillTags.map((group) => (
              <div key={group.skillTagSq} className="mb-3">
                <h6 className="section-title">{group.skillTagNm}</h6>
                <div className="row row-cols-3 card-grid">
                  {group.children.map((skill) => (
                    <div className="col" key={skill.skillTagNm}>
                      <button
                        type="button"
                        className={`tech-card ${isSelected(skill) ? 'selected' : ''}`}
                        onClick={() => toggleSkill(skill)}
                      >
                        <img
                          src={getSkillIcon(skill.skillTagNm)}
                          alt={skill.skillTagNm}
                        />
                        <span>{skill.skillTagNm}</span>
                      </button>
                    </div>
                  ))}
                </div>
              </div>
            ))}
            <div className="mt-4 d-flex justify-content-end">
              <button
                onClick={handleConfirm}
                type="button"
                className="btn btn-primary"
              >
                선택 완료
              </button>
              <button
                onClick={closeModal}
                type="button"
                className="btn btn-secondary ms-2"
              >
                닫기
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>,
    document.body
  );
};

export default ProjectHistorySkillTagModal;
